### PR TITLE
Use C++17 in MSVC

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
follow-up of https://github.com/otland/forgottenserver/commit/501ece8476a8644ca71bc791de1eaf236db120d1

sd

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by MillhioreBT — APPROVED** [review]
I use it this way since the new src changes were implemented, no compatibility warnings/errors since then

**Comment by yamaken93** [comment]
Signed.

**Review by ranisalt — APPROVED** [review]

**Comment by ranisalt** [comment]
Seems like a no-brainer to merge. I would merge it straight away, but I will wait until the reviewers you request have responded

**Review by DSpeichert — APPROVED** [review]

**Comment by soul4soul** [comment]
This PR only changes the setting for debug|win32. It's missing debug|x64, release|win32, and release|x64

**Comment by EPuncker** [comment]
> This PR only changes the setting for debug|win32. It's missing debug|x64, release|win32, and release|x64. Better yet this change should be applied to settings.prop so it applies to all build configurations by default.
> 
> The vxcproj and *.props files need some TLC. Conflicting settings are used in some cases. From what I remember configuration in vxcproj overrides imported config from *.props files. For example `settings.prop` sets the warning level to 3 but that setting is overriden for release|x64 builds in the vxcproj file which sets the warning level to 4.
> 
> Now that TFS uses vcpkg it would be worth while to experiment with using cmake on windows with visual studio so we can drop the vcxproj files from the repo. Recent versions of VS studio can open folders with cmake files. VS will generate and maintain the visual studio specific files behind the scene.

https://github.com/otland/forgottenserver/commit/ac72c745a0aaedf143b298f14bdf710dd1f2845d

**Pull request merged**
