### PR TITLE
Fix #1851

### LINKED ISSUE #1851: Open loot
Have two corpses dead.

Open loot.. and open loot first death corpse.

### PR DESCRIPTION
**Pull request by kornholi**
Can someone test this?

Fixes #1851

### CODE REVIEW

**Comment by wgrriffel** [comment]
Im not sure what purpose of force use flag, i assume thats for items that can be used even not being at top of a stack, without the reverse list when a corpse drop on a ladder stack it will get stuck until it decays, maybe should forceUse flag be removed from these corpses.

**Comment by Kamenuvol** [comment]
In my opinion, forceUse flag in corpses is used to get fluids from them even if there is something on it, pretty useless.

**Comment by HeavenIsLost** [comment]
@kornholi 
```
	for (Item* item : boost::adaptors::reverse(*items)) {
		//if the behavior is wrong remove && !Item::items[item->getID()].isContainer()
		if (Item::items[item->getID()].forceUse && !Item::items[item->getID()].isContainer()) {
			return item;
		}
	}
```

This is my fix for this problem.

**Comment by brunominervino** [comment]
@HeavenIsLost fix works fine.

**Comment by DSpeichert** [comment]
Wouldn't this fix now force you to open the corpse instead of walking up a ladder?
(Just thinking out loud, haven't actually tested.)

**Comment by DSpeichert** [comment]
Fixed in #2393

**Pull request closed without merging**
