### PR TITLE
Add underscores in spells file names.

### PR DESCRIPTION
**Pull request by wgrriffel**

### CODE REVIEW

**Comment by marksamman** [comment]
Why? Underscores are better because they don't have to be escaped.

**Comment by wgrriffel** [comment]
@marksamman I noticed all "newer" (like spells) files haven't underscores anymore, so i assumed it needed an indentation, can close if you think isn't what i thought

**Comment by ranisalt** [comment]
I think it should be the other way around, all should have underscores. Spaces are a pain to navigate through the shell and other places where spaces need to be escaped.

**Comment by esfomeado** [comment]
Why not camelCase?

**Comment by marksamman** [comment]
@wgrriffel If you would like to revert your changes and update the spells to use underscores instead I'll accept this PR. Otherwise you may close it.

**Comment by ranisalt** [comment]
> Why not camelCase?

Camel case is horrible for file names, let it be for some code only.

**Comment by wgrriffel** [comment]
@marksamman i'll do it soon, should I change for xml files? (monsters and npcs) as well?

**Comment by marksamman** [comment]
Thanks! Yes, you can open a new PR for that though.

**Pull request merged**
