### PR TITLE
#4536 close parcel send thru mail system to other player

### PR DESCRIPTION
**Pull request by gesior**
Auto close parcel, when it's send to other player thru mail system.

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Review by Berzekz — APPROVED** [review]

**Review by Zbizu — APPROVED** [review]

**Comment by luanluciano93** [comment]
The solution referenced in issue #4535 is better, but you ignore it because it is a canary.

**Comment by joseluis2g** [comment]
> The solution referenced in issue #4535 is better, but you ignore it because it is a canary.

so if you really think that solution is somehow "better", would you be able to elaborate how that PR is better?

**Comment by gesior** [comment]
> The solution referenced in issue #4535 is better, but you ignore it because it is a canary.

I would call it hotfix. Like Gunzodus's "block possibility to send parcel, when you are standing 1 sqm from mailbox". It fixed crash issue, but not solved real problem.

Canary fix does not solve all possible scenarios [ex. moving container into player Inbox from Lua - without 'mail system'] and add new bug to engine: close parcel when you put it on mailbox, even if it's not delivered to player [ex. it's addressed to player that does not exist].

**Comment by EPuncker** [comment]
just a note in case anyone is wondering on why this PR has not been merged _yet_, it was targeted specifically to branch 1.4, which currently doesn't have any active maintainer thus we still haven't decided how to handle this as of yet

if anyone is feeling like doing so, open a new PR targeting master branch and adding the due credits and we will merge it as soon as possible

**Comment by Zbizu** [comment]
> The solution referenced in issue #4535 is better, but you ignore it because it is a canary.

Canary solution is fetching tiles and spectators again and doing at least two extra loops (getSpectators and "for" spectators) when all that had to be done was to add one "if" statement in place that already had all required variables and was already part of the loop that is going through the container spectators.

in short: canary solution has two unnecessary loops

**Pull request closed without merging**
