### PR TITLE
Upgrade raids to lua under globalevents

### PR DESCRIPTION
**Pull request by andremiles1**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Hello guys.
I was thinking... The raid system being separated from globalevents is kind of redundant. Globalevents does the same, and it's not xml so you can do better, more detailed scripts for certain raids. I've included this script I made, but this is just an example, since it lacks delayed raids or multiple stages raids. So the script needs to be upgraded. Keep in mind that my script is designed run with a chance of no raids occurring, so an interval of 30 minutes is advised.
It's also a decision on if we should remove the raid system we currently use, so let's discuss this, please.

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
#1813

**Review by DSpeichert — CHANGES_REQUESTED** [review]
I think your indentation is off.

**Comment by ranisalt** [comment]
I have updated the changes to mirror what would change in #1813 and added a message to raids.xml

**Review by ranisalt — APPROVED** [review]

**Comment by EPuncker** [comment]
closed as #1813 were implemented

**Pull request closed without merging**
