### PR TITLE
Update loot on Spidris Elite

### PR DESCRIPTION
**Pull request by WibbenZ**
Closes #1129
No need to keep it open for a small change.

### CODE REVIEW

**Comment by marksamman** [comment]
How is this any different?

**Comment by WibbenZ** [comment]
Fail... forgot to fix the indentation

**Comment by ninjalulz** [comment]
Squash the commits

**Comment by WibbenZ** [comment]
How? The github uploading program hasen't worked for me, well once haha...

**Comment by ninjalulz** [comment]
Use either Git Shell (should be installed already if you have Git Client) or Git Bash.

```
cd /path/to/github directory
git clone https://github.com/WibbenZ/forgottenserver.git
cd forgottenserver
git reset --soft HEAD~2
git commit -m "new commit message"
git push -f
```

**Comment by WibbenZ** [comment]
It says "ERROR: Permission to otland/forgottenserver.git denied to WibbenZ."
Should I push to my own resp. insted or did I do something wrong?
This only worked once for me when I reinstalled it and did something.. haha

**Comment by marksamman** [comment]
Yes, you should do it in your own repository on branch "patch-19".

**Comment by WibbenZ** [comment]
Mark how do I update the repo I have? Ive tried a couple of diffrent ones I have but nothing changes on the website and it keeps saying im 2 commits ahead and thats from the first commit I did.

**Comment by marksamman** [comment]
You might have to git push after you squash the commits.

**Pull request closed without merging**
