### PR TITLE
Add .env.example file

### PR DESCRIPTION
**Pull request by NRH-AA**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Add .env.example file

**Issues addressed:** 
#4630

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by MillhioreBT** [comment]
image
you forgot the line break at the end

**Comment by Codinablack** [comment]
Fix that little line break and I will also give you an approved review

**Review by EPuncker — APPROVED** [review]

**Comment by slawkens** [comment]
For what is the .env.sample file, if TFS is not even reading the .env?

I tested, it's reading only the environment variables set by export command on linux.

So you need to export each variable with:

```bash
export MYSQL_HOST=127.0.0.1
export MYSQL_USER=root
```

etc.

So I'm wondering, this PR was merged 1 year ago, didn't anyone noticed since then, that it is not working?

Or am I wrong with my thoughts?

**Comment by ranisalt** [comment]
@slawkens it's not TFS' responsibility to apply the environment file, it should be added to the environment prior to starting the server

If using docker/podman, you can use `--env-file` to load them

**Comment by slawkens** [comment]
Maybe you can use library like this one or similar to load the info from .env file?

https://github.com/adeharo9/cpp-dotenv

Or do you have other solution on clean system (Ubuntu 24.04) to apply the .env? (not the docker)

**Comment by ranisalt** [comment]
> Or do you have other solution on clean system (Ubuntu 24.04) to apply the .env?

You can use [dotenvx](https://dotenvx.com/)

I'm not against adding a solution based on cpp-dotenv, but for the time being it would be easier to use dotenvx since it _just works_

**Pull request merged**
