### PR TITLE
Code Improvements: Items amount limitation

### PR DESCRIPTION
**Pull request by omarcopires**

### CODE REVIEW

**Review by EPuncker — CHANGES_REQUESTED** [review]
maybe RESERVED_ITEM_**ID**_START and same with end

**Comment by Znote** [comment]
The title should be more declarative

**Review by EPuncker — APPROVED** [review]

**Comment by nekiro** [comment]
This pr is no longer needed if #3252 gets merged.

**Comment by omarcopires** [comment]
> This pr is no longer needed if #3252 gets merged.

You could add them together

**Comment by nekiro** [comment]
> > This pr is no longer needed if #3252 gets merged.
> 
> You could add them together

Why? There is no point

**Comment by MillhioreBT** [comment]
> > > This pr is no longer needed if #3252 gets merged.
> > 
> > 
> > You could add them together
> 
> Why? There is no point

I agree, this is totally unnecessary now.
btw thank @nekiro yo are very good! 😍

**Pull request closed without merging**
