### PR TITLE
Enhanced monster spells

### PR DESCRIPTION
**Pull request by raymondtfr**
The main reason for this update is to get rid of the way some monster spells are scripted, **looping through combat table objects to be executed**.

I have also updated some spells to use ``onTargetCreature`` callbacks and ``creature:addDamageCondition``, because it gives much more control.

### CODE REVIEW

**Comment by raymondtfr** [comment]
Resolved conflicts and squashed similar commits.

**Comment by diath** [comment]
Aren't some of these spells broken? For instance the electrify spells damage the caster rather than the target?

**Comment by raymondtfr** [comment]
I don't think so (tested most of them), the ``addDamageCondition`` adds the damage condition to the target (first argument).

**Comment by diath** [comment]
>the addDamageCondition adds the damage condition to the target (first argument)

If that's the case then never mind what I said.

**Pull request merged**
