### PR TITLE
call onItemMove and Moved from Game:playerEquipItem

### PR DESCRIPTION
**Pull request by MillhioreBT**
### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
**Issues addressed:** #4193

### CODE REVIEW

**Review by ramon-bernardo — APPROVED** [review]
This fix the problem, looks good!

**Comment by EPuncker** [comment]
great, need to run clang for code style only

**Comment by MillhioreBT** [comment]
> great, need to run clang for code style only

It was broken many PRs ago, I don't know when they merged a PR with code without the required format, but it doesn't come from this PR. the downside of merging PR without c-clang is that it propagates through all subsequent PRs.

If you think it's a good idea that I do the c-clang to the whole source, I'll gladly do it right here in this PR, just let me know.

**Comment by ranisalt** [comment]
@EPuncker we need to do it separately. I don't have this issue locally, format changes nothing, seems to be an issue with the specific version shipped by the OS that runs the action.

**Pull request merged**
