### PR TITLE
Handle ctrl+map click packet (GM teleport)

### PR DESCRIPTION
**Pull request by MillhioreBT**
### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
MapClick!

**Issues addressed:** Nothing!

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by ramon-bernardo** [comment]
Why not? 🆗

**Review by ramon-bernardo — APPROVED** [review]
Why not? 🆗

**Comment by ranisalt** [comment]
Cool. Would be a perfect packet for handling in Lua :sob:

**Review by ranisalt — APPROVED** [review]

**Comment by Erza** [comment]
> Cool. Would be a perfect packet for handling in Lua 😭

Do you have a system in mind for forwarding packets to be handled in Lua? The issue there would be that it has to go across 2 threads, potentially needing a copy of the packet

**Pull request merged**
