### PR TITLE
Add player functions for account storage value manipulation

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
I was writing my VIP system and felt the need for these two new functions, so I think it might be useful to have them directly in TFS.

```lua
-- Set account storage value
player:setAccountStorageValue(5000, 1)
print("Account storage value set.")

-- Get account storage value
local storedValue = player:getAccountStorageValue(5000)
print("Retrieved account storage value:", storedValue)
```

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by moviebr** [comment]
This is very useful, it makes it a lot easier.

**Comment by MillhioreBT** [comment]
Not Bad.

Currently there is already a shorter way to manipulate account storages.

```lua
print(player.accountStorage[key])
player.accountStorage[key] = value
```

**Comment by omarcopires** [comment]
> Not Bad.
> 
> Currently there is already a shorter way to manipulate account storages.
> 
> ```lua
> print(player.accountStorage[key])
> player.accountStorage[key] = value
> ```

I didn't know this method existed xD
But I think it's okay to keep both

**Review by MillhioreBT — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]

**Comment by ranisalt** [comment]
So now we have more than way of doing the same thing...

**Pull request merged**
