### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by nekiro**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Resolved some warnings such as declaration hiding and unsafe integer cast

**Issues addressed:** 
None

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by ranisalt** [comment]
Wtf what compiler was complaining about this

**Comment by MillhioreBT** [comment]
> Wtf what compiler was complaining about this

I thought the same hahaha, it seems that compilers now don't like certain explicit words that have nothing to do with

**Comment by EPuncker** [comment]
> Wtf what compiler was complaining about this

so, we merging this or not? 😄

**Comment by nekiro** [comment]
msvc was complaining about i t

**Pull request merged**
