### PR TITLE
Registered missing weapons to destroy action

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
TFS only had weapons up to **id 2453**, registered to the destroy action script (responsible for allowing players to destroy furniture using weapons), with this update, ALL missing weapons were added, and the script was moved to revscriptsys as well.

list with id/name for reference: https://pastebin.com/GQKeNGAD

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
need testing, but should work

**Comment by torresmon** [comment]
tested with random items with Ids lower and higher than 2453. tried using weapons from hand, backpack, hotkey, ground, browse field and inside corpses. No errors found, everything seems to be working as intended.

**Comment by Codinablack** [comment]
I'm pretty sure weapon.onUse() is called when the weapon gets used as a weapon, in other words, when attacking something, since you can't attack items, I don't see this as being possible with this event, instead, should still be an **Action**, with **item.onUse()**, that would then have the desired outcome for this PR.

**Comment by DSpeichert** [comment]
> I'm pretty sure weapon.onUse() is called when the weapon gets used as a weapon, in other words, when attacking something, since you can't attack items, I don't see this as being possible with this event, instead, should still be an **Action**, with **item.onUse()**, that would then have the desired outcome for this PR.

So you're saying this should not work. But it does? I'm confused but what you're saying is an important behavior detail to understand.

**Comment by EPuncker** [comment]
> > I'm pretty sure weapon.onUse() is called when the weapon gets used as a weapon, in other words, when attacking something, since you can't attack items, I don't see this as being possible with this event, instead, should still be an **Action**, with **item.onUse()**, that would then have the desired outcome for this PR.
> 
> So you're saying this should not work. But it does? I'm confused but what you're saying is an important behavior detail to understand.

it was just a misunderstanding, it can be merged

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
