### PR TITLE
Validate tokens when connecting to gameworld (Fixes #1965)

### LINKED ISSUE #1965: 2FA Security hole
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. You can connect directly to protocolgame using accuont name password (there are more ways to do that)
2. Editing OTClient
3. Route IP Address to loopback, login to local TFS, remove route, connect to remote server without need of 2FA

### Expected behaviour
ProtocolGame should have finally session key generatde by protocollogin that is real session key (random string), not based on acc name & password. There may be more session keys stored in database (and deleted after user changes password or smth..)

### Actual behaviour
Session key is generated by acc name & password, therefore 2FA is useless after connecting directly to protocol game.

### PR DESCRIPTION
**Pull request by kornholi**
Not ideal, but better than not checking at all.

### CODE REVIEW

**Comment by gunzino** [comment]
This is very restrictive to players since they always have to retype account name, password after they want to change character. We simply need session keys management :/

**Comment by kornholi** [comment]
did you actually test it?

**Comment by ranisalt** [comment]
I think the correct approach is to generate a random string for session key, store it in an account->key map and check it. Non-random session keys are not really session keys.

**Comment by gunzino** [comment]
Ohh sorry, I've just saw you pass the ticks too.

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
