### PR TITLE
Update to game protocol 12.91

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
* Update protocol for login in version 12.91.
* Although the code has been updated to `uint16_t` , purchases are still limited to 100 items.  The change was necessary in this pull request to fix crash when opening the NPC window.
* I will not make/bring the code that brings this increase in quantity, as it is complex and a little big, I will focus only on the protocol part.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by luanluciano93** [comment]
for what? If 10.98 doesn't even have the features yet... what's the advantage of advancing a protocol without features?

**Comment by omarcopires** [comment]
> for what? If 10.98 doesn't even have the features yet... what's the advantage of advancing a protocol without features?

The lack of previous content was never a requirement or impediment to updating the protocol.
Also, there is a to-do list here #3871, feel free to contribute in any way.

**Comment by luanluciano93** [comment]
> for what? If 10.98 doesn't even have the features yet... what's the advantage of advancing a protocol without features?

**Review by Zbizu — APPROVED** [review]
initial tests for protocol and otb integrity seem to be fine

**Review by EPuncker — APPROVED** [review]

**Comment by omarcopires** [comment]
* Everything works as it should, except that it is still not possible to acquire more than 100 NPC items.
* New effects, outfits, depots and mount items have been added.
* new items can be added later.

**Pull request merged**
