### PR TITLE
Add Game.createContainer

### PR DESCRIPTION
**Pull request by TheSumm**
Adds Game.createContainer(itemId, size [, position]) which creates most items as a container.

### CODE REVIEW

**Comment by Nu77** [comment]
Nice :+1:

**Comment by EPuncker** [comment]
with this I can create for example a dragon ham with 50 slots? xD

**Comment by ninjalulz** [comment]
Nice :smile: 

@EPuncker no, it doesn't work with stackables.

```C++
if (it.id == 0 || it.group == ITEM_GROUP_DEPRECATED || it.stackable || it.useable || it.moveable || it.pickupable || it.isDepot() || it.isSplash() || it.isDoor()) {
```

**Comment by EPuncker** [comment]
useable & moveable, so I can't use it on weapons and armors neither? :(

**Comment by marksamman** [comment]
Thank you!

**Pull request merged**
