### PR TITLE
Ship default config.lua as config.lua.dist

### PR DESCRIPTION
**Pull request by DSpeichert**
If config.lua.dist exists and config.lua does not,
we will copy config.lua.dist to config.lua on lauch.

### CODE REVIEW

**Comment by ranisalt** [comment]
No need to close files because `fstream` implements RAII.

**Comment by Dagst** [comment]
What is the advantage of having the config.lua.dist being that it will create the config.lua? It would not be easier to leave the config.lua alone. I'm not criticizing, I just want to understand.

**Comment by Kamenuvol** [comment]
@Dagst Now, it ignores your personal config when commiting.

**Comment by Znote** [comment]
@Dagst No more git conflict when pulling in recent changes because you didnt reset config.lua.

**Pull request merged**
