### PR TITLE
Fix 'force' of Player::toggleMount

### PR DESCRIPTION
**Pull request by Riverlance**
@WibbenZ @Kamenuvol :)

### CODE REVIEW

**Comment by jo3bingham** [comment]
Build failure is because you forgot to update the function declaration in player.h.

Also, maybe I'm failing to comprehend, but I don't understand the purpose of this pr. Feel free to explain, if you don't mind.

**Comment by Riverlance** [comment]
Well, I made this possible to toggle the mount by forcing (without the checks).
So, if it forces, it will stops only if the mount id is incorrect.
If the mount id is correct, it will force the mount change (without checking if is in Protection Zone, exhaustion, and so on).

> If you still want this, I add the change on player.h. Else, I understand also. :)

**Comment by jo3bingham** [comment]
Yes, but as it stands, force will always be false unless the user modifies the source directly. It would make much more sense if you added a Lua function that took advantage of this.

**Comment by Riverlance** [comment]
Hmm... if someone teach me by Team Viewer about how I can send my commits changes of my project as a pull request in here, I will be able to send some of my mount functions. xd

**Pull request closed without merging**
