### PR TITLE
feat: add /deleteaccount command to delete player account

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
This pull request adds the /deleteaccount command, allowing administrators to permanently delete a player’s account and all associated data.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ArturKnopik** [comment]
> and all associated data.
well.. i think it should also remove players from account, player items, houses etc... 
player and his data are part of account, removing only account will leaves some trash in db

question: why we need this? 
all accmaker allow to remove accounts from website... better without website player cant create account, nothing to remove

**Comment by DoktorHolzbein** [comment]
> > and all associated data.
> > well.. i think it should also remove players from account, player items, houses etc...
> > player and his data are part of account, removing only account will leaves some trash in db
> 
> question: why we need this? all accmaker allow to remove accounts from website... better without website player cant create account, nothing to remove

That's like asking why cipsoft added ingame shop instead of sms shop

Easier and faster my friend

**Comment by gesior** [comment]
> Easier and faster my friend

It's easier and faster to remove account with this PR, but what problem does it fix?
What is a goal of removing account from database? Except typing this command by mistake or by unexperienced GM.
I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔 

If you want to block some player/account from playing (for cheating, spamming etc.), you can use permanent ban, which bans whole account forever.
@omarcopires Is there any other problem your PR solves?

I work on OTSes for years and never heard about server that removed accounts from database, except when they start 'new edition'. Even then they often remove players or reset their level, not remove whole accounts - to do not force players to create new accounts.

**Comment by kojimhojo** [comment]
> Gesior: 
>It's easier and faster to remove account with this PR, but what problem does it fix? What is a goal of removing account from database? Except typing this command by mistake or by unexperienced GM. I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔
> 
> If you want to block some player/account from playing (for cheating, spamming etc.), you can use permanent ban, which bans whole account forever. @ omarcopires Is there any other problem your PR solves?
> 
> I work on OTSes for years and never heard about server that removed accounts from database, except when they start 'new edition'. Even then they often remove players or reset their level, not remove whole accounts - to do not force players to create new accounts.

I'm very new to the community.
Thank you Gesior for those motivating words that inspire me to **NEVER** do a PR on TFS.
I don't know omarcopires, but if you are criticizing this person:

**192 PRs in total.
114 PRs merged with different difficulties like Lua, C++, etc.**

If you are criticizing a person like this, I don't even want to imagine what would happen to someone like me a pr ago, or anyone else this starting.

It is for reasons like these, from veterans, sacred cows like you, that TFS is dying, and many prefer to contribute in Canary or in their private servers, or not to contribute because they will criticize the feature or code.


`is:pr is:merged author:omarcopires `

image

**Comment by ArturKnopik** [comment]
> > Gesior:
> > It's easier and faster to remove account with this PR, but what problem does it fix? What is a goal of removing account from database? Except typing this command by mistake or by unexperienced GM. I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔
> > If you want to block some player/account from playing (for cheating, spamming etc.), you can use permanent ban, which bans whole account forever. @ omarcopires Is there any other problem your PR solves?
> > I work on OTSes for years and never heard about server that removed accounts from database, except when they start 'new edition'. Even then they often remove players or reset their level, not remove whole accounts - to do not force players to create new accounts.
> 
> I'm very new to the community. Thank you Gesior for those motivating words that inspire me to **NEVER** do a PR on TFS. I don't know omarcopires, but if you are criticizing this person:
> 
> **192 PRs in total. 114 PRs merged with different difficulties like Lua, C++, etc.**
> 
> If you are criticizing a person like this, I don't even want to imagine what would happen to someone like me a pr ago, or anyone else this starting.
> 
> It is for reasons like these, from veterans, sacred cows like you, that TFS is dying, and many prefer to contribute in Canary or in their private servers, or not to contribute because they will criticize the feature or code.

PR is for discussing the code or reasonableness of a given solution, it's normal that sometimes someone doesn't like something.
I won't look at whether someone has 1 commit or 100, if I don't like something I write about it.
Gesior is well know person in OT community, his opinion matters a lot.

**Comment by omarcopires** [comment]
> > Easier and faster my friend
> 
> It's easier and faster to remove account with this PR, but what problem does it fix? What is a goal of removing account from database? Except typing this command by mistake or by unexperienced GM. I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔
> 
> If you want to block some player/account from playing (for cheating, spamming etc.), you can use permanent ban, which bans whole account forever. @omarcopires Is there any other problem your PR solves?
> 
> I work on OTSes for years and never heard about server that removed accounts from database, except when they start 'new edition'. Even then they often remove players or reset their level, not remove whole accounts - to do not force players to create new accounts.

"I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔"

image
image

yes, it was just a pull request to get into the contributors LOL

**Comment by ArturKnopik** [comment]
> > > Easier and faster my friend
> > 
> > 
> > It's easier and faster to remove account with this PR, but what problem does it fix? What is a goal of removing account from database? Except typing this command by mistake or by unexperienced GM. I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔
> > If you want to block some player/account from playing (for cheating, spamming etc.), you can use permanent ban, which bans whole account forever. @omarcopires Is there any other problem your PR solves?
> > I work on OTSes for years and never heard about server that removed accounts from database, except when they start 'new edition'. Even then they often remove players or reset their level, not remove whole accounts - to do not force players to create new accounts.
> 
> "I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in CV 🤔"
> 
> image image
> 
> yes, it was just a pull request to get into the contributors LOL

Screenshot_2024-11-23-06-19-27-144_com android chrome
Otland/discords also are part of the community

**Comment by gesior** [comment]
@omarcopires 
Why did you close it? Because someone commented?

### Tell me what this PR fixes!



> "I see a lot of PRs that look like someone want to get extra activity on GitHub FOSS projects and put his GitHub username in 
> yes, it was just a pull request to get into the contributors LOL

As many people stated above. IDC about your "contributors" status.

I went back to this commit after Issue: https://github.com/otland/forgottenserver/issues/4864
It seems quite related.

> I'm very new to the community.
> Thank you Gesior for those motivating words that inspire me to **NEVER** do a PR on TFS.

We don't need IDE/AI crap posted by random people and that's exactly what this commit does.
As you can see, author closed it. Not me, not TFS maintainer. He knows, he made useless code and still posted it.

**Pull request closed without merging**
