### PR TITLE
Dont allocate new attributes when calling getCustomAttribute

### PR DESCRIPTION
**Pull request by nekiro**
item:getCustomAttribute method was recreating attributes class each time it was called, which in case when they don't exist shouldn't be created.
This was also breaking stackables after you call item:getCustomAttribute they would stop stacking.

How to reproduce?
call thing:getCustomAttribute("")
in events Player:onLook on one stackable item and try to stack it with other of the same type.

### CODE REVIEW

**Comment by ranisalt** [comment]
In that case, just skip `getAttributes` altogether, AFAIK the purpose of that is to allocate and prevent null dereference but you are checking it twice.

**Comment by nekiro** [comment]
@ranisalt what? If attributes is nullptr and we try to getCustomAttribute out of it then it will always create new attributes instance just for that purpose which is pointless. Not sure if you noticed but these calls are in getCustomAttribute method.

**Comment by ranisalt** [comment]
@nekiro I was talking about removing the method `getAttribute`, now I see it is used elsewhere so nevermind.

**Comment by CristoferMartins** [comment]
I think its missing the same check in the functions removeCustomAttribute.

**Comment by nekiro** [comment]
> I think its missing the same check in the functions removeCustomAttribute.

Agree on this one. The same thing will happen if you try to remove attribute which does not exist.

**Comment by nekiro** [comment]
This is ready to be merged.

**Comment by CristoferMartins** [comment]
Its inconsistent that removeCustomAttribute returns true when there is no attributes as getAttributes()->removeCustomAttribute() return false if the attribute doesn't exist.

**Pull request merged**
