### PR TITLE
Improve luascript with checks and error descriptions

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
DRAFT!
- Improve luascript with checks and error descriptions

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by DSpeichert** [comment]
Do you plan on making use of these in this PR?

**Comment by ramon-bernardo** [comment]
> Do you plan on making use of these in this PR?

No, I'm planning another PR with this features.
Ex: `reportErrorFunc(L, getErrorDesc(LUA_ERROR_..._NOT_FOUND));`

**Comment by ramon-bernardo** [comment]
> Do you plan on making use of these in this PR?
Yes, I will keep all changes in the same PR. Despite the previous commit mess

**Comment by ramon-bernardo** [comment]
ll take a break to work on this in the coming days.

:triangular_flag_on_post: I'll map it for the future.

**Pull request closed without merging**
