### PR TITLE
Fix bitset errors

### PR DESCRIPTION
**Pull request by paulosalvatore**
After #1364 changes I'm getting this errors
 ```1>..\src\player.cpp(526): error C2039: 'bitset' : is not a member of 'std'
1>..\src\player.cpp(526): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(526): error C3861: 'icon_bitset': identifier not found
1>..\src\player.cpp(527): error C2065: 'icon_bitset' : undeclared identifier
1>..\src\player.cpp(527): error C2228: left of '.count' must have class/struct/union
1>          type is 'unknown-type'
1>..\src\player.cpp(528): error C2065: 'icon_bitset' : undeclared identifier
1>..\src\player.cpp(529): error C2065: 'icon_bitset' : undeclared identifier
1>..\src\player.cpp(529): error C2228: left of '.reset' must have class/struct/union
1>          type is 'unknown-type'
1>..\src\player.cpp(533): error C2065: 'icon_bitset' : undeclared identifier
1>..\src\player.cpp(533): error C2228: left of '.to_ulong' must have class/struct/union
1>          type is 'unknown-type'
1>..\src\player.cpp(2215): error C2039: 'bitset' : is not a member of 'std'
1>..\src\player.cpp(2215): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(2215): error C3861: 'bitset': identifier not found
1>..\src\player.cpp(2216): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(2232): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(2232): error C2228: left of '.reset' must have class/struct/union
1>          type is 'unknown-type'
1>..\src\player.cpp(2233): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(2233): error C2228: left of '.to_ulong' must have class/struct/union
1>          type is 'unknown-type'
1>..\src\player.cpp(4032): error C2039: 'bitset' : is not a member of 'std'
1>..\src\player.cpp(4032): error C2065: 'bitset' : undeclared identifier
1>..\src\player.cpp(4032): error C2228: left of '.count' must have class/struct/union
1>          type is 'const uint8_t'```

![bitset errors](https://cloud.githubusercontent.com/assets/7906171/7685272/6e925a6c-fd63-11e4-9992-18c09281aa26.png)

Revert this line can solve it

### CODE REVIEW

**Comment by djarek** [comment]
It probably makes more sense to move that include in the files that actually use the bitset.

**Comment by paulosalvatore** [comment]
I tried but it shows more and more errors.. I didn't found a best solution for this

**Comment by marksamman** [comment]
Fixed in 7cfd48d38c8fe0211d6a4045c562107c3d85e742

**Comment by paulosalvatore** [comment]
Thanks Mark

**Pull request closed without merging**
