### PR TITLE
Fix double initialization of Database class

### PR DESCRIPTION
**Pull request by ArturKnopik**
Fix double initialization of `Database` class, `Database`  now become true singleton 
### Pull Request Prelude

- [X] I have followed [proper The Forgotten Server code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:**

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by nekiro** [comment]
DatabaseTasks operates in its own thread, currently with this change you access the singleton from two different threads simultaneously. This code now is probably not thread safe, thus broken.

**Comment by ArturKnopik** [comment]
Good point, need to be checked

**Comment by kygov** [comment]
So database tasks are no longer asynchronously?

**Comment by nekiro** [comment]
> So database tasks are no longer asynchronously?
> 
> https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L4184 https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L4224

They are, using the same instance doesn't make it synchronous, but in special cases where simultaneous access could occur it will not cause undefined behaviour. If you meant it will not execute at the same time, it never did, mysql has to queue these actions anyway for obvious reasons

**Comment by kygov** [comment]
AFAIK previous it had its own connection to mysql and you could execute two queries in same time if they were not to same table (then mysql would lock it).
I used to move queries to database tasks many times to offload main thread.
Servers sometimes have heavy sql queries that take up to 100ms, in this case I think they will just block the main thread.

Someone should check it.

**Pull request merged**
