### PR TITLE
Remove compat function from swimming.lua

### PR DESCRIPTION
**Pull request by WibbenZ**
doSetCreatureOutfit is not a compat function, no need to use it in the
datapack.

### CODE REVIEW

**Comment by ranisalt** [comment]
I'm pretty sure you don't need to specify all attributes, only `lookType`, can you check?

**Comment by WibbenZ** [comment]
No need to check it, if we don't modify them we will still use our "old" colors.

**Comment by ranisalt** [comment]
But the swimming looktype has no color settings, it just won't apply

**Comment by WibbenZ** [comment]
I was wrong, it worked as you said.
Updated the PR.

**Comment by ranisalt** [comment]
TOLD YA

Thanks!

**Pull request merged**
