### PR TITLE
Fix subType in loot

### PR DESCRIPTION
**Pull request by MillhioreBT**
### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
**Issues addressed:** #3476

### BTW
We will probably have to add `subType="0"` to many liquid containers in all monsters

### CODE REVIEW

**Comment by nekiro** [comment]
This is very problematic, whole the subtype thing is bad implementation. I would say just create new variables for xml files like fluidType, charges etc and leave subType like it's used now and then edit monsters xml files to drop items correctly.

**Comment by MillhioreBT** [comment]
> This is very problematic, whole the subtype thing is bad implementation. I would say just create new variables for xml files like fluidType, charges etc and leave subType like it's used now and then edit monsters xml files to drop items correctly.

I think it is a good option

**Comment by MillhioreBT** [comment]
Anyone who wants to have an opinion about what @nekiro is proposing can do so

**Comment by EPuncker** [comment]
I agree with nekiro, and everything will be okay as long as we keep backward compatibility

**Comment by EPuncker** [comment]
fixed on https://github.com/otland/forgottenserver/commit/9d01be7061c96e7bd46e8c68529f412888cfb2d7

**Pull request closed without merging**
