### PR TITLE
[WIP] Proper signal handling

### PR DESCRIPTION
**Pull request by ranisalt**
I have started working in issue #770, which addresses the capability of handling signals. It is easy to implement some of the signals. In the issue, we have thought of handling SIGINT to shutdown the server properly e.g. on Ctrl+C, SIGSTOP/SIGCONT to close and open game server and SIGHUP to reload configuration files, as some system daemons (namely systemd and OpenRC) tend to do.

This would make it easy to run the server in background as a daemon without the need of tools such as nohup and screen, and maybe ship the server in package managers for even easier installation.

Preview with SIGINT:
Preview

QUESTION: how could one reload the entirety of server configuration? Something like a `/reload all` command would do. I have checked the `/reload` command and it needs a keyword to reload only a single part of configuration, though it would be possible to just reload one by one, there may be a simpler way to do it.

### CODE REVIEW

**Comment by gugahoa** [comment]
+1
I agree with your suggestion of SIGSTOP, SIGCONT and SIGHUP. I would suggest one signal for server saving, without the need to close the game servers.

**Comment by ranisalt** [comment]
I vote on USR1 for saving, as this signal has no specific meaning and there are no signals that mean to save the process.

**Comment by djarek** [comment]
Perhaps you should move the handler definitions and registration to a separate file for readability?

**Comment by diath** [comment]
How about a Lua function to pass the signals to? This way we could keep sane defaults while allowing people to customize them the way they want.

**Comment by djarek** [comment]
```
A signal may be generated (and thus pending) for a process as
   a whole (e.g., when sent using kill(2)) or for a specific
   thread (e.g., certain signals, such as SIGSEGV and SIGFPE,
   generated as a consequence of executing a specific machine-
   language instruction are thread directed, as are signals
   targeted at a specific thread using pthread_kill(3)).  A
   process-directed signal may be delivered to any one of the
   threads that does not currently have the signal blocked.  If
   more than one of the threads has the signal unblocked, then
   the kernel chooses an arbitrary thread to which to deliver
   the signal.
```
The kernel is theoretically free to choose any thread to run the signal handler. Which could cause a race condition on the lua script environment/game state. We could theoretically just add the a dispatcher task from the handler, but taking locks from within a signal handler is a really bad idea.

**Comment by marksamman** [comment]
I'll just leave this link with recommendations here for now:
https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=1420

**Comment by ranisalt** [comment]
Yes, it should not mess with Lua. This is a core functionality and thus should be handled in the C++ part.

@djarek I think using already made functions, such as setting game state to shutdown, is thread safe and does not cause race. I should investigate it further later.

**Comment by djarek** [comment]
If we are to be pedantic, changing the "game state" flag outside the dispatcher thread will cause a race on the flag, and we risk torn write etc. In most cases this isn't going to screw anything up, however, the behavior of the application is undefined (can be fixed easily by using the atomic<> template for the flag and use relaxed memory ordering so that we don't change the performance).

**Comment by HeavenIsLost** [comment]
Its kinda of the off topic, but the dispatcher thread is the one which room game world? Which one thread run the services/protocols? How much threads there is in tfs?

**Comment by djarek** [comment]
Currently there are 4 threads:
*Dispatcher (Game logic)
*Scheduler
*Asynchronous I/O service (networking)
*Asynchronous database task dispatcher.

**Comment by ranisalt** [comment]
Well, what if we create a new task in the dispatcher to shutdown the game?

We should be pedantic, we can not risk losing server data because of a bad implementation :P

**Comment by marksamman** [comment]
It may be safe to add a dispatcher task from a signal handler **if** we make the taskLock mutex recursive. The safest way in Linux is using signalfd, but it's not portable.

**Comment by djarek** [comment]
@ranisalt
Adding a task is not a problem in itself. However, a signal handler is allowed to interrupt a thread in any arbitrary location, which means that the handler could be called just after the dispatcher task mutex has been acquired. The handler would attempt to acquire the mutex and the dispatcher thread would deadlock with itself. 

Recursive mutexes impose additional overhead. I see little benefit in providing a way to define signal handlers in lua. If someone really has the need for a custom handler then we should assume they have the knowledge to modify the handlers/add custom ones. We shouldn't overgeneralize with features like these and we should optimize for the most common use-case.

I forgot to mention that this behavior (namely, that any thread is allowed to be the executor of the handler) is the default and I believe that it is possible to block and enable signal handlers for specific threads. Still, you need to be careful and should limit access to variables that are either volatile or atomic (the latter is preferable) to avoid latent bugs.

**Comment by ranisalt** [comment]
According to [this part](https://github.com/torvalds/linux/blob/54e514b91b95d6441c12a7955addfb9f9d2afc65/kernel/signal.c#L921-L956) of Linux, only the threads that register the signals can be signaled. So I guess it would be good to register the signals in the dispatcher or the main thread only. The problem is this behavior is Linux-only and it can't be guaranteed to work on Windows.

**Comment by djarek** [comment]
BTW, something that might not be obvious at first: only functions that are reentrant (being thread safe is not enough) can be called within a signal handler. That means that even memory allocation within a signal handler would cause a race condition and potentially corrupt heap metadata. This means that both creating a dispatcher task and adding it to the task list are unsafe and would cause undefined behavior.

**Comment by marksamman** [comment]
Closing this as I don't see any progress, and signal handling is a hard problem to solve with portability in mind. Once we create a new admin protocol, there should be a command line tool to send "signals".

**Comment by ranisalt** [comment]
Yes, that proved to be a challenge by now. It's better to wait for changes :D

**Comment by djarek** [comment]
@marksamman 
So are we giving up on signal handling and just replacing it with the admin protocol or are both going to be implemented?

**Comment by marksamman** [comment]
@djarek I'm still OK with catching SIGTERM to save and shutdown gracefully if we can get it right; but the admin protocol is going to be implemented regardless.

**Pull request closed without merging**
