### PR TITLE
Moved slots_t to enums.h

### PR DESCRIPTION
**Pull request by DanielChabrowski**
A change I was talking about in #2312. Sorted includes would result in a compilation error from items or movements - I don't remember. I don't see any reason why it shouldn't be in enums.h.

### CODE REVIEW

**Comment by DanielChabrowski** [comment]
@EvulMastah It would work but honestly I don't even know the difference between types of content that are in these two files. Both have enums, only enums has also structs.

**Comment by ranisalt** [comment]
Enums and consts should be defined on the files where they make sense. I think those separate files (and definitions) are legacy from otserv.

**Comment by DanielChabrowski** [comment]
So you guys wanna move it to const.h or leave it in enums.h?

How about dividing those definitions into separate server-side-only and client-side-only files?

**Comment by DSpeichert** [comment]
I agree with @ranisalt, this doesn't seem like a move in the right direction.

**Pull request closed without merging**
