### PR TITLE
Use shared_ptr for GuildRank

### PR DESCRIPTION
**Pull request by ninjalulz**
This should resolve the crash bug that occurs in `Player::getDescription`.

Related issue: #2561

### CODE REVIEW

**Comment by lollers420** [comment]
Bad fix. breaks changing rank names completley they will not be updated till after a server restart!

**Comment by Lyuzera** [comment]
> Bad fix. breaks changing rank names completley they will not be updated till after a server restart!

can you explained it? how to reproduce it? I use that fix for a long time and it solves my problem.

**Comment by lollers420** [comment]
> > Bad fix. breaks changing rank names completley they will not be updated till after a server restart!
> 
> can you explained it? how to reproduce it? I use that fix for a long time and it solves my problem.

Explain what??? with this change rank names will no longer be updated in the game. So if a player changes his guild rank with name "a member" to "a gamer" it will stay "a member" till after a server restart. This was not the case before, then it was properly updated to "a gamer" wihtout any restarts and it should be fixed!

**Comment by Lyuzera** [comment]
> > > Bad fix. breaks changing rank names completley they will not be updated till after a server restart!
> > 
> > 
> > can you explained it? how to reproduce it? I use that fix for a long time and it solves my problem.
> 
> Explain what??? with this change rank names will no longer be updated in the game. So if a player changes his guild rank with name "a member" to "a gamer" it will stay "a member" till after a server restart. This was not the case before, then it was properly updated to "a gamer" wihtout any restarts and it should be fixed!

if it really happens, doesn't can merged. So we have to found where are the memory leak, because probably is what crashes the server.

**Comment by lollers420** [comment]
> > > > Bad fix. breaks changing rank names completley they will not be updated till after a server restart!
> > > 
> > > 
> > > can you explained it? how to reproduce it? I use that fix for a long time and it solves my problem.
> > 
> > 
> > Explain what??? with this change rank names will no longer be updated in the game. So if a player changes his guild rank with name "a member" to "a gamer" it will stay "a member" till after a server restart. This was not the case before, then it was properly updated to "a gamer" wihtout any restarts and it should be fixed!
> 
> if it really happens, doesn't can merged. So we have to found where are the memory leak, because probably is what crashes the server.

Yes ofcourse its beter than crash, but Still it removes 1 error and adds another one.

**Comment by ninjalulz** [comment]
> Bad fix. breaks changing rank names completley they will not be updated till after a server restart!

I don't see how it's connected since you can neither modify or delete a rank in-game.

**Comment by lollers420** [comment]
> Even if you alter the `name` in your database, it won't update either way because it checks whether a rank exists or not by looking up its ID.

But AACs change the name? Before in gesior when u changed rank name, it would also be update ingame (if a player relogged) now only after a server reboot. I think its same on znote right?? Same would be if u do it ingame thorugh some guild managment

To me it feels very wrong that we need a server reboot to change a player ranks now. And especially since this wasnt the case before this Fix.

**Comment by Xaekai** [comment]
I think that's the problem.

The game itself should be the only thing modifying the rank names, and should propagate those changes both to logged in players and the database.

If the webportal wants to surface controls for that, it should merely be a relay to an API surfaced by gameworld engine. Top down, full stop. Countless bugs are a result of not enforcing such an architecture.

**Comment by infister** [comment]
> I think that's the problem.
> 
> The game itself should be the only thing modifying the rank names, and should propagate those changes both to logged in players and the database.
> 
> If the webportal wants to surface controls for that, it should merely be a relay to an API surfaced by gameworld engine. Top down, full stop. Countless bugs are a result of not enforcing such an architecture.

There is missing proper API in tfs for that architecture, for now.

**Comment by LukSrT** [comment]
> > I think that's the problem.
> > The game itself should be the only thing modifying the rank names, and should propagate those changes both to logged in players and the database.
> > If the webportal wants to surface controls for that, it should merely be a relay to an API surfaced by gameworld engine. Top down, full stop. Countless bugs are a result of not enforcing such an architecture.
> 
> There is missing proper API in tfs for that architecture, for now.

I believe with this PR, it would already solve the problem of data manipulation on the site, no?

https://github.com/otland/forgottenserver/pull/2010/

**Comment by Xaekai** [comment]
> I believe with this PR, it would already solve the problem of data manipulation on the site, no?

I'm completely aware of that PR. That PR is the only reason I haven't already made a PR doing the same thing, though I'd use libuv instead of Beast. I don't like Beast at all.

**Pull request merged**
