### PR TITLE
Exp tracker

### PR DESCRIPTION
**Pull request by ArturKnopik**
Exp tracker feature
 config:
 analyserSendTrueRawExp - default false, give ability to send raw exp without multiplication by expStage
 
 analyserSendTrueRawExp false
image

analyserSendTrueRawExp true
image

### CODE REVIEW

**Review by EPuncker — CHANGES_REQUESTED** [review]
add the config.lua.dist entry and we good

**Review by EPuncker — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]
thank you

**Comment by ranisalt** [comment]
> analyserSendTrueRawExp - default false, give ability to send raw exp without multiplication by expStage

Why would someone want one option over the other?

**Comment by ramon-bernardo** [comment]
> > analyserSendTrueRawExp - default false, give ability to send raw exp without multiplication by expStage
> 
> Why would someone want one option over the other?

Alright, looks like custom config for server, far from TibiaRL

**Comment by dudantas** [comment]
It would be interesting to cite the original author: https://github.com/opentibiabr/canary/pull/232

**Comment by EPuncker** [comment]
> It would be interesting to cite the original author (@marcosvf132): [opentibiabr/canary#232](https://github.com/opentibiabr/canary/pull/232)

TRUE
https://github.com/opentibiabr/canary/pull/249
https://github.com/opentibiabr/canary/pull/250/files#diff-2b16a5ca17f2799203c4df2fdf8c16dbeceb88bb4aaf60513f647e704fbf4ddeR1018


hehehe

**Comment by ranisalt** [comment]
> It would be interesting to cite the original author (@marcosvf132): [opentibiabr/canary#232](https://github.com/opentibiabr/canary/pull/232)

The code has nothing special and there is no requirement to mention the author in the license. Please stop begging for it every time :pray:

**Comment by dudantas** [comment]
> The code has nothing special and there is no requirement to mention the author in the license. Please stop begging for it every time 🙏 the author is free to open a pull request to this repository if they want.

It's free to open and I'm free to comment. Am I not?
It is a common practice in open source to cite the author of the code, it is not mandatory, but it is something that strengthens ties and passes an air of respect. Not that I'm expecting that, as I've realized that this sort of thing has long since been abandoned by this community, regrettably.

**Comment by nekiro** [comment]
> > The code has nothing special and there is no requirement to mention the author in the license. Please stop begging for it every time 🙏 the author is free to open a pull request to this repository if they want.
> 
> It's free to open and I'm free to comment. Am I not? It is a common practice in open source to cite the author of the code, it is not mandatory, but it is something that strengthens ties and passes an air of respect. Not that I'm expecting that, as I've realized that this sort of thing has long since been abandoned by this community, regrettably.
> 
> And you still wonder why some people don't contribute more here?

I still wonder why are you checking every single commit, every single pull request of this repository, if it's so bad and so dead

**Comment by joseluis2g** [comment]
4 line codes of course need authors, we need to add jo3 as author because he was the first who exposed this code so.

**Pull request merged**
