### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by WibbenZ**
Replaced all
````
"/>
```

with
````
" />
```

### CODE REVIEW

**Comment by Crypton33** [comment]
It looks bad now :/ :-1:

**Comment by WibbenZ** [comment]
Mark has approved prev. commits that ive posted that have contained the exact same thing.
It is the way the code style should be, you can look in (I think) globalevents.xml and you will see that both ways are used.
We should stick to one.

**Comment by ranisalt** [comment]
This style is much better and almost every other XML/HTML file uses it.

**Comment by WibbenZ** [comment]
Yeah I go crazy when I see tags that are missing spaces, same with if statments that are missing "{ }"...

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
