### PR TITLE
GitHub Workflows Reworked

### PR DESCRIPTION
**Pull request by ericlancebrown**
This updates the old, not working GitHub workflows in place of new, working ones. Even generates more packages and tests builds on multiple OS's.

### CODE REVIEW

**Comment by ericlancebrown** [comment]
You are able to see the actions...in action... right here: https://github.com/ericlancebrown/forgottenserver/actions/runs/387532418

I also merged this pull into my master branch at: https://github.com/ericlancebrown/forgottenserver

Checks are passing.

**Comment by ericlancebrown** [comment]
Everything is passing and building properly. Check out my main branch here: 
[ericlancebrown/forgottenserver](https://github.com/ericlancebrown/forgottenserver)

You can see the tests individually here:
[Ubuntu](https://github.com/ericlancebrown/forgottenserver/actions/runs/387883096)
[MacOS](https://github.com/ericlancebrown/forgottenserver/actions/runs/387883097)
[Windows](https://github.com/ericlancebrown/forgottenserver/actions/runs/387883094)

**Comment by DSpeichert** [comment]
> This updates the old, not working GitHub workflows in place of new, working ones. Even generates more packages and tests builds on multiple OS's.

I see you've extended the Ubuntu build to use 3 versions instead of one: 16.04, 18.04 and 20.04.
However, I fail to see how current workflows are broken?

**Comment by ericlancebrown** [comment]
> > This updates the old, not working GitHub workflows in place of new, working ones. Even generates more packages and tests builds on multiple OS's.
> 
> I see you've extended the Ubuntu build to use 3 versions instead of one: 16.04, 18.04 and 20.04.
> However, I fail to see how current workflows are broken?
> 
> EDIT: I see something changed and the workflows fail on PRs.

I am referring to the outdated actions and syntax.

**Comment by ericlancebrown** [comment]
Seems that artifact generation is working properly on all of the builds now. I am attempting to fix the caching. It should be fine to merge.

**Pull request closed without merging**
