### PR TITLE
fix #3842: item attributes + trade bug

### LINKED ISSUE #3842: item attributes + trade bug
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Summary
Changing item attribute mid-trade doesn't cancel the trade. This can result in such situation:
- assume the server has some kind of upgrade system
- players trade the upgraded item
- player1 (the buyer) looks at the item and sees stats
- player2 (the seller) uses some kind of gem to remove the attributes from the traded item
- trade doesn't get cancelled
- both parties accept the trade
- player1 buys item with no attributes thinking that he bought upgraded one

### Steps to reproduce (include any configuration/script required to reproduce)
1. start trade as player 1
2. join trade as player 2
3. change traded item attribute
4. look at the item in trade window

### Expected behaviour
trade stops before step 4 happens

### Actual behaviour
trade continues

### PR DESCRIPTION
**Pull request by ArturKnopik**
fix #3842

### CODE REVIEW

**Comment by Zbizu** [comment]
personally I'd make `setAttribute` cancel the trade through `item->getHoldingPlayer` and (if player and trade) cancelling the trade

**Comment by ArturKnopik** [comment]
nice tip, i will try fix this that way, should we keep this fix to?

**Comment by Zbizu** [comment]
> nice tip, i will try fix this that way, should we keep this fix to?

I can't think of a scenario in which this would be necessary.
- Moving the item cancels the trade already.
- Removing the item cancels it too.
- Changing the item count/subType cancels the trade as well.

With setAttribute cancelling the trade, I can't think of any situation in which your fix would be triggered.

**Comment by ArturKnopik** [comment]
make trade using item A, use item B(example: upgrade stone) on item A, trade will be canceled and item A upgraded

**Comment by MillhioreBT** [comment]
I think it is not necessary to add this, in fact adding an attribute in the middle of a transaction is very normal.

**Comment by Zbizu** [comment]
That's what onTradeCompleted is for

**Pull request closed without merging**
