### PR TITLE
Configurable market fee

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
All offers (Buy and Sell) include a fee which ranges between 20gp and 100,000gp. This fee is 1% of the total price displayed on the offers and will be taken when the offer is created.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Zbizu** [comment]
Context for this change: https://tibia.fandom.com/wiki/Updates/12.20.9108

**Comment by omarcopires** [comment]
> Context for this change: https://tibia.fandom.com/wiki/Updates/12.20.9108

I looked for the version that changed, but I couldn't find it. Thank you!

**Comment by brunotonin** [comment]
Maybe it would be nice that these settings could be changed in config.lua.

**Comment by omarcopires** [comment]
> Maybe it would be nice that these settings could be changed in config.lua.

I don't see why, since the client itself is limited to 100,000gps.

**Pull request closed without merging**
