### PR TITLE
addTask(callback, ...) lua function

### PR DESCRIPTION
**Pull request by yamaken93**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

implements addTask lua c function so we can access the engine g_dispatcher.addTask function like addEvent and g_scheduler.addEvent.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Erza** [comment]
Can you describe an example scenario where having this functionality would be useful?

**Comment by yamaken93** [comment]
> Can you describe an example scenario where having this functionality would be useful?
If  you want the function(task) to be executed in the next frame(dispatcher cycle) asap without any delay.

**Comment by Erza** [comment]
> > Can you describe an example scenario where having this functionality would be useful?
> 
> If you want the function(task) to be executed in the next frame(dispatcher cycle) asap without any delay.

Sure, but in which example scenario would you want to do that?

**Comment by Kamenuvol** [comment]
addEvent with 1ms is not the same?

**Comment by MillhioreBT** [comment]
the dispatcher executes tasks in another thread is it correct?

**Comment by nekiro** [comment]
> the dispatcher executes tasks in another thread is it correct?

Yes, dispatcher and scheduler are using their own thread.

**Comment by yamaken93** [comment]
I think i may drop this pr and then change addEvent to use g_dispatcher.addTask when the delay is 0.

**Comment by yamaken93** [comment]
So we should add addTask or internally when someone call addEvent with 0 interval parameter it should add the task to dispatcher?

**Comment by DSpeichert** [comment]
I'd say the latter.

**Comment by yamaken93** [comment]
I still think we should add this addTask function. Why? Its problematic to change this ancient addEvent function parameters, since its has been a given for ages the minimum delay is 100 ms and its also problematic to under the hood make addEvent to add the task to dispatcher instead of scheduler because for the API sake the user script should be able to call addEvent and in the next line  call stopEvent and its not possible or easier to implement that dispatcher has cancellable tasks.
So the only two options for me is, add this addTask function or remove the 100 ms minimum delay from addEvent which will work basically as adding the task to the dispatcher when delay is 0 but will keep the stopEvent function working.

**Comment by DSpeichert** [comment]
Remove the minimum delay?

Wasn't there a reason this was implemented though?

**Comment by yamaken93** [comment]
> Remove the minimum delay?
> 
> Wasn't there a reason this was implemented though?

Probably a protection for performance reasons.

**Comment by yamaken93** [comment]
@nekiro @DanielChabrowski @MillhioreBT @ranisalt I'm willing to finally finish this. We should decide, add this api or remove the minimum delay from addEvent or add something like addEventEx whithout the minimum delay.

**Comment by MillhioreBT** [comment]
> @nekiro @DanielChabrowski @MillhioreBT @ranisalt I'm willing to finally finish this. We should decide, add this api or remove the minimum delay from addEvent or add something like addEventEx whithout the minimum delay.

I like `addTask` and am using it in some of my scripts. If `addEventEx` works all the same I have no complaints about it, I'll take it.

**Comment by yamaken93** [comment]
> > @nekiro @DanielChabrowski @MillhioreBT @ranisalt I'm willing to finally finish this. We should decide, add this api or remove the minimum delay from addEvent or add something like addEventEx whithout the minimum delay.
> 
> I like `addTask` and am using it in some of my scripts. If `addEventEx` works all the same, I have no complaints about it, I'll take it.

addEventEx would accept below 100 ms delay as parameter so it can work like addTask (with more overhead thanks to the timer system) if the delay is 0 and you will be able to cancel it if you call stopEvent before the task is added to the dispatcher.

**Pull request closed without merging**
