### PR TITLE
Use CMake presets and vcpkg manifest in workflows

### PR DESCRIPTION
**Pull request by ranisalt**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** fixes the current build error for Windows builds

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ArturKnopik** [comment]
WOW, it's working for windows :D

**Comment by ranisalt** [comment]
> WOW, it's working for windows :D

It's not doing anything 😂 I would be surprised if it didn't work

**Comment by ranisalt** [comment]
I removed `FindPugiXML.cmake` because it is shipped by default on Ubuntu, Arch Linux, vcpkg and a few more widely used distros, with a much better script for it. No point in keeping it, and I'll do the same with other modules that are unnecessary.

**Comment by ArturKnopik** [comment]
Will be nice to fix builds asap... windows build is broken again...

**Review by EPuncker — APPROVED** [review]

**Review by DSpeichert — APPROVED** [review]
Great!

**Pull request merged**
