### PR TITLE
Clean up LuaScriptInterface::luaSpellVocation

### PR DESCRIPTION
**Pull request by marksamman**
The code was quite confusing and from a quick glance there seemed to be a potential out of bounds access there:
```
if (vocList.size() > 0) {	
	if (vocList[1] == "true") {
```
It turns out that the first if-statement was just unnecessary. I've cleaned up the code and also replaced the `== "true"` check with booleanString().

### CODE REVIEW

**Comment by marksamman** [comment]
I noticed that the previous implementation would set `false` if there wasn't a semi-colon in the string, is that intentional? I feel like defaulting to true would make more sense, but I don't like the design of handling arguments in this way at all.

**Comment by raymondtfr** [comment]
> 
> 
> I noticed that the previous implementation would set `false` if there wasn't a semi-colon in the string, is that intentional? I feel like defaulting to true would make more sense, but I don't like the design of handling arguments in this way at all.

In recent tibia versions all runes now show vocation descriptions by default, so I'd say remove them altogether if we plan to update to newest protocols.

**Comment by marksamman** [comment]
I see, so that bool is for showing vocation in description. It's not obvious to anyone using this API.

**Comment by raymondtfr** [comment]
Yes, and it is only used for runes but that part of the code would run for any kind of spell if I'm not mistaken, even though "instant" does not make use of it.

**Pull request merged**
