### PR TITLE
Add NetworkMessage deletion in Player.sendHotkeyPreset function

### PR DESCRIPTION
**Pull request by omarcopires**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
Adds network message deletion in the Player.sendHotkeyPreset function for optimization.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ranisalt** [comment]
This is not needed, it will be deleted when it is garbage collected

**Comment by omarcopires** [comment]
> This is not needed, it will be deleted when it is garbage collected; if anything, this de-optimizes by deleting twice, the second being no-op

so it would be interesting to remove it from everyone else?

**Comment by ranisalt** [comment]
> so it would be interesting to remove it from everyone else?

Logic-wise, it makes no difference. For consistency, then yes, it should always be called or never be called.

**Comment by omarcopires** [comment]
> > so it would be interesting to remove it from everyone else?
> 
> 
> 
> Logic-wise, it makes no difference. For consistency, then yes, it should always be called or never be called.

I'll remove them all in a future pull request!

**Pull request closed without merging**
