### PR TITLE
Configurable stack size

### PR DESCRIPTION
**Pull request by ArturKnopik**
Issue: https://github.com/otland/forgottenserver/issues/4333

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Stack size can be set in game.h
static constexpr uint8_t ITEM_STACK_SIZE = 100;

image: stack size set to 250 (max 255)
image

### Note
It requires many tests to verify that each case is covered, a lot of magic 100 values

### CODE REVIEW

**Comment by ranisalt** [comment]
If it's meant to be configurable, what about adding to config.lua?

Otherwise, push the constant to Lua with `registerEnum` to avoid the function call

**Comment by ArturKnopik** [comment]
> If it's meant to be configurable, what about adding to config.lua?
> 
> Otherwise, push the constant to Lua with `registerEnum` to avoid the function call
Configuration I meant you can change one value and everything works, usually the owner won't want to change it so the value is set at compile time for optimization

**Comment by MillhioreBT** [comment]
> If it's meant to be configurable, what about adding to config.lua?
> 
> Otherwise, push the constant to Lua with `registerEnum` to avoid the function call

@ArturKnopik do what @ranisalt says, why make a call to lua when we can already have the constant in the global environment with registerEnum, the call `Game.getMaxStackSize` is unnecessary

**Comment by ranisalt** [comment]
That, keep in mind that `registerEnum` does not do what it says, it registers any constant with the same name, enum or not.

**Review by EPuncker — APPROVED** [review]

**Review by ranisalt — APPROVED** [review]

**Pull request merged**
