### PR TITLE
Revert "Add monsters walking back to spawn"

### PR DESCRIPTION
**Pull request by nekiro**
Reverts otland/forgottenserver#3604

It doesn't work properly.

### CODE REVIEW

**Review by MillhioreBT — APPROVED** [review]
These changes do not fully satisfy what we would expect from this mechanism.

**Comment by marmichalski** [comment]
so why not just fix it? 🙄

**Comment by MillhioreBT** [comment]
> so why not just fix it? 🙄

If you still keep the branch, do it, fix it and then push the changes, i suppose this revert is in case you don't decide to fix it.

**Comment by marmichalski** [comment]
This happens because of how poor A* is in TFS. I'll just chunk the path, so it does not have to check high count of nodes at once 🙄.

**Comment by lgrossi** [comment]
Would be nice to know the reason of the revert. That way people of other repositories can see it and maybe help to improve/fix. It's also an amazing way of keeping log for the future. 😁

**Comment by marmichalski** [comment]
> Would be nice to know the reason of the revert. That way people of other repositories can see it and maybe help to improve/fix. It's also an amazing way of keeping log for the future. 😁

https://github.com/otland/forgottenserver/pull/3604#issuecomment-907679749
https://github.com/otland/forgottenserver/pull/3610#issuecomment-907689912

PR with solution has been opened.

**Comment by lgrossi** [comment]
> > Would be nice to know the reason of the revert. That way people of other repositories can see it and maybe help to improve/fix. It's also an amazing way of keeping log for the future. 😁
> 
> [#3604 (comment)](https://github.com/otland/forgottenserver/pull/3604#issuecomment-907679749)
> [#3610 (comment)](https://github.com/otland/forgottenserver/pull/3610#issuecomment-907689912)
> 
> PR with solution has been opened.

Thanks for linking it, I think it's important to have some visibility in the revert PR.

**Comment by DSpeichert** [comment]
Reverting isn't necessary if the author is providing a fix quickly.

**Pull request closed without merging**
