### PR TITLE
Magicwall shouldn't disappear on forced step-in

### PR DESCRIPTION
**Pull request by Sundance**
Test done on a retro world

img
img
img
https://www.tibia.com/community/?subtopic=characters&name=Merlins+Pain

Code changes not tested

### CODE REVIEW

**Comment by EPuncker** [comment]
wild growth have same behavior?

**Comment by Sundance** [comment]
Unconfirmed, but those are also a type of magic wall so they most likely have the same behavior

**Comment by MillhioreBT** [comment]
I do not understand this PR very well, but I cannot reproduce the one of its GIF
GIF 10-05-2020 01-20-02 a  m
Neither with wild growth.

**Comment by Zbizu** [comment]
Imo it's okay. If somebody wants it to be kept, this can be done in lua and since it's one of bigger pvp things, it can be put in config.lua

**Comment by emil92b** [comment]
back in the days you would get stuck in the door ;p so make sense they fixed that

**Comment by EPuncker** [comment]
#3836

**Pull request closed without merging**
