### PR TITLE
Fix #1909

### LINKED ISSUE #1909: Missing item attribute for distance weapons?
### Actual behaviour

We have this bow.

```
<item id="2456" article="a" name="bow">
        <attribute key="weight" value="3100" />
        <attribute key="weaponType" value="distance" />
        <attribute key="slotType" value="two-handed" />
        <attribute key="ammoType" value="arrow" />
        <attribute key="skilldist" value="3" />
        <attribute key="range" value="6" />
    </item>
```

when we add "ammoType" then it doesnt show skill dist in description:
16:57 You see a bow (Range:6).
else after removing only this attribute it shows "distance fighting +3"
16:58 You see a bow (distance fighting +3).
### Expected behaviour

It should show item attribute everytime

### PR DESCRIPTION
**Pull request by thexamx**
I would like to request review.
This pull request should fix #1909

### CODE REVIEW

**Comment by ranisalt** [comment]
Please rebase your code against master as it seems it's incorporating changes from other commits.

**Comment by thexamx** [comment]
@ranisalt is it good now? I'm very noob in github commands ;d

**Comment by ranisalt** [comment]
Yes! LGTM.

**Comment by wgrriffel** [comment]
@thexamx github doesn't have 'commands', what has 'commands' are git, github is where you host git repositories

**Pull request merged**
