### PR TITLE
Add missing message to warn the player that he can't accept his own offer

### PR DESCRIPTION
**Pull request by Diego-OT**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Added missing message to warn the player that he can't accept his own offer

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by EPuncker** [comment]
2021-09-29 19_31_24-unknown png (1920×1080)

**Review by DSpeichert — CHANGES_REQUESTED** [review]
The commit message is ambiguous and PR template isn't filled.

**Comment by omarcopires** [comment]
I believe it is now okay to be added, except that the version check can be removed.

**Review by EPuncker — COMMENTED** [review]
yeah remove the version check and we okay

**Comment by Zbizu** [comment]
Been having that line (without version check) in my repo and reworked market three times already (so it got plenty of testing). Didn't had any problems with it. Remove version check and it's ready.

**Pull request merged**
