### PR TITLE
Format function parameters & arguments to break after parens

### PR DESCRIPTION
**Pull request by ranisalt**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 
A request from @EPuncker to improve readability on functions with long names, chopping parameters/arguments to the next line instead of using massive continuation indents.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by omarcopires** [comment]
@ranisalt could you also line up the comments on this pull request?

**Comment by omarcopires** [comment]
There are still a lot of places using spaces instead of tabs, but it's fine.

**Comment by ranisalt** [comment]
> There are still a lot of places using spaces instead of tabs, but it's fine.

For alignment, yes. Or are spaces being used for indentation? Can't find it

**Comment by omarcopires** [comment]
> > There are still a lot of places using spaces instead of tabs, but it's fine.
> 
> 
> 
> For alignment, yes. Or are spaces being used for indentation? Can't find it

You're right, it's just alignment.

**Review by EPuncker — APPROVED** [review]

**Pull request closed without merging**
