### PR TITLE
Move player task-delay

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Move player task-delay

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ramon-bernardo** [comment]
> I think it would be nicer if we had them at game.h as we have these:
> 
> https://github.com/otland/forgottenserver/blob/master/src/game.h#L66-L69

Its a good point, I like config because change interval without restarting.
Wait more opns.

**Comment by ranisalt** [comment]
> that would still mean they are hardcoded, so no point in pr xD

At least we avoid the magic numbers sprinkled around

**Comment by ranisalt** [comment]
Big finger on phone screen attacks again

**Comment by slawkens** [comment]
Looks good, making code more readable.

However, I would use the same convention as other variables do, that is: first the prefix, then the rest of variable name. Like INTERVAL_*

Like this:

MOVE_CREATURE_INTERVAL ->INTERVAL_MOVE_CREATURE
RANGE_MOVE_CREATURE_INTERVAL -> INTERVAL_RANGE_MOVE_CREATURE

Other than that, LGTM!

**Comment by ramon-bernardo** [comment]
I lost this branch, im not allowed to edit this. I will have to create another PR. :(

**Comment by ramon-bernardo** [comment]
> Looks good, making code more readable.
> 
> However, I would use the same convention as other variables do, that is: first the prefix, then the rest of variable name. Like INTERVAL_*
> 
> Like this:
> 
> MOVE_CREATURE_INTERVAL ->INTERVAL_MOVE_CREATURE RANGE_MOVE_CREATURE_INTERVAL -> INTERVAL_RANGE_MOVE_CREATURE
> 
> Other than that, LGTM!

I didn't find use of interval on front, but I like `interval_...`

**Comment by slawkens** [comment]
Ignore that, I was going too much into details 😉

**Pull request closed without merging**
