### PR TITLE
Implement loaded mounts limit

### LINKED ISSUE #3578: Client crash if you have more than 255 mounts
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Add a few custom mounts to your mounts.xml file until you have 254 or more
2. Open your server
3. Login your (GM) character and open outfit window

### Expected behaviour
no client crash

### Actual behaviour
client crash

I think we should have a limit check as we have for outfits [here](https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2807)

### PR DESCRIPTION
**Pull request by marmichalski**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Since mount id is declared as `uint8_t`, protocol check is not needed, since we can report invalid configuration during loading.

**Issues addressed:** Closes #3578.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by MillhioreBT** [comment]
The limit check should be done in the construction of the packet just as it is done with the outfits.

There is not much science with that, in any case if you think it is better to do it directly in the load, then do it for the outfits too.
Anyway, I would like to see someone else's opinion

**Comment by marmichalski** [comment]
> The limit check should be done in the construction of the packet just as it is done with the outfits.
> 
> There is not much science with that, in any case if you think it is better to do it directly in the load, then do it for the outfits too.
> Anyway, I would like to see someone else's opinion

Why would it? Mounts, for some reason, have `id` that's an uint8_t. If you have more than 255, it will just overflow and you will have duplicated mounts with the same id. It's limited """by design""" 😎

**Review by ranisalt — DISMISSED** [review]

**Review by Erza — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]
Shouldn't we warn the user that the max id is 255 too, to prevent future confusion? (if and when we get to that point) 😄

**Comment by marmichalski** [comment]
> Shouldn't we warn the user that the max id is 255 too, to prevent future confusion? (if and when we get to that point) 😄

id 255 is allowed as it fits in u8. 0 also fits, but to keep mounts size limited to 254, it's treated as invalid

**Comment by EPuncker** [comment]
> Oh, I think I've understood now what you want - to display the allowed range in notice?

exactly

**Review by DSpeichert — APPROVED** [review]

**Comment by marmichalski** [comment]
```
[Notice - Mounts::loadFromXml] Mount id "0" is not within 1 and 255 range
[Notice - Mounts::loadFromXml] Mount id "256" is not within 1 and 255 range
```

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
