### PR TITLE
Fix string view in game world auth

### PR DESCRIPTION
**Pull request by ArturKnopik**
Fix string_view pointing to non-existent string
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

**Issues addressed:** 
https://github.com/otland/forgottenserver/issues/4359

### CODE REVIEW

**Comment by ranisalt** [comment]
No need for most of these changes; just changing the return type from `string_view` to `string` in `gameworldAuthentication` and `move`ing it into the lambda is enough.

**Comment by ArturKnopik** [comment]
i tried it your way but i failed, i don't know why but i got an empty string after escaping gameworldAuthentication method(int onRecvFirstMessage method), before adding the string to the pair the string had a valid value

**Comment by ArturKnopik** [comment]
updated, issue with @ranisalt approach was std::tie and characterName variable, characterName was string_view not std::string

**Comment by reyaleman** [comment]
> updated, issue with @ranisalt approach was std::tie and characterName variable, characterName was string_view not std::string

I just changed std::tie to std::pair on protocolgame.cpp (L472) and it worked 😕 


```cpp
std::tie(accountId, characterName) = ...
```

```cpp
std::pair(accountId, characterName) = ...
```

**Comment by ranisalt** [comment]
I would try with

```
auto [accountId, name] = gameworldAuthentication(...);
```

then `move` `name` into the lambda if necessary.

> `std::pair(accountId, characterName) = ...`

Did it _compile_ or did it _work_? I think that's creating a new pair with `accountId` (which is zero) and `characterName` (the unnormalized name) and then assigning it, but this shouldn't override the previous values, and you'll get the `accountId == 0` and the unmodified `characterName` instead.

**Comment by reyaleman** [comment]
> > `std::pair(accountId, characterName) = ...`
> 
> Did it _compile_ or did it _work_? I think that's creating a new pair with `accountId` (which is zero) and `characterName` (the unnormalized name) and then assigning it, but this shouldn't override the previous values, and you'll get the `accountId == 0` and the unmodified `characterName` instead.

you're right... it doesn't override previous values for `accountId` and `characterName`.

Ignore my previous comment 👍

**Comment by ranisalt** [comment]
To be honest, reading the character name would just prevent a hopelessly broken client from not being able to log in, because by default the Tibia client and OTClient send the name exactly as the login server responds.

We can skip that code and return solely the account ID, the code gets much simpler. Along these lines:

```cpp
	uint32_t accountId = IOLoginData::gameworldAuthentication(accountName, password, characterName, token, tokenTime);
	if (accountId == 0) {
		disconnectClient("Account name or password is not correct.");
		return;
	}

	g_dispatcher.addTask([=, thisPtr = getThis(), characterName = std::move(characterName)]() {
		thisPtr->login(characterName, accountId, operatingSystem);
	});
```

Alternatively, we can instead return the character ID and not the name, and then `login` takes it, since the very first thing it does is `getPlayerByName`.

What do you think?

**Comment by ArturKnopik** [comment]
characterName is string_view, string_view is moveable? I don't think so... but i can be wrong

**Comment by ranisalt** [comment]
> characterName is string_view, string_view is moveable? I don't think so... but i can be wrong

Right, it is not, so keep `std::string{characterName}` to copy it

**Pull request closed without merging**
