### PR TITLE
Use item id instead of name in monster loot

### PR DESCRIPTION
**Pull request by marmichalski**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** #3528 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by marmichalski** [comment]
If you prefer, I can keep (& add missing) comments with item name 🤔

**Comment by Zbizu** [comment]
Why did you remove the comments on item ids? It tells exactly what the user is editing and makes the whole thing readable.

If you're using a script to convert that, call ItemType(itemId):getName() on each item id.

**Comment by marmichalski** [comment]
> Why did you remove the comments on item ids? It tells exactly what the user is editing and makes the whole thing readable.
> 

https://github.com/otland/forgottenserver/pull/3538#issuecomment-891816241

> If you're using a script to convert that, call ItemType(itemId):getName() on each item id to generate comments again.

Do you just type things for the heck of typing?

**Comment by soul4soul** [comment]
I'd rather have the item names and run the risk of duplicate item name. At a minimum the item names have to be kept as comments to make editing the files manageable.

**Comment by marmichalski** [comment]
Will this be stalled until merge conflicts arise?

**Comment by Erza** [comment]
To help with your decision: id's should be used because of name duplication - you can't reliably use item names as loot because multiple items can have the same name and the engine will pick the first id that it finds.

Now when you look at https://github.com/otland/forgottenserver/pull/3540, non-unique item names use id's instead, but for one, that's inconsistent, and for two, nobody wants to maintain maintain that. It's not future-proof, if item names ever get corrected and one ends up with a duplicate name

Just use id's across the board and merge this PR.

**Comment by marmichalski** [comment]
@EPuncker beep boop

**Comment by Erza** [comment]
smh

**Comment by EPuncker** [comment]
@DSpeichert this can be merged, I can't approve it because my browser lag with so many files

**Comment by DSpeichert** [comment]
I think someone suggested keeping both `id` and `name` parameter, instead of moving the name out to a comment. It's easier to write and it's also more portable. IIRC, the engine will prefer `id`, if exists, before reverting to name.

**Comment by marmichalski** [comment]
kthxbye

**Pull request closed without merging**
