### PR TITLE
Rename casting functions from getX to asX

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Rename casting functions from getX to asX

**Issues addressed:** 
#4068

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ArturKnopik** [comment]
do we really need this change, what bad is on getX?

**Comment by ramon-bernardo** [comment]
> do we really need this change, what bad is on getX?

See linked issue, have a good explan

**Comment by MillhioreBT** [comment]
While there are methods that fit the name asX well, in some cases asX seems to make no sense.
for example if I want to obtain a creature of a thing, the logical thing would be to get creature

besides that what would happen with the compatibility of the many scripts that use getx in the forum

**Comment by Zbizu** [comment]
@ramon-bernardo I literally never heard about anyone having any confusion over this. It's been like that for 7 years. Changing this now will cause more confusion than it's supposed to avoid.

@MillhioreBT we keep deprecated functions working through compat.lua

**Comment by luanluciano93** [comment]
Really unnecessary.

**Pull request closed without merging**
