### PR TITLE
Use a variable as a reference of database instance

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### (Reverted - Changes Proposed)
- Use ref variable with database instance.
- Code more clean.

### Changes Proposed
- Use a variable as a reference of db instance instead of 2?

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by nekiro** [comment]
Why? If that variable isn't reused then what's the point of defining it?

**Comment by kygov** [comment]
It could be "more clean" with changes that Saiyans did, instead calling Database::getInstance just g_database.X.

https://github.com/andersonfaaria/optimized_forgottenserver/blob/master/src/ban.cpp#L100

**Comment by ranisalt** [comment]
It would be more clean without the globals. Just pass the reference around

**Comment by ramon-bernardo** [comment]
`g_database`, `Database::getInstance()` or `Database& db = Database::getInstance()`?

**Comment by MillhioreBT** [comment]
it's not necessary at all, and it doesn't look cleaner either, I just see more unnecessary instructions
`Create a reference variable`, `Destroy the reference when the function returns` XD

**Review by DSpeichert — COMMENTED** [review]
I don't think it's worth making a change.

**Comment by ramon-bernardo** [comment]
Alright, Thanks!

**Pull request closed without merging**
