### PR TITLE
Updating Spawns.

### PR DESCRIPTION
**Pull request by slavidodo**
This update was implemented in 10.76 update.
Image

### CODE REVIEW

**Comment by WibbenZ** [comment]
Sad thing about is that some monsters still can be blocked, 
Found this on otland, might be diffrent now, but just a week ago I could block a monster can't remember what it was tho..
http://1.ii.gl/GzdzEGBbt.png

**Comment by slavidodo** [comment]
Well, this is good point of this spawn system which will work overall monsters.

**Comment by mattyx14** [comment]
:D nice ^^

**Comment by ranisalt** [comment]
Please don't implement multiple things on a single PR, instead do each one on a different branch and PR individually.

**Comment by slavidodo** [comment]
Okay.

**Comment by slavidodo** [comment]
@ranisalt I am not so familer with git, how to revert commit?

**Comment by ranisalt** [comment]
I would use `git reset HEAD~2` to revert 2 commits

**Comment by WibbenZ** [comment]
Just saying that this isen't the best way.
Ex the spawns in the poi tp room are blockable, to make it easier..
This would make it alot harder to do a poi service or a poi boss check.

**Comment by slavidodo** [comment]
I will close the pull request and rework it with monster flag.

**Pull request closed without merging**
