### PR TITLE
Update outfits gender and boolean values

### PR DESCRIPTION
**Pull request by WibbenZ**
Swap "type" for "sex".
Use yes/no insted of 1/0 for boolean values.
Use male/female insted of 1/0 for sex attributes.

### CODE REVIEW

**Comment by EvulMastah** [comment]
Why not true/false for boolean values? You changed them anyway.
Why not keeping backward compatibility leaving type?

**Comment by WibbenZ** [comment]
Does not really matter, we used yes/no in the config file and it seems abit more understandable when it comes to a string value(as in XML).

Type can be confusing to understand, while sex tells you right away what it means.
This is not a major change for others if they decide to upgrade, what could it take 5-15 sec?

type="0" => sex="male"
type="1" => sex="female"

If a person can't use the find and replace function with the code above then they will have alot more problems.
IMO the removeItem etc (move from items to weapons) was a bigger thing then this.

**Comment by ranisalt** [comment]
`sed -i -e 's/type="0"/sex="female"/g' -i -e 's/type="1"/sex="male"/g' -i -e 's/"0"/"no"/g' -i -e 's/"1"/"yes"/g' path/to/outfits.xml` and you're done.

**Comment by marksamman** [comment]
This change is not worth breaking backwards compatibility.

**Comment by WibbenZ** [comment]
So should I change it back to type, use 1/0 for male/female?

Still if you ask me we should really stop with keeping compatibility, those who want to move to 1.x have already done it and most of them have adapted the new script interface.
All this does is limit us to what we can do really.

Same with the weapons / items change you did, was that a thing worth doing?
Did it really optimize it to the point that users will wanna change the custom items they might have etc.
As I said, if users want to move to 1.x they have already done it and the most used server right now is probbly ORTS and they keep the datapack updated with TFS.

**Comment by kornholi** [comment]
We break compatibility in cases where it can be justified. I don’t see how this “limits us to what we can do"

**Comment by WibbenZ** [comment]
How does it not limit us to what we can do?
Like in this case, how do you justify calling type when you are returning a sex id?
It would be alot simpler to just call it sex or gender and then return male / female.

**Comment by ranisalt** [comment]
How come this change is not worth it, but modifying the XML flags is?

**Comment by djarek** [comment]
Perhaps we could try doing a gradual change, for example we could print out a big scary deprecation warning if the old syntax is used.

**Comment by WibbenZ** [comment]
Implement what I did and start it with type and 1/0, you will get alot of errors haha, so ye.
But I guess the problem is that they are afraid people won't continue with 1.x while I think it's the other way around.
I still today don't get why we keep things like doPlayerAddItem when we can force users to use Player:addItem etc.
There are alot of functions like that, just go to luascript.cpp and serach for "lua_register"

**Comment by ranisalt** [comment]
I think a major change in XML structure should be scheduled for a 2.0 version, with a big red NO BACKWARDS COMPATIBILITY warning.

**Comment by WibbenZ** [comment]
Will probbly take a long while till we are at 2.0 xD
But maybe 1.3 / 1.4.
Atleast change out names like this that makes no sence at all without looking in the source code.

**Comment by WibbenZ** [comment]
So nothing more on this Mark?
What is the point of even keeping backwards compat?
We can insted try to make it better, ex. With the code style.

**Comment by ranisalt** [comment]
I don't think it was closed with compatibility in mind, else it wouldn't be a milestone to [change the flag representation](https://github.com/otland/forgottenserver/issues/1394).

**Comment by marksamman** [comment]
I disagree about it being better, it's a step towards restricting the gender system to be binary and hard coding gender names. It's slower. It doesn't maintain backwards compatibility (and even if it did, it would just make the code messy).

**Comment by djarek** [comment]
To be honest the name should probably be changed from type to sex(a little more intuitive ;)).

**Comment by WibbenZ** [comment]
Same with using integers as bools if you ask me.
The only changes except sex was femake/male since I hate having to check if 0 or 1 is the male or female.

**Pull request closed without merging**
