### PR TITLE
Rename cannotpushallcreatures to canpushallcreatures

### PR DESCRIPTION
**Pull request by nekiro**
Current PlayerFlag_CanPushAllCreatures groups.xml string is misleading, it should be the opposite way.

### CODE REVIEW

**Comment by EPuncker** [comment]
missing groups.xml file change

**Comment by MillhioreBT** [comment]
Changes are also required here
https://github.com/otland/forgottenserver/blob/670b0ca111cbc72440b60e43c627716de88aee9f/data/XML/groups.xml#L27
https://github.com/otland/forgottenserver/blob/670b0ca111cbc72440b60e43c627716de88aee9f/data/XML/groups.xml#L68

**Comment by DSpeichert** [comment]
Is this in use? If so, it would be backwards incompatible.

**Comment by nekiro** [comment]
> Is this in use? If so, it would be backwards incompatible.

Just the string is renamed not the actual flag, this bug appeared when I added new groups parsing

**Review by EPuncker — APPROVED** [review]

**Review by MillhioreBT — APPROVED** [review]

**Comment by DSpeichert** [comment]
I see the flag being renamed in this PR, is it reverting to the name that was used before?

**Comment by MillhioreBT** [comment]
> I see the flag being renamed in this PR, is it reverting to the name that was used before?

What happens is that it is a name that does not mean what the flag actually does:
image
the flag is understood as a flag that allows you to move all creatures, while its name in xml, implies that it is a flag that does not allow you to move all creatures

**Comment by nekiro** [comment]
> I see the flag being renamed in this PR, is it reverting to the name that was used before?

No name was used before as I said before this was added by me and I mispelled this flag name.

**Comment by DSpeichert** [comment]
> No name was used before as I said, this was added by me and I mispelled this flag name.

Okay, so here's what I was asking: since i can see you are changing the line in XML, it existed before. Looking through git blame, I found commit 7f8002e14 (#2546) which is probably where you're saying you added it. However, it was 2 years ago. So for two years, we had this other, confusing name for the flag. Is that right?

If so, that does open up the discussion whether anyone over 2 years got used to using that name you're now changing.

**Comment by nekiro** [comment]
> > No name was used before as I said, this was added by me and I mispelled this flag name.
> 
> Okay, so here's what I was asking: since i can see you are changing the line in XML, it existed before. Looking through git blame, I found commit [7f8002e](https://github.com/otland/forgottenserver/commit/7f8002e1479b75e6be1349cec80089e192118072) (#2546) which is probably where you're saying you added it. However, it was 2 years ago. So for two years, we had this other, confusing name for the flag. Is that right?
> 
> If so, that does open up the discussion whether anyone over 2 years got used to using that name you're now changing.

Wow, it was 2 years ago. I didn't realize that. How weird I thought it was recent change wtf...

**Comment by EPuncker** [comment]
I see no reason for all this hassle, I'm in favor of this PR, its not like people wouldn't know how to fix this on their end

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
