### PR TITLE
Summons inherit master flags

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Summons inherit master flags (canPushCreatures, canPushItems).

#3427 @emil92b

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
do they? 🤔 I need to think of a scenario so I can test it in rl tibia (free account 😛 )

**Comment by soul4soul** [comment]
I don't remember this behavior from cipbia.

> 
> 
> do they? 🤔 I need to think of a scenario so I can test it in rl tibia (free account 😛 )
Giant spiders are a good FACC test creature

**Comment by emil92b** [comment]
beholder and crates, skeles inherit push mechanic

**Comment by soul4soul** [comment]
> 
> 
> beholder and crates, skeles inherit push mechanic

Interesting, I just tested a beholder + skelly summons. 
beholder: can push boxes, can't be pushed
regular skeleton: can't push boxes, can be pushed
beholder skeleton summon: CAN push boxes, can be pushed.

So in this test only the ability to push boxes was inherited. There must be more to it or only the ability to push boxes is inherited.  Plus, I looted a terra rod. I never got that lucky when I actually played daily.

idk how to record videos on cipbia anymore of I would of made a video.

**Comment by EvilHero90** [comment]
> idk how to record videos on cipbia anymore of I would of made a video.
use OBS, sounds funny but works for recording pretty well

**Review by EPuncker — APPROVED** [review]
yeah actually confirmed with both bonelord and giant spiders, their summons do inherit their push item flags, altought I don't think they inherit the push creature

**Review by EvilHero90 — CHANGES_REQUESTED** [review]
This looks to me that it'll change the status to all monsters of that monster type and not only for the summons, if someone tried and confirmed that it's working corectly I'll approve it

**Review by EPuncker — CHANGES_REQUESTED** [review]
actually need to check if summons inherit monster push flag as well

**Review by nekiro — CHANGES_REQUESTED** [review]
Your current change breaks canpushitems for every single monster based off the summon monster type.
You should check if monster has master and then get master canPushItems state for the summon.

**Comment by nekiro** [comment]
Changes are still broken

**Comment by ramon-bernardo** [comment]
> Changes are still broken

Yes, check has to be from summon and not from master. 🤔

**Comment by ramon-bernardo** [comment]
I believe I went wrong way.
`summon->isSummon()` necessary? 1 line above, master is added.

**Comment by emil92b** [comment]
what about push monsters tho

**Pull request closed without merging**
