### PR TITLE
Monsters cleanup

### PR DESCRIPTION
**Pull request by raymondtfr**
A small cleanup in monster files.

I'm having some troubles with renaming some files with uppercase letters to lowercase, so I'll leave this for another PR.

### CODE REVIEW

**Comment by ranisalt** [comment]
I personally prefer `<immunity drunk="yes">` if available.

**Comment by raymondtfr** [comment]
There's this way ``<immunity name="drunk"/>`` besides that.

But all those changes I made reflect the way most monster files are configured.

There are some other names too that don't fit, such as ``drunk`` where it should be ``drunkenness``, etc.

I accidentally pushed two different kind of changes into the same commit (about removing spaces), I think I'm gonna revert them and redo each one in a different commit to make things clearer to analyze.

**Comment by ranisalt** [comment]
Whatever, commits will be squashed together anyway.

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
