### PR TITLE
Feature: disable specific creature script in combat object

### PR DESCRIPTION
**Pull request by ArturKnopik**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Add possibility to disable specific creature script in combat object, this give possibility to execute combat object in creaturescript without risko of stuck in infinity loop
Can be useful when implementing charms

### Example
```lua
local test1_onHealthChange = CreatureEvent("test1_onHealthChange")
function test1_onHealthChange.onHealthChange(target, attacker, primaryDamage, primaryType, secondaryDamage,
    secondaryType, origin)
    print("test1_onHealthChange called")
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end
test1_onHealthChange:register()

local test1_onManaChange = CreatureEvent("test1_onManaChange")
function test1_onManaChange.onManaChange(target, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType,
    origin)
    print("test1_onManaChange called")
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end
test1_onManaChange:register()

local test2_onHealthChange = CreatureEvent("test2_onHealthChange")
function test2_onHealthChange.onHealthChange(target, attacker, primaryDamage, primaryType, secondaryDamage,
    secondaryType, origin)
    print("test2_onHealthChange called")
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end
test2_onHealthChange:register()

local test2_onManaChange = CreatureEvent("test2_onManaChange")
function test2_onManaChange.onManaChange(target, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType,
    origin)
    print("test2_onManaChange called")
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end
test2_onManaChange:register()

local test_onLogin = CreatureEvent("test_onLogin")
function test_onLogin.onLogin(player)
    player:registerEvent("test1_onHealthChange")
    player:registerEvent("test1_onManaChange")
    player:registerEvent("test2_onHealthChange")
    player:registerEvent("test2_onManaChange")
    return true
end
test_onLogin:register()

local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_ENERGYAREA)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_ENERGY)
combat:setParameter(COMBAT_PARAM_DISABLECREATUREEVENT, "test1_onHealthChange")
combat:setParameter(COMBAT_PARAM_DISABLECREATUREEVENT, "test1_onManaChange")

function onGetFormulaValues(player, level, maglevel)
	local min = 100
	local max = 100
	return -min, -max
end

combat:setCallback(CALLBACK_PARAM_LEVELMAGICVALUE, "onGetFormulaValues")

local rune = Spell("rune")

function rune.onCastSpell(creature, var, isHotkey)
	return combat:execute(creature, var)
end

rune:group("attack")
rune:id(8)
rune:name("Heavy Magic Missile")
rune:vocation("sorcerer;true", "master sorcerer;true,","druid;true", "elder druid;true", "paladin;true", "royal paladin;true", "knight;true", "elite knight;true")
rune:runeId(2280)
rune:allowFarUse(true)
rune:charges(10)
rune:level(25)
rune:magicLevel(3)
rune:cooldown(2 * 1000)
rune:groupCooldown(2 * 1000)
rune:needTarget(true)
rune:isBlocking(true)
rune:register()
```
console output: 
image

Practical example
```lua
local charmCombat = Combat()
charmCombat:setParameter(COMBAT_PARAM_DISABLEDCREATUREEVENT, "CharmMonsterDamageTrigger")
charmCombat:setParameter(COMBAT_PARAM_DISABLEDCREATUREEVENT, "CharmPlayerDamageReceived")

local charmDamage = CreatureEvent("CharmMonsterDamageTrigger")
function charmDamage.onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType,
    origin)
    if not attacker or not creature then
        return primaryDamage, primaryType, secondaryDamage, secondaryType
    end

    if not (creature:isMonster() and attacker:isPlayer()) then
        return primaryDamage, primaryType, secondaryDamage, secondaryType
    end

    local bestiaryInfo = creature:getType():getBestiaryInfo()
    if not bestiaryInfo then
        return primaryDamage, primaryType, secondaryDamage, secondaryType
    end

    if bestiaryInfo.raceId == 0 then
        return primaryDamage, primaryType, secondaryDamage, secondaryType
    end

    local charm = nil
    for index, value in ipairs(combatCharms) do
        if attacker:getCharmMonster(CHARMS_DATA[value].id) == bestiaryInfo.raceId then
            charm = CHARMS_DATA[value]
            break
        end
    end

    if not charm then
        return primaryDamage, primaryType, secondaryDamage, secondaryType
    end
    if math.random(0, 100) <= charm.chance then
        local damage = math.min(attacker:getLevel(), creature:getMaxHealth() / 100 * charm.percentage)
        charmCombat:setParameter(COMBAT_PARAM_TYPE, charm.damageType)
        charmCombat:setParameter(COMBAT_PARAM_EFFECT, charm.effect)
        charmCombat:setFormula(COMBAT_FORMULA_DAMAGE, -damage, 0, -damage, 0)
        charmCombat:execute(attacker, Variant(creature:getId())) -- without this changes this line can generate infinity loop
    -- combat generated by creature script will trigger another creature script that trigger combat that trigger creature script etc...  
    end
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end
charmDamage:register()
```

### CODE REVIEW

**Comment by MillhioreBT** [comment]
Although through lua we can emulate this behavior for specific spells or any script in general.
what is true is that this PR makes it a little easier for everyone

However, I don't know how useful it is in general or if it's worth adding.

**Comment by ArturKnopik** [comment]
> Although through lua we can emulate this behavior for specific spells or any script in general. what is true is that this PR makes it a little easier for everyone
> 
> However, I don't know how useful it is in general or if it's worth adding.

can you show me example where you execute combat object from creature event(onHeal/onMana change) and you solve infinity loop issue?

**Comment by MillhioreBT** [comment]
> > Although through lua we can emulate this behavior for specific spells or any script in general. what is true is that this PR makes it a little easier for everyone
> > However, I don't know how useful it is in general or if it's worth adding.
> 
> can you show me example where you execute combat object from creature event(onHeal/onMana change) and you solve infinity loop issue?

Sure...
```lua
local CONTROL = false

local charmCombat = Combat()

local charmDamage = CreatureEvent("CharmMonsterDamageTrigger")

function charmDamage.onHealthChange(creature, attacker, primaryDamage,
                                    primaryType, secondaryDamage, secondaryType,
                                    origin)
	if CONTROL then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end

	if not attacker or not creature then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end

	if not (creature:isMonster() and attacker:isPlayer()) then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end

	local bestiaryInfo = creature:getType():getBestiaryInfo()
	if not bestiaryInfo then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end

	if bestiaryInfo.raceId == 0 then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end

	local charm = nil
	for index, value in ipairs(combatCharms) do
		if attacker:getCharmMonster(CHARMS_DATA[value].id) == bestiaryInfo.raceId then
			charm = CHARMS_DATA[value]
			break
		end
	end

	if not charm then
		return primaryDamage, primaryType, secondaryDamage, secondaryType
	end
	if math.random(0, 100) <= charm.chance then
		local damage = math.min(attacker:getLevel(),
		                        creature:getMaxHealth() / 100 * charm.percentage)
		charmCombat:setParameter(COMBAT_PARAM_TYPE, charm.damageType)
		charmCombat:setParameter(COMBAT_PARAM_EFFECT, charm.effect)
		charmCombat:setFormula(COMBAT_FORMULA_DAMAGE, -damage, 0, -damage, 0)
		CONTROL = true
		charmCombat:execute(attacker, Variant(creature:getId()))
		CONTROL = false
	end
	return primaryDamage, primaryType, secondaryDamage, secondaryType
end

charmDamage:register()
```

This would be a basic example, but it can be done in many more ways.

**Comment by ArturKnopik** [comment]
it's look tricky :d

**Comment by MillhioreBT** [comment]
> it's look tricky :d

It's not something new or complicated, in fact TFS has used this trick before
https://github.com/otland/forgottenserver/blob/9dc86d0c0e156417edf725b9a68c89d182511e3b/data/lib/core/player.lua#L123-L130

Can you estimate how many spells might need this change?
maybe 1 or 2?

**Pull request closed without merging**
