### PR TITLE
prevent lag in /i talkaction

### PR DESCRIPTION
**Pull request by Zbizu**
workaround for #3222

this is NOT a bugfix to the issue itself

### CODE REVIEW

**Comment by MillhioreBT** [comment]
I have been testing what you say and it is not true, my server does not cause any delay, if you can give us some other way to reproduce the performance problem it would be great, to help you confirm the problem.

It goes without saying that I tested it with my TFS fork without any changes, totally vanilla as is the master branch

**Comment by Zbizu** [comment]
@MillhioreBT see #3222 

I downloaded the zip of master branch now and compiled it again without any changes (64 bit release same setup as in description) and the freeze still occurs.

**Comment by EPuncker** [comment]
I tested here as well and there is no lag/freeze at all, maybe there is another variable necessary to reproduce this

**Comment by Zbizu** [comment]
@EPuncker I tested it on appveyor build and it also froze

**Comment by EPuncker** [comment]
> @EPuncker I tested it on appveyor build now and it also froze

do you perhaps, have access to a second pc where you could test this?

**Comment by Zbizu** [comment]
ok for some reason it works fine on my laptop so I have no idea what is causing it on my pc

**Pull request closed without merging**
