### PR TITLE
fix #4077 (monster id 0 in onSpawn event)

### LINKED ISSUE #4077: monster:onSpawn creature id is 0
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce
1. create a script:
```
	local ec = EventCallback
	ec.onSpawn = function(self, position, startup, artificial)
		print(self:getId())
		return true
	end
	ec:register()
```
2, start the server

### Expected behaviour
output: monster id

### Actual behaviour
output: 0
note: monster methods work normally, but this could break a script that would rely on monster id

### PR DESCRIPTION
**Pull request by Zbizu**
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
set monster ID before calling the script
**Issues addressed:** #4077

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by nekiro** [comment]
This event is called too early, with that fix you are setting id twice, It will work cause setId has id == 0 check, but anyway that's workaround and is probably problematic

**Comment by conde2** [comment]
In my opinion we should only call onSpawn after it successfully spawn.

**Comment by conde2** [comment]
Can't we just call setId on each creature class consctructor?

**Comment by Zbizu** [comment]
> I believe it sets the id after creature is placed to avoid waste of ids for unplaced creatures, this is though very rare, when creature is created but not placed, so your suggestion might be actually quite good, unless I missed something

the id pool is big enough to run the server for several months without restarting, even high exp ue spam
will never get exhausted if you restart server daily

**Comment by Codinablack** [comment]
Would it not be best, for the end user, if "onSpawn" was a void, with the whole created monster passed after creation, and then there be another event "onPrepareSpawn" which could have more information such as,
 onPrepareSpawn(monsterType, spawnId, spawnBlock, centerPos, radius, #aliveInSpawn, startup)

**Review by ramon-bernardo — APPROVED** [review]

**Comment by ramon-bernardo** [comment]
Simplest solution. Good!

> @Zbizu 
> the id pool is big enough to run the server for several months without restarting, even on high exp ue spam server the pool will never get exhausted if you restart server daily

I agree.

Any reason not to merge?

**Comment by Zbizu** [comment]
@ramon-bernardo 
> Any reason not to merge?

Divided opinions on the solution.

I won't be working on this pr anymore so if you guys are not interested in merging it in its current state, you can close it.

**Comment by ranisalt** [comment]
If no one is willing to dedicate time, I'd rather have the bug fixed.

**Pull request closed without merging**
