### PR TITLE
bestiary - God char display all info

### PR DESCRIPTION
**Pull request by ArturKnopik**
### Pull Request Prelude

- [X] I have followed [proper The Forgotten Server code styling][code].
- [X] I have read and understood the [contribution guidelines][cont] before making this PR.
- [X] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Allow God character do display all bestiary information

### CODE REVIEW

**Comment by omarcopires** [comment]
It does not work for me

**Comment by ArturKnopik** [comment]
Are you synced with master?

**Comment by ranisalt** [comment]
I don't think it belongs here, post it on the forum and the server owner that is interested can add the code. Let's keep to the fundamentals.

**Comment by omarcopires** [comment]
> Are you synced with master?

yes :/

**Comment by ArturKnopik** [comment]
> > Are you synced with master?
> 
> yes :/

ok, i know what is wrong i forget add some changes in bestiary_classes.lua and bestiary_monster_types.lua

**Pull request closed without merging**
