### PR TITLE
Fix spells addevent crash after reload

### PR DESCRIPTION
**Pull request by MillhioreBT**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** #3025

The author of these changes is: @SaiyansKing all credits to this person.

### CODE REVIEW

**Comment by nekiro** [comment]
It's possible to avoid combat crashes just by using the table instead of the object itself, like this:
Combat.execute(combat, creature, variant)

**Comment by MillhioreBT** [comment]
> It's possible to avoid combat crashes just by using the table instead of the object itself, like this:
> Combat.execute(combat, creature, variant)

I have proven what you say, and if you are right about one thing, it does not produce the crash!
however it does not have the expected behavior, the combat is not supposed to be lost, much less to execute a different combat!

The following code has a strange behavior when reload spells before executions.
```lua
addEvent(Combat.execute, 5000, combat2, creature:getId(), variant)
addEvent(Combat.execute, 7000, combat, creature:getId(), variant)
```
when I say strange, I mean that any combat is executed and not the combat that it really is.

**Important: all this happens with master sources!**

**Comment by MillhioreBT** [comment]
These changes allow this:
https://user-images.githubusercontent.com/28090948/126395353-b02dec76-016d-49fe-9620-72060b1f543a.mp4

For now there are some merge conflicts, but I can do another PR if necessary, I just need to know if this really they interests

**Comment by MillhioreBT** [comment]
Closed, because #3503 seems like a better option, but it has yet to be decided

**Pull request closed without merging**
