### PR TITLE
Use table in changeGold.lua

### PR DESCRIPTION
**Pull request by PrinterLUA**

### CODE REVIEW

**Comment by marksamman** [comment]
Address the following and squash your commits:
* x - x is always 0, also why transform to 0?
* item is already a userdata, so Item(item.uid) is unnecessary
* restore the new line at the end of the file

**Comment by PrinterLUA** [comment]
Done ^^

**Comment by marksamman** [comment]
Thank you, now just squash your commits and I'll merge this.

**Comment by PrinterLUA** [comment]
Done:)

**Comment by marksamman** [comment]
I'm not sure why you wrote squash in the commit message, the point of squashing your commits is to have one commit represent your pull request which describes what has been changed in the commit. Explaining that you have squashed your previous commits is not very relevant in the commit log. Even something as simple as "Update changegold.lua" is good enough in this case. Update the commit message and comment again and I'll merge.

**Comment by PrinterLUA** [comment]
Oh did not know, that would be the title. Alright here you go ^^

**Pull request merged**
