### PR TITLE
[Revscriptsys] fixing memory leak in Actions & Moveevents

### PR DESCRIPTION
**Pull request by EvilHero90**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Actions and Moveevents where leaking memory due to having the temporary vectors for registering ids in the pointer itself
Since we copy the values when we register the event we also copied the vectors which wheren't cleared already thus creating memory which was not intended.
I've moved them to their singletons (Actions/MoveEvents) and clear them every registration

**Issues addressed:** 
- #3694 
- #3692

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
related to #3694 and perhaps #3692 (linked on the mentioned PR)

**Comment by MillhioreBT** [comment]
It looks good, although these changes make Revscript objects unsafe to store, since they don't contain their own content themselves.

In OTLand I have seen several scripts that create objects at the beginning of the file and register these objects at the end of the file, so each new object will overwrite the vectors and previous objects would be registered incorrectly.

**Comment by ranisalt** [comment]
> It looks good, although these changes make Revscript objects unsafe to store, since they don't contain their own content themselves.

+1 I don't think this is a good solution

**Comment by EvilHero90** [comment]
> It looks good, although these changes make Revscript objects unsafe to store, since they don't contain their own content themselves.
> 
> In OTLand I have seen several scripts that create objects at the beginning of the file and register these objects at the end of the file, so each new object will overwrite the vectors and previous objects would be registered incorrectly.

Good catch, however this was actually never intended to work that way anyway, we gave a clear structure on how to create revscripts.
I could pass the superior object along with it and if the vectors are not empty but the object is different then throw a warning
`You are trying to overwrite ids/aids/uids from another Action/Moveevent, please fix your script setup and first register the object before adding ids/aids/uids to the next object`

**Comment by MillhioreBT** [comment]
> > It looks good, although these changes make Revscript objects unsafe to store, since they don't contain their own content themselves.
> > In OTLand I have seen several scripts that create objects at the beginning of the file and register these objects at the end of the file, so each new object will overwrite the vectors and previous objects would be registered incorrectly.
> 
> Good catch, however this was actually never intended to work that way anyway, we gave a clear structure on how to create revscripts. I could pass the superior object along with it and if the vectors are not empty but the object is different then throw a warning `You are trying to overwrite ids/aids/uids from another Action/Moveevent, please fix your script setup and first register the object before adding ids/aids/uids to the next object`

Lua is well known for its flexibility when it comes to doing what we want with Lua objects, forcing the programmer or user to follow rules and design patterns seems to me to be too much, I know that your `revscript 2.0` system solves this , as long as you use your assistant,
But if I don't want to use it I will be forced to follow these rules.

I prefer the solution of stealing the vector using swap or simply creating the temporary copy, then cleaning it and then moving it to the actions vector.

example:
image

or swap:
image
image

**Comment by EvilHero90** [comment]
https://github.com/otland/forgottenserver/pull/4742/commits/6e0a6f3d4c51570c342dbd762abd46b728199301
I've reworked it and made a `std::map<Object*, std::vector<uint16_t>>` out of it, now it does behave like it was before but we avoid all this copy/borrow/steal stuff
@MillhioreBT

**Review by ranisalt — DISMISSED** [review]
Seems quite solid now, solves the leak and also saves memory on actions after registering.

**Review by EPuncker — APPROVED** [review]

**Comment by gesior** [comment]
@EvilHero90 
I get into similar problem on 1.4. Can you explain how can I reproduce memory leak?
Or if it was memory leak or memory management optimization to save some KBs of RAM?

> Actions and Moveevents where leaking memory due to having the temporary vectors for registering ids in the pointer itself

These pointers - created in `luascripts.cpp` - are deleted from memory with all their IDs structures by unique_pointer `Action_ptr action{event};` (add destructor to `Action` to test it or compile server with ASAN - it will fail with old code):
https://github.com/otland/forgottenserver/pull/4742/files#diff-1445d56ba3a14e3ecba7e7ad4f2b573d7798789e2547f44cbf092aa0ee69c668R193
This part of old code in `luascript.cpp`:
```cpp
		pushBoolean(L, g_actions->registerLuaEvent(action));
// 'action' is already deleted
		action->clearActionIdRange();
		action->clearItemIdRange();
		action->clearUniqueIdRange();
```
executed functions on already deleted object `action`. You can delete these 3 lines and there is no more ASAN errors (same for movements).

As I understand, thing you fixed is `Actions` singleton `useItemMap` etc. do not store item IDs inside `Action` copies anymore:
```cpp
	using ActionUseMap = std::map<uint16_t, Action>;
	ActionUseMap useItemMap;
```
**Right? So it's not 'memory leak' in C++ meaning of that word, but memory optimization?**

**Comment by MillhioreBT** [comment]
> @EvilHero90 I get into similar problem on 1.4. Can you explain how can I reproduce memory leak? Or if it was memory leak or memory management optimization to save some KBs of RAM?
> 
> > Actions and Moveevents where leaking memory due to having the temporary vectors for registering ids in the pointer itself
> 
> These pointers - created in `luascripts.cpp` - are deleted from memory with all their IDs structures by unique_pointer `Action_ptr action{event};` (add destructor to `Action` to test it or compile server with ASAN - it will fail with old code): https://github.com/otland/forgottenserver/pull/4742/files#diff-1445d56ba3a14e3ecba7e7ad4f2b573d7798789e2547f44cbf092aa0ee69c668R193 This part of old code in `luascript.cpp`:
> 
> ```c++
> 		pushBoolean(L, g_actions->registerLuaEvent(action));
> // 'action' is already deleted
> 		action->clearActionIdRange();
> 		action->clearItemIdRange();
> 		action->clearUniqueIdRange();
> ```
> 
> executed functions on already deleted object `action`. You can delete these 3 lines and there is no more ASAN errors (same for movements).
> 
> As I understand, thing you fixed is `Actions` singleton `useItemMap` etc. do not store item IDs inside `Action` copies anymore:
> 
> ```c++
> 	using ActionUseMap = std::map<uint16_t, Action>;
> 	ActionUseMap useItemMap;
> ```
> 
> **Right? So it's not 'memory leak' in C++ meaning of that word, but memory optimization?**

In that specific case, yes, it is memory optimization, since the Actions maintained the vector with IDs that were not even being used; they were only there for their registration but nothing more.

**Pull request merged**
