### PR TITLE
Fix send yourself in vip list. #2611

### PR DESCRIPTION
**Pull request by danielsalim1**

### CODE REVIEW

**Comment by DSpeichert** [comment]
Is this the behavior in RL Tibia?

**Comment by danielsalim1** [comment]
I don't think so, but I there's no reason to add myself to the friend list... it doesn't make sense

**Comment by ranisalt** [comment]
Why fix if it's not broken tho

**Comment by Znote** [comment]
Think I have seen some OTs where a player could opt out of "online list", and to see if they were hidden they could add themselves to their own vip list. If their own name was red then they knew they were currently "hidden".

**Comment by wgrr** [comment]
This PR is a regression; it had been reported as an issue back then (see #1852 and #1656), it's introducing it back.

**Comment by EPuncker** [comment]
> This PR is a regression; it had been reported as an issue back then (see #1852 and #1656), it's introducing it back.

yes in 2016 it was possible to add yourself on the vip list, now it isn't

**Pull request closed without merging**
