### PR TITLE
Add Wand combat origin type

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Follow-up of https://github.com/otland/forgottenserver/commit/9876f2f374dcb67daaa7488d6c915bc77c88d1dd#diff-ee28d186e505762f7d874ee619cae401419c6fdb6ea8c5817d44b148f397f8c9R412-R417

**Issues addressed:** 
none

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by MillhioreBT** [comment]
The magic wands are not necessarily ranged weapons, so in my opinion it would be better to create a new type of origin.
Example: `ORIGIN_WAND`
This will bring with it an improvement when creating a script to improve attacks that come from magic wands and much easly

**Comment by soul4soul** [comment]
> 
> 
> The magic wands are not necessarily ranged weapons, so in my opinion it would be better to create a new type of origin.
> Example: `ORIGIN_WAND`
> This will bring with it an improvement when creating a script to improve attacks that come from magic wands and much easly

Agreed, I almost suggested `ORIGIN_SPELL` should be used but you are right a new type of origin should be added for wands.

**Comment by EPuncker** [comment]
@MillhioreBT @soul4soul okay guys you won

**Review by MillhioreBT — APPROVED** [review]
LGTM

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
