### PR TITLE
remove unused methods

### PR DESCRIPTION
**Pull request by rookgaard**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Removes old, unused functions.

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by rookgaard** [comment]
@EPuncker Can you add reviewers please?

**Comment by nekiro** [comment]
Why? Is there any advantage to remove two methods? Which later might be used or by someone that use this engine?

**Comment by rookgaard** [comment]
> Why? Is there any advantage to remove two methods? Which later might be used or by someone that use this engine?

@nekiro That's the point. Anyone who uses and will use this engine won't have any chance to make use of:
- `saveAccount` method, because after premium days behaviour were changed https://github.com/otland/forgottenserver/blob/master/src/iologindata.cpp#L1072-L1077 were added (which do the same)
- `getInstantSpellById` as that method is not used in that engine

**Review by ranisalt — APPROVED** [review]
If someone wants to use dead code like this they can keep their fork or copy from the history, it's not obliterated from existence

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
