### PR TITLE
Move Convince Creature to Lua

### PR DESCRIPTION
**Pull request by Kamenuvol**

### CODE REVIEW

**Comment by ninjalulz** [comment]
Hm, this doesn't notify surrounding creatures about the change, and I think you might have fixed a respawn issue.

**Comment by Kamenuvol** [comment]
I will fix the notification, and.. which respawn issue was fixed oO?

**Comment by DSpeichert** [comment]
@ninjalulz Can you contribute the fix for surrounding creatures you mentioned?

**Comment by DSpeichert** [comment]
We have merged #2102 that duplicates this behavior.

However, I see that this version of `convince_creature.lua` also checks for summons and removes them. If that is necessary you can open a new PR adding just those lines.

https://github.com/otland/forgottenserver/pull/2168/files#diff-5b7d3daa3f9be5f0d1e801abf0e79521R33

**Pull request closed without merging**
