### PR TITLE
Removed protocolold

### PR DESCRIPTION
**Pull request by EPuncker**
its not used at all

### CODE REVIEW

**Comment by EPuncker** [comment]
don't hate me guys

**Comment by DSpeichert** [comment]
Well, it is used to tell old clients that they are old instead of not being able to decipher their messages on the wire.

If the current protocol gets upgraded from 11.98 to future versions and login method changes, we'd use similar concept for current protocol.

**Comment by Zbizu** [comment]
and this is a reason good enough to keep it

**Comment by DSpeichert** [comment]
Nothing to gain here.

**Pull request closed without merging**
