### PR TITLE
Add forced argument to on logout creature event

### LINKED ISSUE #2147: onLogout should have second parameter isForced!
onLogout event should have additional parameter isForced. This is necessary in case you have logic that expects player not to be logged out after preventing logout by returning false.

I would create a pull request if I wasn't noob with git :(

### PR DESCRIPTION
**Pull request by marmichalski**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** Closes #2147

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by MillhioreBT** [comment]
Any real life examples? I do not see any use for this parameter, if it is forced or not forced, what happens?

**Comment by marmichalski** [comment]
> Any real life examples? I do not see any use for this parameter, if it is forced or not forced, what happens?

Can't you imagine anything? 😛 

First thing that came to mind is do not let GM to kick a player that has engaged pvp.

**Comment by marmichalski** [comment]
> > Any real life examples? I do not see any use for this parameter, if it is forced or not forced, what happens?
> 
> Can't you imagine anything? 😛
> 
> First thing that came to mind is do not let GM to kick a player that has engaged pvp (which could also be done in kick script, but whatever).

That's a bad example actually, because Player::kickPlayer ignores the event return value. 🤷

**Comment by marmichalski** [comment]
@DSpeichert / @EPuncker if this is not wanted, could the issue be closed along with this PR?

**Review by EPuncker — APPROVED** [review]
well, I see no issue in having it, but lets see what @DSpeichert thinks

**Comment by DSpeichert** [comment]
Hey, I haven't had the chance to think about it earlier.

It looks good but I think the primary purpose is for it to be used in scripts. Therefore, it would be good to extensively document when `forced` is `true` or `false`. Naturally, client-initiated logout is "not forced", and server initiated logout is "forced" (but is it always?). Now, is noPongKick a client or server initiated? Someone might be x-logging on purpose.

Therefore, maybe, and I know it doesn't necessarily make it better, we should have a "Logout cause", maybe an ENUM of "client" / "server" / "timeout" (noPongKick) ?

If it's supposed to be useful and make a stable scripting interface, we should think about it at the design stage - which is now.

**Comment by Zbizu** [comment]
imo `creature:remove(forced?)` and closing the server should be only cases when forced is true

**Comment by MillhioreBT** [comment]
> Hey, I haven't had the chance to think about it earlier.
> 
> It looks good but I think the primary purpose is for it to be used in scripts. Therefore, it would be good to extensively document when `forced` is `true` or `false`. Naturally, client-initiated logout is "not forced", and server initiated logout is "forced" (but is it always?). Now, is noPongKick a client or server initiated? Someone might be x-logging on purpose.
> 
> Therefore, maybe, and I know it doesn't necessarily make it better, we should have a "Logout cause", maybe an ENUM of "client" / "server" / "timeout" (noPongKick) ?
> 
> If it's supposed to be useful and make a stable scripting interface, we should think about it at the design stage - which is now.

It is a perfect idea.

**Pull request closed without merging**
