### PR TITLE
fixed stopped walking onuseitem/itemex

### PR DESCRIPTION
**Pull request by Codinablack**
### Pull Request Prelude

- [x ] I have followed [proper The Forgotten Server code styling][code].
- [ x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 
fixes issue #3411

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Codinablack** [comment]
> Does this work with the Cip client? I can't test it now, but with OTC it works

Yes this definitely works with cip client from my own testing. This PR does however require a review, so if you feel up to it, test for yourself so we can get the bug finally closed and behind us.

**Comment by nekiro** [comment]
If you use hotkeys, client will stop you anyway (cip client < 11 version)

**Comment by MillhioreBT** [comment]
> If you use hotkeys, client will stop you anyway (cip client < 11 version), but for other things like manually using, it should work.

confirmed!

**Comment by Codinablack** [comment]
I will look into how to fix the issue with hotkeys then , and rebase, and post a new pr when I have some time

**Comment by nekiro** [comment]
> I will look into how to fix the issue with hotkeys then , and rebase, and post a new pr when I have some time

but the thing is you cant. It's client sided.

**Comment by Codinablack** [comment]
If that is the case, and both ways are bugged, server and client, should we not at least fix the server side?
So if it is an item not being used with a hotkey, as we do allow checking "hotkey" use in onUseItem() anyways, the user doesn't have the problem? 

Maybe a user wants to completely disallow all hotkey usage on their server... then the bug would only exist on our end right?
I personally prefer hotkey usage disabled, but surely I'm not the only one. 

I have seen, without the changes, the problem exists even outside of hotkey use, and since it exists outside of the client, is it not our responsibility to fix the problem?

If the dev's disagree, then I will close, but if not, then I believe this PR is good for merger, causes no bugs that I have found, and fixes our end of issue #3411

**Review by DSpeichert — APPROVED** [review]

**Comment by DSpeichert** [comment]
I agree that map-click walk does not need to be cancelled when using items (manually, not via hotkey if that's what client controls anyway).

**Pull request merged**
