### PR TITLE
Better handling of DepotLocker and DepotChest

### PR DESCRIPTION
**Pull request by MillhioreBT**
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Now we can verify if a container is a `DepotLocker` or a `DepotChest`.
When we modify the content of a DepotChest, the lastDepotId of the player who owns the deposit is updated

> **Suggestions to improve the code are welcome if you wish**
**Issues addressed:** #2251

### CODE REVIEW

**Comment by nekiro** [comment]
https://github.com/nekiro/TFS-1.4-Downgrades/commit/eb87698fe1ec5b28099a5d74559ce56af61bbd61

**Comment by MillhioreBT** [comment]
> [nekiro/TFS-1.4-Downgrades@eb87698](https://github.com/nekiro/TFS-1.4-Downgrades/commit/eb87698fe1ec5b28099a5d74559ce56af61bbd61)
> ^
> Other than that, depotId is used somewhere in market stuff, not sure why, but probably fixable.

the market uses the player's lastDepotId and this is updated when you open the locker

**Comment by MillhioreBT** [comment]
malformed commits!

**Comment by nekiro** [comment]
> > [nekiro/TFS-1.4-Downgrades@eb87698](https://github.com/nekiro/TFS-1.4-Downgrades/commit/eb87698fe1ec5b28099a5d74559ce56af61bbd61)
> > ^
> > Other than that, depotId is used somewhere in market stuff, not sure why, but probably fixable.
> 
> the market uses the player's lastDepotId and this is updated when you open the locker

why does it though? It has a reason for it? Depots are global, so whats the point of keeping depot id?

**Pull request closed without merging**
