### PR TITLE
Remove promoted vocations from weapons.xml

### PR DESCRIPTION
**Pull request by bpawel10**

### CODE REVIEW

**Comment by nekiro** [comment]
What is fixing this "fix"?

**Comment by bpawel10** [comment]
Sorcerers and druids can still use their wands and rods once they buy a promotion.

**Comment by nekiro** [comment]
They can use it right now too.

**Comment by bpawel10** [comment]
So why weapons for knights and paladins have two vocations?

**Comment by nekiro** [comment]
Probably, because of this code:
https://github.com/otland/forgottenserver/blob/master/src/weapons.cpp#L205

**Comment by bpawel10** [comment]
Okay, so let's remove elite knights and royal paladins instead to unify it.

**Comment by DSpeichert** [comment]
@bpawel10 You can change this PR to remove the promoted vocations and we'll merge it.

**Comment by Kamenuvol** [comment]
I think they are there because showInDescription tag. They should not appear and the default is to appear.

**Comment by DSpeichert** [comment]
@Kamenuvol will they still appear even if the vocation is not listed at all?

**Pull request merged**
