### PR TITLE
Replaced number with constant in offline training code

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by soul4soul — APPROVED** [review]

**Review by Erza — APPROVED** [review]

**Comment by marmichalski** [comment]
how is that a constant? 🤔

**Comment by MillhioreBT** [comment]
The correct term would be, change the constant for a variable XD
a number is a constant, since its value cannot be changed, 1 will always be 1, while a variable can change its value, in case the variable is not declared as a constant `const`

Anyway the changes are fine, and do not cause any problems

**Comment by soul4soul** [comment]
> 
> 
> The correct term would be, change the constant for a variable XD
> a number is a constant, since its value cannot be changed, 1 will always be 1, while a variable can change its value, in case the variable is not declared as a constant `const`
> 
> Anyway the changes are fine, and do not cause any problems

I would use "magic number" to describe the initial implementation instead of "constant" and it's being replaced with a variable which is properly named.

**Review by DSpeichert — APPROVED** [review]
LGTM

**Review by MillhioreBT — APPROVED** [review]

**Comment by DSpeichert** [comment]
Next time make sure the commit message makes sense

**Pull request merged**
