### PR TITLE
feature: itemType:isBed()

### PR DESCRIPTION
**Pull request by Zbizu**
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Added a method to check if `itemType` is a bed.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by nekiro** [comment]
should be in sources, if you ask me

**Comment by Zbizu** [comment]
> should be in sources, if you ask me

https://github.com/otland/forgottenserver/pull/3679#pullrequestreview-770763626

**Comment by nekiro** [comment]
> > should be in sources, if you ask me
> 
> [#3679 (review)](https://github.com/otland/forgottenserver/pull/3679#pullrequestreview-770763626)

Too bad, we have to write group == group_bed in sources now :(

**Comment by Zbizu** [comment]
> Too bad, we have to write group == group_bed in sources now :(

No we don't.
`if (BedItem* bed = item->getBed()) {`

**Pull request merged**
