### PR TITLE
Enforce backward compatibility (#1896)

### PR DESCRIPTION
**Pull request by gugahoa**

### CODE REVIEW

**Comment by marksamman** [comment]
This should be in compat.

**Comment by gugahoa** [comment]
It doesn't load compat before loading spells, so it'll crash anyway if it's in compat. :/

**Comment by Kamenuvol** [comment]
The problem is the opposite.
compat.lua loads before spells.lua, so there is no AREA_CIRCLEnXn yet to assign to AREA_CROSSnXn
We should transfer all subfolder libs to main lib folder and "dofile" them.

**Comment by ranisalt** [comment]
dofile sucks, we instead should reorder which files are loaded if there are no other implications

**Comment by Kamenuvol** [comment]
Compat should be the last lib to be loaded, because all previously libs are supposed to be code updated and not need it. Custom scripts, of course, are loaded after because may still use old code.

**Comment by marksamman** [comment]
This should be fixed by explicitly defining the areas in the compat file.

**Comment by gugahoa** [comment]
I won't be able to make the changes mentioned here until next week, but there's a better solution opened by @kamenuvol, so I'll close the PR

**Pull request closed without merging**
