### PR TITLE
Fix incorrect default key numbers for modals

### PR DESCRIPTION
**Pull request by infister**
Right now clicking "Enter" will abort modal window action.

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by nekiro** [comment]
Didn't you just make default enter click, button 0 which is cancel?

**Comment by infister** [comment]
> Didn't you just make default enter click, button 0 which is cancel?

did you test that button 0 is actually a Cancel?

**Comment by EPuncker** [comment]
tested with client 10.98:
depois2
- used bed -> esc -> training aborted
- used bed -> enter -> training started

everything seems to be working just fine, I remember having this issue on client 12 tho, but on client 10.98 it doesn't happen

**Comment by infister** [comment]
> tested with client 10.98:
> depois2
> 
> * used bed -> esc -> training aborted
> * used bed -> enter -> training started
> 
> everything seems to be working just fine, I remember having this issue on client 12 tho, but on client 10.98 it doesn't happen

well, maybe they have swapped it on 11+
thats worth noting anyway in the future

thank you for testing

**Pull request closed without merging**
