### PR TITLE
Add spell max range

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Add max range when throw spell

#### TibiaRL
- Player cannot throw spell "Exura sio", if target is not on screen

#3427 @emil92b

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by MillhioreBT** [comment]
The default range is 8, 6 why change to 7, 5? if 8, 6 are considered to be in the field of vision

**Comment by ramon-bernardo** [comment]
> The default range is 8, 6 why change to 7, 5? if 8, 6 are considered to be in the field of vision

I tested it TibiaRl, can only use spell with player on screen.
  ```![image](https://user-images.githubusercontent.com/53269692/117215547-bb2ea380-add4-11eb-9aff-2caca0972c81.png)
![image](https://user-images.githubusercontent.com/53269692/117215570-c4b80b80-add4-11eb-8c16-16d684425b5e.png)
  ```

**Comment by MillhioreBT** [comment]
In that case, then okay Although I do not know how this applies for users who use OTC with the modified viewport

**Comment by Znote** [comment]
We should make our hardcoded viewport values configurable, and this should be calculated on the viewport values instead of being hardcoded.

**Comment by ramon-bernardo** [comment]
> We should make our hardcoded viewport values configurable, and this should be calculated on the viewport values instead of being 7, 5.

I'll try, good idea!

**Comment by nekiro** [comment]
> > We should make our hardcoded viewport values configurable, and this should be calculated on the viewport values instead of being 7, 5.
> 
> I'll try, good idea!

I would say it's a thing for another pull request, let it be for this one.

**Comment by ramon-bernardo** [comment]
Links with viewport; [canUseFar()](https://github.com/otland/forgottenserver/blob/aea764cb8d8ea5da41e050d302b99033be1008cf/src/actions.cpp#L311), [playerUseWithCreature()](https://github.com/otland/forgottenserver/blob/aea764cb8d8ea5da41e050d302b99033be1008cf/src/game.cpp#L2201)

**Review by Znote — APPROVED** [review]

**Comment by ranisalt** [comment]
I believe when #3456 is merged, you can use the constants here too instead of 7 and 5

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
