### PR TITLE
Fix #2028

### LINKED ISSUE #2028: GM change outfit + mount = Tibia crash
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login on your GM character
2. Take for random outfit, example Citizen
3. Choose mount, example Widow Queen
4. Mount up, using CTRL + R
5. Change outfit again to Gamemaster Outfit.
6, Enjoy crash

### Expected behaviour
When changing to GM outfit, you should be dismounted.

### PR DESCRIPTION
**Pull request by brunominervino**
Fix crash when player try to mount with GM Outfit #2028

### CODE REVIEW

**Comment by ranisalt** [comment]
Hardcoded magic numbers are not an option.

**Comment by brunominervino** [comment]
@ranisalt in this case, this bug is caused only by gamemaster outfit:
https://github.com/otland/forgottenserver/blob/9c27677b4f660a6c8122a66cfc4e4f2a37257f3e/src/protocolgame.cpp#L2636-L2639

What do you suggest?

**Comment by Kamenuvol** [comment]
I suggest create a boolean in ProtocolOutfit canMount and set false when adding Gamemaster outfit and true for outfits.xml list ones. And check for that.

**Comment by darkjav** [comment]
This solution not work or what?
https://github.com/otland/forgottenserver/commit/ea9ad8e443c855473a1bb7c7d7a5bbbe4251fe89

**Comment by ranisalt** [comment]
Not really, it probably will also crash for any outfit but the ones players can choose. You name it: colorable creature outfits, old GM outfits, etc.

**Comment by elderapo** [comment]
I would suggest to add GM_OUTFIT in consts.h and just use it instead of magic number :)

**Comment by brunominervino** [comment]
@marksamman Can you give us your suggestion?

**Comment by ranisalt** [comment]
Naming a magic number does not make it non-magic.

**Comment by ranisalt** [comment]
This does not fix the issue. The problem is not when the player tries to *mount* with the GM outfit as this is already blocked, the problem is when the player is mounted and then *changes* to an outfit without mounts. It also only crashes the Tibia client, OTClient seems to work fine.

**Pull request closed without merging**
