### PR TITLE
Removing unused corpses and tab adjustments

### PR DESCRIPTION
**Pull request by omarcopires**

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by nekiro** [comment]
I kinda don't know what are these corpses. We aren't using them anywhere?

**Comment by EPuncker** [comment]
> I kinda don't know what are these corpses. We aren't using them anywhere?

nope, we don't, maybe they were used in the past by the animate dead rune, but since the implementation of the isCorpse, this table is not used anywhere else

**Review by nekiro — APPROVED** [review]

**Comment by soul4soul** [comment]
I'd rather just keep it but won't be upset should this PR be merged. The corpse table is hurting anything and makes it easier to bring back animate dead for those who liked playing with that spell.

**Comment by omarcopires** [comment]
> Prefiro ficar com ele, mas não ficarei chateado se esta relações públicas for mesclada. A mesa do cadáver está machucando qualquer coisa e torna mais fácil trazer de volta animado morto para aqueles que gostavam de brincar com esse feitiço.

The rune remains in the game and functioning as it should, except that there is now a function to check if it is a corpse.

**Pull request merged**
