### PR TITLE
Level Door require level to walkthrough

### PR DESCRIPTION
**Pull request by PrinterLUA**
This should fix the issue with this:
https://github.com/otland/forgottenserver/issues/1591

### CODE REVIEW

**Comment by marksamman** [comment]
It won't. The proper solution is setting walk stack to 0 for the open doors, and making walk stack work for other items than ground. There should be a tile flag for walk stack.

**Comment by PrinterLUA** [comment]
Ok, ill take a look at it then.

**Comment by TheSumm** [comment]
This is the proper solution as multiple players should be able to pass through quest doors and gates of expertise.

**Comment by marksamman** [comment]
I still think using walk stack is the better solution, but in that case I would be OK with merging a solution that solves it this way. This PR is more broken than just missing a player variable though, I suggest you test that your solution actually works before submitting a pull request.

**Pull request closed without merging**
