### PR TITLE
Fix monster's IDLE. fixes  #1834, closes #1835.

### LINKED ISSUE #1834: Monsters's IDLE bug.
Monsters don't move(dance) when the player is in screen on PZ.

### PR DESCRIPTION
**Pull request by slavidodo**

### CODE REVIEW

**Comment by PrinterLUA** [comment]
Would this change bring back this issue?
https://github.com/otland/forgottenserver/issues/928

**Comment by slavidodo** [comment]
Check it again, I think this how it should be.

**Comment by PrinterLUA** [comment]
Looks good, but you should test it.

**Comment by slavidodo** [comment]
Yeah, this is tested.

**Comment by marksamman** [comment]
Thanks!

**Comment by ranisalt** [comment]
You should just replace `isSummon() && !isMasterInRange` with `isSummon() || !isMasterInRange`, since it is logically equivalent to `!isSummon() || (isSummon() && !isMasterInRange)`.

**Pull request merged**
