### PR TITLE
Convert all monsters to rev script system

### PR DESCRIPTION
**Pull request by soul4soul**
A long time ago I was working on a program to converter monsters from TFS XML format to pyOT format. Last fall I updated that program to support the TFS revscriptsys monster format. I finally got around to adding a UI and command line interface to the program. Most of the logic is completed for converting from TFS XML format to TFS revscriptsys format. The program is open source and can be found at https://github.com/soul4soul/ot-monster-converter.

For anyone curious to try it themselves they can find binaries hosted on the bitbucket repo. Be aware the only working input format at this time is "TFS XML Format". As for output formats both "TFS Rev Script System Format" and "PyOT" are working. The executable is a whopping 82MB because I made it a self contained exe by packing in the entire .NET core 3.1 SDK. I made that decision since it's not yet common for non devs to have .NET Core SDKs installed on their machines.

Screenshot of the application running. The entire conversion process takes 20 seconds or so.
image

There are still a few issues to work out but I opened this PR so the community would be aware of this work.

- [ ] Discuss with community changing revscriptsys monsters loot drop chance to be a percentage from 0 to 1. Where 1 means 100% drop rate.
- [ ] Discuss with community changing element resistance to a decimal percentage between 0 and "1". 1 = 100% damage no immunity. 0.85 = 15% immunity. 1.15 = 15% weakness.
- [ ] Discuss with community replacing the monsters attacks and defenses for revscriptsys  with the player spell system. Due to the revscriptsys, monsters and spells can be defined in the same file. All creature spells would be defined with the spell system in the monster file and registered directly to the creature. The player spell system is already more powerful then the creature attacks and defenses. 

With this program the process of updating to rev script is seamless and easy for everyone. We should be able to remove the entire XML monster system in a future version of TFS.

### CODE REVIEW

**Comment by strndi** [comment]
Should everything really be made purely in revscripts? While people hate on XML, I think it has it uses, it keeps things much more organized (maybe not so much for monsters, but finding action ids/unique ids is much easier for beginners with our old XML files), XML is also much easier to parse, and all tools that are parsing XML would need to be updated (such as RME, AACS etc).

I think that's some discussion worth having

**Comment by andersonfaaria** [comment]
> Should everything really be made purely in revscripts? While people hate on XML, I think it has it uses, it keeps things much more organized (maybe not so much for monsters, but finding action ids/unique linked to scripts is much easier for beginners with our old XML files), XML is also much easier to parse, and all tools that are parsing XML would need to be updated (such as RME, AACS etc).
> 
> I think that's some discussion worth having

discussions are always worth having, IMO Lua is much more powerful iterating tables than parsing XML. revscripts can be a total substitute for XML.

**Comment by gudan-garam** [comment]
> > Should everything really be made purely in revscripts? While people hate on XML, I think it has it uses, it keeps things much more organized (maybe not so much for monsters, but finding action ids/unique linked to scripts is much easier for beginners with our old XML files), XML is also much easier to parse, and all tools that are parsing XML would need to be updated (such as RME, AACS etc).
> > I think that's some discussion worth having
> 
> discussions are always worth having, IMO Lua is much more powerful iterating tables than parsing XML. revscripts can be a total substitute for XML.

What do you mean by Lua is much more powerful iterating tables than parsing xml?

**Comment by nekiro** [comment]
In my opinion this change is redundant, monster types are static (you can dynamically allocate them via revscriptsys as far as I know though) so there is no need to push them all into revscriptsys. They are only loaded once at server startup and reloaded if you force the server to. Also I think this will give newbies much more trouble to locate and change stuff, because you actually need to know the syntax for lua scripts. I dont know if there are any plans to ditch completely xml, but in my opinion when something does not require any coding/scripting like monsters in this pull request, we should keep them in xml, because why not? Is xml limiting us? I dont think so. It's like editing config file, why would you want to have scripting support in it? I would like to hear more from other people point of view, so lets have a nice conversation about that here.

**Comment by DSpeichert** [comment]
We won't be dropping support for XML for monsters or any other "type", so like @nekiro pointed out, this change isn't actually necessary.

**Comment by MillhioreBT** [comment]
Maybe it is a good idea to do it in the future, I have seen the **Revscript Interface** a bit and you could separate the reloads of each folder, in this way the server will not have to reload all the monsters when in reality we are reloading a simple talkaction for example: 
```c++
g_scripts->loadScripts("scripts/monsters", false, true);
g_scripts->loadScripts("scripts/talkactions", false, true);
g_scripts->loadScripts("scripts/blablabla...", false, true);
```
I guess there are future plans for this, because reloading all the **scripts** always is very redundant.

**Comment by gpedro** [comment]
> Maybe it is a good idea to do it in the future, I have seen the **Revscript Interface** a bit and you could separate the reloads of each folder, in this way the server will not have to reload all the monsters when in reality we are reloading a simple talkaction for example:
> 
> ```c++
> g_scripts->loadScripts("scripts/monsters", false, true);
> g_scripts->loadScripts("scripts/talkactions", false, true);
> g_scripts->loadScripts("scripts/blablabla...", false, true);
> ```
> 
> I guess there are future plans for this, because reloading all the **scripts** always is very redundant.

a good solution is to enable a checker with a manual initializer. by default, revscripts loads all files on the directory, but if have a `init.lua` file, he manages the initialization by yourself using `loadScripts` or another nice API interface

**Comment by EvilHero90** [comment]
> 
> 
> Maybe it is a good idea to do it in the future, I have seen the **Revscript Interface** a bit and you could separate the reloads of each folder, in this way the server will not have to reload all the monsters when in reality we are reloading a simple talkaction for example:
> 
> ```c++
> g_scripts->loadScripts("scripts/monsters", false, true);
> g_scripts->loadScripts("scripts/talkactions", false, true);
> g_scripts->loadScripts("scripts/blablabla...", false, true);
> ```
> 
> I guess there are future plans for this, because reloading all the **scripts** always is very redundant.

This actually doesn't work very well, keep in mind if you don't put every talkaction into ```scripts/talkactions``` then it will be removed on reload and not loaded again.
I've already explained the problems with revscriptsys and reload, thus why I honestly dislike the idea to have a reload command overall.

> 
> 
> > Maybe it is a good idea to do it in the future, I have seen the **Revscript Interface** a bit and you could separate the reloads of each folder, in this way the server will not have to reload all the monsters when in reality we are reloading a simple talkaction for example:
> > ```c++
> > g_scripts->loadScripts("scripts/monsters", false, true);
> > g_scripts->loadScripts("scripts/talkactions", false, true);
> > g_scripts->loadScripts("scripts/blablabla...", false, true);
> > ```
> > 
> > 
> > I guess there are future plans for this, because reloading all the **scripts** always is very redundant.
> 
> a good solution is to enable a checker with a manual initializer. by default, revscripts loads all files on the directory, but if have a `init.lua` file, he manages the initialization by yourself using `loadScripts` or another nice API interface

This would kinda defeat the purpose of the modularity revscriptsys brings into.

**Comment by MillhioreBT** [comment]
> This would kinda defeat the purpose of the modularity revscriptsys brings into.

Maybe add functionality to command: `/reload scripts"/interfacename"`

**Comment by soul4soul** [comment]
I didn't mean to suggest XML format was going anywhere anytime soon. I was thinking in the TFS 2.0 time frame. I don't see the point in maintaining two formats when revscriptsys can do everything XML can do and more. Any commits to changing monsters otherwise requires two systems to change #2979 and #2826. Due to the availability of this tool it's trivial for uses to migrate to revscriptsys. This is all in a similar vain of migrating to the questlog to lua #1973 and #2048.

> 
> 
> P.S good tool, can we have it on github please? I think I would like to contribute to it.

@nekiro  Done. You can find it at https://github.com/soul4soul/ot-monster-converter. I welcome any contributions. I have started to work on [parsing TibiaWiki] in order to creature OT monsters. (https://github.com/soul4soul/ot-monster-converter/pull/2). 

Does anyone have any thoughts or objections on changing item loot drop rate and elemental modifiers to percentages in revscriptsys?

**Comment by Zbizu** [comment]
@soul4soul if none of solutions (current vs percentages) have any serious downsides, I vote for the one that will load faster.

**Comment by DSpeichert** [comment]
This is out of date by now and huge, as discussed above there is a consensus not to remove XML before TFS 2.0 (if that ever happens), so this being an outdated PR, I'm closing it.

**Pull request closed without merging**
