### PR TITLE
Added swamp digging

### PR DESCRIPTION
**Pull request by EPuncker**
now players can get a Leech by digging on a swamp with ID 20230

it was added on unknow version
https://tibia.fandom.com/wiki/Swamp_(Diggable)
I made the script based on this video: https://www.youtube.com/watch?v=nT8ZpoB91Kw
tested and working without breaking any other shovel functions

### CODE REVIEW

**Comment by soul4soul** [comment]
I played cipbia after the 9.8 update. I didn't know it was possible to dig swamp tiles.

**Comment by EPuncker** [comment]
> I played cipbia after the 9.8 update. I didn't know it was possible to dig swamp tiles.

there are only like 5 of these tiles in a real map tho 😛

**Comment by BahamutxD** [comment]
You are using the same storage as nailCaseUseCount from https://github.com/otland/forgottenserver/pull/2938

**Comment by EPuncker** [comment]
> You are using the same storage as nailCaseUseCount from #2938

fixed! thanks

**Comment by BahamutxD** [comment]
Working just fine (reduced cooldown for testing purposes)

https://gfycat.com/bothglamorousindianhare

**Pull request merged**
