### PR TITLE
Move getMaster down 1 line - mass healing.lua

### PR DESCRIPTION
**Pull request by WibbenZ**
There is no reason to get the master, since it might not be needed.

### CODE REVIEW

**Comment by raymondtfr** [comment]
While your at it, you could also remove that pair of redundant parenthesis in min/max -- so that ``((a / 5) + (b * n) + c)`` becomes ```(a / 5) + (b * n) + c``.

**Comment by WibbenZ** [comment]
But c is still used in the formula xD
The point of using parentheses is so you can click on one to see where that part begins and ends.
But if Mark prefers it ill change it.

**Comment by raymondtfr** [comment]
Well, **``c``** will still be part of the arithmetic. By the way, all formulas of spell files now uses this style -- it was great a suggestion of @ranisalt . This style makes formulas look even more clearer when it is a attack spell -- because we can use ``-min`` instead of enclosing the whole formula with **``()``** and appending a **``-``** sign.

**Comment by WibbenZ** [comment]
Yes both ways works, but I updated it.

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
