### PR TITLE
Replace reinterpret_casts.

### PR DESCRIPTION
**Pull request by djarek**
Replaced reinterpret_casts where the semantic meaning of the type
cast is satisfied by a static_cast (in other word where we cast
pointers/references to objects that are related).

### CODE REVIEW

**Comment by marksamman** [comment]
reinterpret_cast should be preferred over static_cast when casting pointers because it doesn't impose any runtime overhead, it just interprets the same bits of data as another type. static_cast will re-construct the new type with the old type's value (semantically no difference when casting pointers). Correct me if I'm wrong.

**Comment by djarek** [comment]
AFAIK the only C++-style cast that imposes an overhead is dynamic_cast (because it does checks using RTTI).
```
dynamic_cast
 is primarily used to perf
orm “safe downcasting,” i.e.,
to determine whether an object is 
of a particular type in an inher-
itance hierarchy. It is the only cast that cannot be performed us-
ing the old-style syntax. It is also the only cast that may have a
significant runtime cost
. (I’ll provide details on this a bit later.)
```
source: http://www.aristeia.com/EC3E/3E_item27.pdf
(it quotes Meyer's book, so I guess it's a reliable source)

**Comment by marksamman** [comment]
So assuming they generate the same code when casting pointers, what's the benefit of replacing reinterpret_cast with static_cast?

**Comment by djarek** [comment]
The benefit is that it's clear at first glance that we're not doing any fancy pointer magic and the compiler checks whether types are related when using a static_cast (basically reinterpret_cast throws away type safety).

**Comment by marksamman** [comment]
Fair enough. Thanks!

**Pull request merged**
