### PR TITLE
Adding icon to windows executable

### PR DESCRIPTION
**Pull request by omarcopires**
For some reason the icon was removed, I see no reason for that.
I just added it for better viewing

### CODE REVIEW

**Comment by ericlancebrown** [comment]
RIP AppVeyor

**Review by ericlancebrown — APPROVED** [review]
Builds fine for me on Windows and Ubuntu. Not really anything code wise that could go wrong, so I don't see the point in not improving a feature such as an icon.

**Comment by DSpeichert** [comment]
I have to ask: what's the license behind this icon?

**Comment by omarcopires** [comment]
> I have to ask: what's the license behind this icon?

It was used in the project for a long time, I believe there were no problems in that regard.

**Comment by nekiro** [comment]
If it's the old tfs 0.x icon, then I would change it, this isn't tfs 0.x anymore, so let's put a new one, which gonna feel fresh.

**Comment by omarcopires** [comment]
> If it's the old tfs 0.x icon, then I would change it, this isn't tfs 0.x anymore, so let's put a new one, which gonna feel fresh.

I see no reason to change something that I think is nice, so feel free to send a pull request.

**Comment by peonso** [comment]
> > I have to ask: what's the license behind this icon?
> 
> It was used in the project for a long time, I believe there were no problems in that regard.

If the origin of the image is not trackable there is no point into using it, specially since making a similar one is so easy.

**Comment by ericlancebrown** [comment]
I vote for a new Forgotten Server logo. That'd be awesome.

**Comment by ranisalt** [comment]
What about a contest in OTLand? I don't think we have designers around here that could make something good.

**Comment by omarcopires** [comment]
> What about a contest in OTLand? I don't think we have designers around here that could make something good.

This idea is incredible!!!!

**Comment by EPuncker** [comment]
> What about a contest in OTLand? I don't think we have designers around here that could make something good.

> > What about a contest in OTLand? I don't think we have designers around here that could make something good.
> 
> This idea is incredible!!!!

here guys:
https://otland.net/threads/new-tfs-logo-icon.274494/

**Comment by MillhioreBT** [comment]
I have seen several very good designs in the thread posted in otland, don't forget this PR ;)
and by the way what will happen with the verification compilations? example: `AppVeyor` does this affect anything?

**Pull request closed without merging**
