### PR TITLE
Fix MatrixArea rotations and add tests

### PR DESCRIPTION
**Pull request by ranisalt**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:**

Fixes an issue where rotating spells using `flip()` and `mirror()` would sometimes incorrectly generate the new area with the wrong positions. To ensure this does not happen again, added unit tests checking that the correct positions will or will not get spell effects, and that the center of the area is correctly moved when rotated.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by ranisalt** [comment]
Flip, mirror and transpore are correct, but are the wrong functions to use where they are used. Fixed and removed the unused code.

**Review by MillhioreBT — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]

**Comment by omarcopires** [comment]
Some errors are being returned when trying to compile on mvs 2022.
* Master environment, without any changes.
* Previous commits compile normally.
I apologize for the mistakes in Portuguese, but it's something like "unresolved external symbol"

image

**Comment by ranisalt** [comment]
@omarcopires check #4396 it should fix the problem

**Comment by omarcopires** [comment]
> @omarcopires check #4396 it should fix the problem

works fine!

**Pull request merged**
