### PR TITLE
Reformat according to .clang-format

### PR DESCRIPTION
**Pull request by DSpeichert**
### Pull Request Prelude

- [ ] I have followed [proper The Forgotten Server code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** Let's see if PR check likes this more.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by ranisalt — APPROVED** [review]

**Comment by EPuncker** [comment]
@DSpeichert add a `;` to all `registerEnumIn` and `registerEnum`, while at it please. to fix direct formatting on windows 😄 

2022-04-17 20_15_21-GitHub Desktop

**Comment by DSpeichert** [comment]
@EPuncker can you link to code?

**Comment by EPuncker** [comment]
> @EPuncker can you link to code?

nvm, my bad 😝

**Comment by EPuncker** [comment]
> @EPuncker can you link to code?

nvm, my bad 😝

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
