### PR TITLE
Function updated

### PR DESCRIPTION
**Pull request by vankk**
Now we can use _player:doPlayerAddExp(exp, multi)_ instead of _doPlayerAddExp(player:getId(),exp, multi)_

### CODE REVIEW

**Comment by diath** [comment]
That function's in compat for a reason - to keep backwards compatibility with old scripts.

**Comment by vankk** [comment]
Oh, I'm sorry, I did not know that.

**Comment by ranisalt** [comment]
Also there's `player:addExp` which is what that function uses.

**Comment by vankk** [comment]
@ranisalt 
You didn't mean `player:addExperience` [1692](https://github.com/otland/forgottenserver/blob/c4b10a905b11728522e715bd41f2493858ab0e46/src/player.cpp#L1692)?

**Comment by vankk** [comment]
maybe `player:addExperience` is missing experience multiply value?

**Comment by ranisalt** [comment]
Yes, I meant, and no, you should calculate multipliers prior to applying addExperience.

**Comment by vankk** [comment]
@ranisalt 
I know this is a support board but could you give me a example of that?

**Pull request closed without merging**
