### PR TITLE
fix targeted spells bug

### PR DESCRIPTION
**Pull request by Zbizu**
### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Steps to reproduce
1. go to some place on the surface
2. spawn some wall with /i
3. put some creature on the other side
4. cast a missile rune or a targeted strike spell

### Expected Result
spell cancelled

### Actual Result
spell goes through wall when there are no obstacles above because it's treated like item throwing

### Changes Proposed
stop treating throwing spells like throwing items

**Issues addressed:** see **steps to reproduce**
### Reproduction environment
This bug was discovered while working with isSightClear, but is not related to map.cpp so no conflict will arise between these pulls.
This bug can be reproduced with any build. It's also present in my build from November 2020 and was there for unknown amount of time so you can reproduce it with your own tfs builds as well.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by MillhioreBT** [comment]
Is this really happening? I was so curious that I wanted to try it, and it doesn't seem to work the way you describe it here, at least for me. I have always seen that the projectiles respect the walls and the line of sight

**Comment by Zbizu** [comment]
I'll record a video when I'm home.

**Comment by Zbizu** [comment]
Weird thing, I'm not able to reproduce that bug anymore. I'll continue testing my other PRs to see what might be the cause.

**Comment by Zbizu** [comment]
My bad, had executable from another branch running.

**Pull request closed without merging**
