### PR TITLE
Player::canSeeCreature check creature is null

### PR DESCRIPTION
**Pull request by Eternal-Scripts**
- Fix a random crash when the creature is null (0x0)

### CODE REVIEW

**Comment by DSpeichert** [comment]
You're probably just hiding a symptom of a larger problem - why is this function called on null in the first place?

**Comment by Eternal-Scripts** [comment]
@DSpeichert i don't remember now why, but this check is important btw.
The alternative is track every place who use this function and put a check too, but in big systems this is recommended.

**Comment by Lyuzera** [comment]
In many places where this method is called, it is checked first if the creature exists, but I think the verification inside the method is valid, because we don't know if it's checking everywhere before. It is an extra security.

**Comment by Znote** [comment]
Is it possible to throw out a warning, possibly a staktrace before returning false if creature does not exist? 

That way we solve this problem, as well as enlighten the users of which process is causing this error. 
Is it a performance thingy that stops us from verifying function params? We just expect a function to be used correctly?

**Comment by DSpeichert** [comment]
Let's find a proper fix instead.

**Pull request closed without merging**
