### PR TITLE
Updated Visual Studio project file

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

- Updated toolset from version **142** to **143**
- Renamed folder from **vc14** to **vc17** (minor/aesthetical change that should've been done years ago) to comply with MSVS 2022 file version (it was done [here](https://github.com/otland/forgottenserver/commit/18a259d07d0c91ea5ce5d1d819a5397e8f2f9bc4) once)
- maybe a couple guides will need a small rewrite after using **vc14** folder for so long, but its fine

### If you are not a Windows developer/user:
But want to know what is new on MSVS 2022, [click here](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2022?view=vs-2022)
best part: **it finally runs natively on 64x bits**

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
and yes, I've tested it, everything working flawlessly

**Comment by marmichalski** [comment]
Why 17 when the version is 15 and you did not change these? :thinking: 
https://github.com/otland/forgottenserver/blob/f3e6de0c57298c21bc085e0ce04feb377b1b123b/vc14/theforgottenserver.sln#L3
https://github.com/otland/forgottenserver/blob/f3e6de0c57298c21bc085e0ce04feb377b1b123b/vc14/theforgottenserver.vcxproj#L2

**Comment by EPuncker** [comment]
> Why 17 when the version is 15 and you did not change these? 🤔
> 
> https://github.com/otland/forgottenserver/blob/f3e6de0c57298c21bc085e0ce04feb377b1b123b/vc14/theforgottenserver.sln#L3
> 
> 
> https://github.com/otland/forgottenserver/blob/f3e6de0c57298c21bc085e0ce04feb377b1b123b/vc14/theforgottenserver.vcxproj#L2

u happy now?

**Comment by Erza** [comment]
> Why 17 when the version is 15 and you did not change these? 🤔

Version number is 17 https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History

**Comment by marmichalski** [comment]
> > Why 17 when the version is 15 and you did not change these? 🤔
> 
> Version number is 17 https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History

That's what I've meant. The version was left at 15.x in the files I've linked. Reading my comment now, and it's not clear for me too, but the attached snippets helped me 🥸
Also @EPuncker understood it and updated the files 🥦

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
