### PR TITLE
Added a config to enable/disable dice usage on depot

### PR DESCRIPTION
**Pull request by EPuncker**
It is not possible any longer to use Dies on Depot Lockers and the Counter between the them. [10.36 update]

### CODE REVIEW

**Comment by nekiro** [comment]
use tile:hasFlag(TILESTATE_DEPOT)

**Comment by EPuncker** [comment]
> tile:hasFlag(TILESTATE_DEPOT)

that way I would still be able to use the dice on myself, I would need a function to check the 9 SQM around me to look for a depot for it to be perfect

**Comment by EPuncker** [comment]
@nekiro maybe creating a Lua function for this?
`https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L759-L775`

**Comment by DSpeichert** [comment]
Is this ready or a draft? I'm unsure based on your last comment.

**Comment by EPuncker** [comment]
> Is this ready or a draft? I'm unsure based on your last comment.

ready

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
