### PR TITLE
Fixed displaying Premium Account (status) in client

### PR DESCRIPTION
**Pull request by slawkens**
After Mark update Premium Status stopped showing in Tibia Client.

This push fixes it.
Now client displays correct Premium Status (either free or premium with days).

### CODE REVIEW

**Comment by DSpeichert** [comment]
Can you link to the commit that broke it?

**Comment by slawkens** [comment]
In this commit there were some changes how packet were sent to the client:
https://github.com/otland/forgottenserver/commit/2cc16851e69d9dd9ad8a80c9add3312de9d2d890#diff-4aa7a24bdaebd6ae3f1ee9500e6b47e0

I think it doesn't work since then. I saw other posts on otland about it.

**Comment by DSpeichert** [comment]
image
Is OTClient showing wrong number of days left or was this also not working properly? I should only have 2 days left per database.

**Comment by slawkens** [comment]
As you can see I've only changed one byte from 0 to 1 (if premium). Nothing with days. So it might be something with OTClient.

Tested only with official Tibia Client 10.98.

**Pull request merged**
