### PR TITLE
Moved Creature:addDamageCondition to core

### PR DESCRIPTION
**Pull request by raymondtfr**
Users should also be able to use such metatable method in other kinds of scripts (e.g. Claw of the Noxious Spawn, Poison Arrow, Viper Star, etc.)

### CODE REVIEW

**Comment by diath** [comment]
Perhaps you could create some constants for the listType variable rather than using magic numbers.

**Comment by raymondtfr** [comment]
Added such constants, they make it more clear to use that method, although very long to read hah.
I'll update spells to use use such constants later.

@diath

**Comment by ranisalt** [comment]
You'll need to rebase after #2326

**Comment by ranisalt** [comment]
Sweet!

**Pull request merged**
