### PR TITLE
Added isBoss flag

### PR DESCRIPTION
**Pull request by EPuncker**
also added Lua part to get/set it

// get: monsterType:isBoss() set: monsterType:isBoss(bool)

a following pull request will be made in order to add the flags to the xml monster files

### CODE REVIEW

**Comment by nekiro** [comment]
why do we need it though? It's not part of any bigger system or anything

**Comment by EPuncker** [comment]
> why do we need it though? It's not part of any bigger system or anything (its not even used for anything)

this may come in hand when users need to check if a monster is a boss or not, and might be used for the reward chest feature in the future

**Comment by EvilHero90** [comment]
You are missing the monsterType info change incase you didn't notice, but yea probably better to add it now since monsters get reworked anyway then waiting until other stuff is implemented and then we need another rework on monsters.

**Comment by DSpeichert** [comment]
What does this do (or will do)?
How can this be useful later?

I'm guessing for the special loot handling. Can we also edit the monsters to make the right ones a "boss" with that?

**Comment by EPuncker** [comment]
> What does this do (or will do)?
> How can this be useful later?
> 
> I'm guessing for the special loot handling. Can we also edit the monsters to make the right ones a "boss" with that?

I wanted to do that in a following up commit to not cluster this one, but will do it here instead

**Comment by DSpeichert** [comment]
> I wanted to do that in a following up commit to not cluster this one, but will do it here instead

Hmm, maybe not.

**Pull request merged**
