### PR TITLE
Traps update

### PR DESCRIPTION
**Pull request by EPuncker**
- should work on player too
- added walkable lava (id: 25331) found on 9. something update
- added their names
- jungle maw should take 2 and a half minute to be open again and not on stepout
- fixed slits name
- slits should trigger on stepin and not from time to time
- fixed spikes timer

disclaimer:
yes I know we are not trying to mimic the original game, but these changes make more sense, see an after and before comparision:

before:
antes

after:
depois

### CODE REVIEW

**Comment by soul4soul** [comment]
My test char is a 37 sorc, spike shield, plate legs, some mage robe.

### Jungle maw
Always 30 earth damage. Damage is reduced by eq modifiers, resistance, and immunity. The best place to test in cipbia is port hope.

### Spikes
Never exceeded 58 damage in my limited test. Damage might be applied as physical so it takes into account armor/defense? I'm guessing since the character was hit so much less then the monsters. Decent test location on cipbia is greenshore. 
```
09:20 An orc spearman loses 57 hitpoints. 
09:20 An orc loses 58 hitpoints. 
09:20 An orc loses 58 hitpoints. 
09:20 An orc loses 58 hitpoints. 
09:21 You lose 45 hitpoints. 
09:21 You lose 39 hitpoints. 
09:21 You lose 41 hitpoints. 
09:21 You lose 46 hitpoints. 
09:21 You lose 40 hitpoints. 
09:21 You lose 46 hitpoints. 
09:22 You lose 39 hitpoints.
```

### Blades
Damage might be applied as physical so it takes into account armor/defense? I'm guessing since the character was hit so much less then the monsters. Decent test location on cipbia is greenshore.  The comment for blades can be improved by changing `[1510] = { -- strange` to `[1510] = { -- strange slits`
```
09:22 You lose 46 hitpoints. 
09:22 An orc warrior loses 54 hitpoints. 
09:22 An orc warrior loses 56 hitpoints. 
09:22 You lose 43 hitpoints. 
09:22 An orc warrior loses 54 hitpoints. 
09:22 An orc warrior loses 53 hitpoints. 
09:23 An orc spearman loses 55 hitpoints. 
09:23 You lose 43 hitpoints. 
09:23 You lose 43 hitpoints. 
09:23 You lose 46 hitpoints. 
09:23 You lose 45 hitpoints. 
09:23 You lose 37 hitpoints. 
09:23 You lose 43 hitpoints. 
09:23 You lose 44 hitpoints. 
```

**Comment by EPuncker** [comment]
@soul4soul yes, I was talking with @nekiro about this, seems to be an issue with doTargetCombat, I'll open a separated issue for this

**Review by omarcopires — DISMISSED** [review]

**Comment by EPuncker** [comment]
@DSpeichert this is ready!

**Review by soul4soul — CHANGES_REQUESTED** [review]
Based on my testing this PR the wrong damage values for jungle maw, blades, and strange slits. See my previous comment.

**Review by peonso — CHANGES_REQUESTED** [review]
Update values as requested by @soul4soul. Wrong values to make up for a problem on other part of the engine makes nosense, would require another update.

**Review by DSpeichert — DISMISSED** [review]

**Comment by EPuncker** [comment]
@soul4soul can you review it again please? [make sure to have this commit applied](https://github.com/otland/forgottenserver/commit/cc7cebf85b92a9dad4ec94a20e5d5b085838fd14)

**Review by DSpeichert — APPROVED** [review]

**Comment by soul4soul** [comment]
This looks better. I would change `damage` to a scalar instead of an array.  I didn't test the effects of a shield on the damage so I can't say it it should help in blocking the damage or not. Assuming it doesn't in the call to doTargetCombat seems fine.

**Review by soul4soul — APPROVED** [review]
This looks better. I would change `damage` to a scalar instead of an array.  I didn't test the effects of a shield on the damage so I can't say it it should help in blocking the damage or not. Assuming it doesn't in the call to doTargetCombat seems fine.

**Pull request merged**
