### PR TITLE
onMove creature event

### PR DESCRIPTION
**Pull request by gugahoa**
I was having trouble squashing commits, so I made a new pull request.

### CODE REVIEW

**Comment by Codinablack** [comment]
:+1:

**Comment by Codinablack** [comment]
Is there a reason this hasn't been merged yet?

**Comment by marksamman** [comment]
Yes, it was specified in the previous pull request.

**Comment by gugahoa** [comment]
https://github.com/otland/forgottenserver/pull/1166#issuecomment-72361916

Must wait for onStepIn and onStepOut enchancements.

**Comment by gugahoa** [comment]
I was thinking of making the change in onStepIn/onStepOut to prevent movement so this PR can be accepted or not. I thought of using postAddNotification and postRemoveNotification but soon discarded that idea, because as the name implies, it's a post notification. Any suggestions?

Is it better to create a issue to ask this or not?

**Comment by gugahoa** [comment]
I still have the branch with this change, if it's needed just give me a heads up and I'll sync the fork and make a new pull request.

**Comment by deniso95** [comment]
@gugahoa any tips how to use it ? becouse it doesn't seems to work for me or i have incorrectly added the creaturescript

creaturescripts.xml

    <event type="move" name="CreatureMove" script="test.lua" />

test.lua

    function onMove(creature, newPos, oldPos)
	creature:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "TEST")
    end

Nothing happens :/

I've also tried to clog some cpp functions and:
- bool CreatureEvent::executeOnMove in creatureevent.cpp doesn't execute

- And now the weird part :D
When i add clog at the top of Game::internalMoveCreature in game.cpp it work's fine, but when i add it into "for" loop in the same function (added in gugahoa onMove creature event commit) it doesn't show.
It looks like Game::internalMoveCreature ignore this loop - why ?

**Pull request closed without merging**
