### PR TITLE
Fix int_fast16_t overflow

### PR DESCRIPTION
**Pull request by ramon-bernardo**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Fix int_fast16_t overflow

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by soul4soul — DISMISSED** [review]

**Comment by DSpeichert** [comment]
From the commit message, PR message and the code, I still have no idea what the problem is and what the fix fixes.

**Comment by ranisalt** [comment]
> From the commit message, PR message and the code, I still have no idea what the problem is and what the fix fixes.

The range arguments are int32, but the result variable is int16, therefore overflow may occur if the range does not fit 16 bits. It doesn't usually happen, because the range is usually small (this function is heavy af, it usually runs with the viewport dimensions).

**Comment by DSpeichert** [comment]
@ranisalt `int` or `int32_t` to keep it the same?

**Comment by ranisalt** [comment]
`auto` to avoid conversions, but `int32_t` between those

**Review by DSpeichert — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
