### PR TITLE
[WIP] Fix Monsters Loot

### PR DESCRIPTION
**Pull request by brunominervino**
Based on http://tibia.wikia.com/wiki/Loot_Statistics

### CODE REVIEW

**Comment by brunominervino** [comment]
@Mkalo @raymondtfr @WibbenZ 
I have made a html crawler from tibiawiki, to get automatically items and your percentages. If I create a separate repository, with these informations, can you help me revise all files? Have a lot and I have small time.

Thank you!

**Comment by WibbenZ** [comment]
Sorry got enough on my plate as it is right now :/

**Comment by brunominervino** [comment]
I understand bro. 👍

**Comment by wgrriffel** [comment]
@brunominervino instead you could post the sources of your crawler, so we could revise it instead revise whole monster files.

**Comment by brunominervino** [comment]
@wgrriffel, my source generate only the loot, is very simple, but have a small problem with this.

For example:
http://tibia.wikia.com/wiki/Barbaria

Some loots, don't have percentage, so, look at Statistics Page:
http://tibia.wikia.com/wiki/Loot_Statistics:Barbaria

Because of this, need revise manually :(

My idea to parse the page, is the facility to fix the loots found.

**Comment by wgrriffel** [comment]
@brunominervino if there is less than one thousand monster killed statistic you should just skip, in this case percentages are not trustworthy

**Comment by brunominervino** [comment]
Source:

```php
<?php

namespace TibiaCrawler;

use Symfony\Component\DomCrawler\Crawler;

class Wiki
{
    private const $xmlFolder = dirname(__DIR__) . DIRECTORY_SEPARATOR . "creatures";
    function __construct() {
        if (!file_exists($xmlFolder)) {
            mkdir($xmlFolder, 0777, true);
        }
    }

    public function parseCreatures($creatures)
    {
        foreach ($creatures as $c) {
            $folder = $c["folder"];
            foreach ($c["creatures"] as $m) {
                $creature = $m;
                $creature = str_replace(" ", "_", $creature);
                $url = "http://tibia.wikia.com/wiki/Loot_Statistics:" . $creature;
                $html = file_get_contents($url);
                $crawler = new Crawler();
                $crawler->addHtmlContent($html);

                $content = $crawler->filterXPath('//table[1]/tr[position() > 1]');
                $linhas = [ ];
                foreach ($content as $row) {
                    $amount = $row->childNodes[2]->nodeValue;
                    $item = strtolower($row->childNodes[4]->nodeValue);
                    $chance = ((double)str_replace("%", "", $row->childNodes[10]->nodeValue)) * 1000;

                    if (!strpos($item, "empty")) {
                        if (strpos($amount, "-")) {
                            $explode = explode("-", $amount);
                            $linhas[] = '<item name="' . $item . '" countmax="' . $explode[1] . '" chance="' . $chance . '" />';
                        } else {
                            $linhas[] = '<item name="' . $item . '" chance="' . $chance . '" />';
                        }
                    }
                }

                $creaturesFolder = $xmlFolder . DIRECTORY_SEPARATOR . $folder;
                if (!file_exists($creaturesFolder)) {
                    mkdir($creaturesFolder, 0777, true);
                }

                $filename = $creaturesFolder . DIRECTORY_SEPARATOR . strtolower($creature) . ".txt";
                $fh = fopen($filename, "w") or die("Could not open log file.");
                foreach ($linhas as $linha) {
                    fwrite($fh, $linha . PHP_EOL) or die("Could not write file!");
                }

                fclose($fh);
            }
        }
    }
}
```

Simple usage:
```php
use TibiaCrawler\Wiki;

$creatures = [
    "Arachnids" => [ "folder" => "Arachnids", "creatures" => ["Crystal Spider", "Giant Spider", "Poison Spider", "Sacred Spider", "Sandstone Scorpion", "Scorpion", "Spider", "Tarantula", "Wailing Widow" ]]
];

$wiki = new Wiki();
$wiki->parseCreatures($creatures);
```

You need Symfony DomCrawler

**Comment by comedinha** [comment]
The loot chance not is (Kills to Get 1 * 100000)?
and TibiaML Statistics is better.

**Comment by raymondtfr** [comment]
I don't mess with websites, so I don't know html or any website programming languages for that matter 😜 .

IMHO, i think updating monsters loot chance may is tricky if you ask me, because the wikia is constantly being updated with newer data from server logs, hence modifying the probability/approximation for each item, meaning this could be an endless job 😐 .

Although fixing incorrect item ids, their counts is great.

**Comment by brunominervino** [comment]
Based on the comment from @ray, I thought better and it really is an endless job.
Anyway, worth the try hahaha
Thanks!

**Comment by ranisalt** [comment]
You can just use rough approximations for loot chance. I mean, if something has a 1.267% drop chance it probably is 1.25% or even 1% with a pretty lucky hunt.

**Comment by vankk** [comment]
I don't think that we should care about monsters in this datapack even because we have [this](https://otland.net/threads/monsterpack-spellpack-and-creaturescriptspack-for-tibia-10-7-tfs-1-1-based-on-real-tibia.215685/).

**Comment by ranisalt** [comment]
I agree with @vankk and this type of work should be handled by a third party, as I stated before. We could then just point to the monster pack as a submodule instead.

Anyone care to do that?

**Pull request closed without merging**
