### PR TITLE
Automatic Remount https://github.com/otland/forgottenserver/issues/1273

### PR DESCRIPTION
**Pull request by PrinterLUA**

### CODE REVIEW

**Comment by PrinterLUA** [comment]
It works, but i know the boolean name is bad and also should i make it option in the config?

@marksamman

**Comment by djarek** [comment]
For future reference: you don't have to provide links to issues, instead, just write #number_of_the_issue in the title/description of the PR.

**Comment by ranisalt** [comment]
My suggestion: name it `lastMountStatus`

**Comment by ranisalt** [comment]
My suggestion: name it `lastMountStatus` and create an enum with `NOT_MOUNTED` and `MOUNTED`.

**Comment by WibbenZ** [comment]
```
bool shouldMount = false;
```
Sounds better to me, then just use a boolean insted of enums.

**Comment by marksamman** [comment]
Use wasMounted as the variable name, and squash your commits when you're
done.

**Comment by PrinterLUA** [comment]
Done

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
