### PR TITLE
Adding features from #998

### LINKED ISSUE #998: Missing item attributes [$100]
# Missing Item Attributes

Hello,
There are some attributes that have been implemented in TFS 0.4, but that aren't added in 1.0.
### Attribute list

Increasing power of melee / magic / healing:

```
increasemeleevalue
increasemeleepercent

increasemagicvalue
increasemagicpercent

increasehealingvalue
increasehealingpercent
```

Reflect system - something like absorb system, but the attacker gets some of the damage back:

```
reflectpercentall
reflectpercentelements
reflectpercentmagic
reflectpercentenergy
reflectpercentfire
reflectpercentearth
reflectpercentice
reflectpercentholy
reflectpercentdeath
reflectpercentlifedrain
reflectpercentmanadrain
reflectpercentdrown
reflectpercentphysical
reflectpercenthealing
```

For every reflect type:

```
reflectchanceall
reflectchanceelements
reflectchance...
```

Extra attributes for absorbing player / monster damage, could be useful for creating tank items:

```
absorbpercentmonsters
absorbpercentplayers
```

Also it should be possible to set those attributes by using item:setAttribute(...)
# Bounty

Unfortunately I'm kinda busy, so I won't have time to work on it.
Fortunately Znote gave idea for using **Bountysource**, so I'm setting $65 bounty for adding those atributes.
## <bountysource-plugin>

There is a **[$100 open bounty](https://www.bountysource.com/issues/5013382-missing-item-attributes-100?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F392151&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nekiro**
This pr resolves #998 
I have added requested attributes, not sure if the bounty is still valid and to be claimed?

Usage for dynamic reflect, reflect chance and boosts
```lua
local item = player:addItem(8877, 1)
if item then
	item:setBoostPercent(COMBAT_PHYSICALDAMAGE, 200)
        item:setReflect(COMBAT_PHYSICALDAMAGE, {percent = 10, chance = 100})
end
```

New lua methods:
```lua
item:setReflect(combatType, reflect)
item:getReflect(combatType, total = true)

reflect = {percent = 0, chance = 0}
```

```lua
item:setBoostPercent(combatType, value)
item:getBoostPercent(combatType, total = true)
```
**Total** argument in both methods means return also the ability value (items.xml attributes)

I didn't implement, but they can be implemented if requested:
```
absorbpercentmonsters
absorbpercentplayers
```
and these too, cause they are achiveable through using boosts
```
increasemeleevalue
increasemeleepercent

increasemagicvalue
increasemagicpercent

increasehealingvalue
increasehealingpercent
```

### CODE REVIEW

**Comment by Znote** [comment]
Here is the new bounty link:
https://www.bountysource.com/issues/5013382-missing-item-attributes

It appears its still valid and possible to be claimed.

**Comment by EPuncker** [comment]
adding the following to a spike sword:
```
<attribute key="reflectpercentphysical" value="99" />
<attribute key="reflectchancephysical" value="99" />
```
won't work, and spams the server console with "99" (whatever number is used in the value)

edit: I noticed it only works with armors, not weapons 😝 , makes sense
edit2: Using reflectpercentall displays everything correct but with a "undefined" included, I don't know why

I don't know if you are taking suggestions in this PR since its pretty done already, but the system would be really complete having these:

Resist: reduce damage by x%
Absorb: reduce damage by x%, heal x%
Reflect: take full damage, deal x% to attacker
Deflect: reduce damage by x%, deal x% to attacker

thanks for this PR nekiro

and @Znote your bounty link is not working (internal server error)

**Comment by nekiro** [comment]
@EPuncker did you just try to use reflect (which works when you get damage and it reflects it) on sword? How did you think that would work xD

**Comment by Leo32onGIT** [comment]
@DSpeichert label/review

**Comment by MohamedRefaat** [comment]
I tried to add these changes and compile but i found these errors

`1>creature.obj : error LNK2001: unresolved external symbol "public: short __cdecl Item::getBoostPercent(enum CombatType_t)" (?getBoostPercent@Item@@QEAAFW4CombatType_t@@@Z)
1>item.obj : error LNK2001: unresolved external symbol "public: short __cdecl Item::getReflectPercent(enum CombatType_t)" (?getReflectPercent@Item@@QEAAFW4CombatType_t@@@Z)
1>item.obj : error LNK2001: unresolved external symbol "public: short __cdecl Item::getReflectChance(enum CombatType_t)" (?getReflectChance@Item@@QEAAFW4CombatType_t@@@Z)
1>G:\OT\vc14\x64\Release\theforgottenserver-x64.exe : fatal error LNK1120: 3 unresolved externals`

**Comment by nekiro** [comment]
I will rework this pr, because using consts as numbers in custom attributes is unsafe, cause people can overwrite that by setting number values in custom attribute by accident. Safer approach is to use string values.

**Comment by trzzu** [comment]
Reflect works good but boosts doesn't works.

**Comment by Sansero1** [comment]
> 
> 
> Reflect works good but boosts doesn't works.
> 
> I add to item attributes this line: `<attribute key="boostpercentenergy" value="150" /> `
> and its change nothing in player damage.

same problem here 
@nekiro

**Comment by trzzu** [comment]
Boosts works only on items, not for spells

**Review by EPuncker — APPROVED** [review]

**Comment by DSpeichert** [comment]
Isn't this overlapping with #3864 ?

**Comment by nekiro** [comment]
> Isn't this overlapping with #3864 ?

no

**Review by EPuncker — DISMISSED** [review]

**Comment by nekiro** [comment]
> Reflect works good but boosts doesn't works.
> 
> I add to item attributes this line: `<attribute key="boostpercentenergy" value="150" /> ` and its change nothing in player damage.



> > Reflect works good but boosts doesn't works.
> > I add to item attributes this line: `<attribute key="boostpercentenergy" value="150" /> `
> > and its change nothing in player damage.
> 
> same problem here @nekiro



> Boosts increase damage only on items, damage from spells not increase.

this was fixed with latest commit, test again

**Review by EPuncker — APPROVED** [review]

**Comment by Crypton33** [comment]
Good to see that TFS is still being developed after all these years. I'm no longer active in the open tibia server community, but gonna assume that everything works fine as it got merged in the repository.

Bounty claim accepted, good work :)

**Comment by Zbizu** [comment]
conflict with mapeditor
https://github.com/Zbizu/rme/blob/master/source/iomap_otbm.h#L51

requesting moving them to 42 and 43 if possible (the longer we wait, the more people will end up having map/database conflicts)

**Comment by Sansero1** [comment]
thank you for your great work , i really appreciate it .
some of the attributes that wasn't working works fine at the moment like (boostpercentdamage,boostpercentphysical) but
im trying to add healing percentage to an item like
`<attribute key="boostpercenthealing" value="75" />`
but it doesn't work at all , so if you can look again at it that would be great.

**Comment by Sansero1** [comment]
guys , you still working on this healing attribute ?
cause im waiting for this to be solved.

**Pull request merged**
