### PR TITLE
New items

### PR DESCRIPTION
**Pull request by raymondtfr**
New items from old updates.
Removed deprecated item "crystal bolt".

### CODE REVIEW

**Comment by marksamman** [comment]
What do you mean when you say that crystal bolt is deprecated? Is it in the deprecated group in the OTB/is it no longer in the client?

**Comment by raymondtfr** [comment]
The item is no longer *visible* ingame. So I guess if it was *visible* in previous clients then it sprite has been removed from the game. So I guess that it is no longer in the client.

**Comment by vankk** [comment]
@raymondtfr 
10.90 items?

**Comment by raymondtfr** [comment]
@vakk, Nope. Just items from old updates (10.55 to 10.77). There's still no official support for 10.90 and items.otb has to be updated in order to add 10.77+ items.

**Comment by Szmycu** [comment]
when items.otb will be updated? any announcements? There is no update for 11 months. I dont know should I use unnofficial 10.9 or wait for updating this official

**Comment by marksamman** [comment]
Please rebase.

**Comment by Szmycu** [comment]
?? I do not understand

**Comment by raymondtfr** [comment]
> Please rebase.

Rebased against the master.

**Comment by marksamman** [comment]
Thanks!

**Pull request merged**
