### PR TITLE
Codex ng17 Animated Text Support - otclient 10.98/99

### PR DESCRIPTION
**Pull request by Codex-NG17**

### CODE REVIEW

**Comment by Kamenuvol** [comment]
there should be a test of version, if its vanilla old that has this feature or if it is otclient

**Comment by Codex-NG17** [comment]
I am little confused here why there is a conflict. I used the same compat.lua as the official branch but just replaced the method

`function doSendAnimatedText(message, position, color) return Game.sendAnimatedText(message, position, color) end`

**Comment by Znote** [comment]
@Codex-NG17 Have you tested this with a regular tibia client (10.98)? If it produces a debug there we can't just implement it on good faith.

**Comment by Codex-NG17** [comment]
@Znote No I have not tested it with a regular client yet since I do most of my development in Linux, I will test it in a little while and get back to you on that.

**Comment by Codex-NG17** [comment]
@Znote I am having issues with compiling on windows so I won't be able to test the server on a regular tibia client and to be truthful I really don't feel like trouble shooting the issue because I don't program in windows... 

I could launch the regular client in wine but this feature is not meant to support the regular tibia client plus i thought the goal of TFS was to eventually move away from tibia's dependency.

I'll let you guys test it yourselves because I am not interested in whether or not its debugs a normal tibia client.

**Comment by Znote** [comment]
@Codex-NG17 I think once you have solved PR conflicts the appveyor will compile the .exe file for you. 
If we were to support unique features to OTClient, especially ones that debug the regular client, we should make it optional in config.lua, and its default value should be set to disabled.

**Comment by Codex-NG17** [comment]
@Znote I posted this on otland in the C++ code section under a avatar named Void_ and you ban me lol but yet I am allowed to do pull requests to the main branch, I don't the understand the logic.

**Comment by Codex-NG17** [comment]
Fuck this community

**Pull request closed without merging**
