### PR TITLE
Add secondary parameter "forced" to logout event

### PR DESCRIPTION
**Pull request by Leohige**
#2147

### CODE REVIEW

**Comment by vankk** [comment]
I don't think that is necessary because if you don't want the player logout just return **false** and if you want he logout just return **true**. I don't see the point of adding a new argument.

**Comment by slawkens** [comment]
With this parameter, you can distinguish if the logout was forced (normal logout) or not forced (kicked by the anti-afk system). So I find it actually useful.

And in TFS 0.4 this parameter is present too, so I am for merging this.

**Comment by vankk** [comment]
I still don't understand the logic of the needs of distinguish if it was forced or not. In my experience as a developer, if I restrict the player logout it is because there is something that he is doing in this particully moment that he shouldn't logout - even if it was by anti idle/afk.

**Comment by slawkens** [comment]
> I haven't looked at the code but my immediate understanding would be that "forced" means kicked by e.g. anti-afk system, and not-forced would be normal logout - which is the opposite of what was explained. In other words, this change is confusing and the forced should be at least renamed to something better.

You are right. It was confusing for me too, I am not even sure if that's what this parameter means in TFS 1.2, as I took a look only at TFS 0.4. And it was always 'true', except kick after inactivity - anti-afk - where it is set to 'false'.

**Comment by ranisalt** [comment]
When would it be relevant to know if a player was kicked or logged out willingly?

**Pull request closed without merging**
