### PR TITLE
Pathfinding blockPath check, fix issue #1745

### PR DESCRIPTION
**Pull request by PrinterLUA**
This is how it's currently:
http://imgland.net/?img=6WFLCfD.gif

And after:
http://imgland.net/?img=IccUuMe.gif

### CODE REVIEW

**Comment by vankk** [comment]
Good job, mate.

**Comment by marksamman** [comment]
This affects monsters and NPC's too (this is what I mean with side effects of your changes, as I said in the other PR). Aren't some monsters able to walk on those items?

**Comment by PrinterLUA** [comment]
But npcs should not walk over boxes? As for monster e.g orc should not be able, while Demon should push the box.

Since i remember on Tibia rook, people blocked orcs with boxes.

**Comment by wgrriffel** [comment]
@PrinterLUA you right, on tibia is just like that, but i remember trying something like this and screw up monsters canpushitems, i suggest you try it before, if it's okay so npc and monsters is even with tibia.

**Comment by PrinterLUA** [comment]
@marksamman 
I have made some tests and it seems that npcs has their own canWalkTo
https://github.com/otland/forgottenserver/blob/master/src/npc.cpp#L391
Here is a gif, to prove it:
http://3.1m.yt/aEyMTmm.gif

While monsters works like i expected:
Here is a Orc, which cannot push items e.g boxes:
http://1.1m.yt/0LEyTEA.gif

Here is a Demon, which can push items e.g boxes:
http://1.1m.yt/i7Fg2-C.gif

**Comment by wgrriffel** [comment]
@PrinterLUA lgtm, but still an issue imo npcs walking through blockpath items.

**Comment by PrinterLUA** [comment]
But that can easily be fixed. Or it's maybe intended that they walk over boxes.

**Comment by wgrriffel** [comment]
@PrinterLUA sure it's easy, if @marksamman like to have it, you could commit in this same PR.

**Comment by PrinterLUA** [comment]
I have no idea, if npcs should be able to walk over boxes or not. Maybe a option? I'll wait for the feedback by @marksamman

**Comment by HeavenIsLost** [comment]
"ignoreheight" option in the npc.xml make the npc able to walk over boxes/chairs.
check: https://github.com/otland/forgottenserver/blob/master/src/npc.cpp#L411

**Comment by wgrriffel** [comment]
I didn't ever noticed that, so right then i get home i'll compile with this PR looking for any unexpected behavior.

**Comment by jo3bingham** [comment]
Platinum coin marks the crate trying to be moved/used. Gold coins mark the tiles where neither are possible ("There is no way.").
How it is currently: http://i.imgur.com/MYUSSGB.jpg
With your PR: http://i.imgur.com/x65l4BV.jpg
On RL-Tibia it's possible from any of those tiles.

**Comment by wgrriffel** [comment]
agreed @jo3bingham i completely forgot about it, and this shouldnt happen.

**Comment by HeavenIsLost** [comment]
Why you did close it? did you ever found the fix?

**Comment by wgrriffel** [comment]
When git set as unknown repository can't make commits anymore, i've tried many ways to github link my branch to PR again, all failed so i think happened same to him.

**Comment by PrinterLUA** [comment]
I will take a look at it later. I going to make other pull requets that is on the roadmap.

**Pull request closed without merging**
