### PR TITLE
Correction in crate usable

### PR DESCRIPTION
**Pull request by omarcopires**
According to the Brazilian wiki when used by a player, the box is unusable for 1 real hour. This means that no player will receive any items from the box during this period. Likewise, the player who used the box will not be able to use any other box for 1 real hour.

https://www.tibiawiki.com.br/wiki/Crate_(Usable)

### CODE REVIEW

**Comment by luanluciano93** [comment]
Friend I believe you got it wrong, the script is correct, the **global storage** issue would have to be implemented by a particular **actionId** for each crate implemented on the map.

**Comment by omarcopires** [comment]
> Friend I believe you got it wrong, the script is correct, the **global storage** issue would have to be implemented by a particular **actionId** for each crate implemented on the map.
> 
> something like this, for example: https://hastebin.com/xebugigomi.rb

But my changes don't affect that, it just corrects the break time and leaves it as global storage, as it should be.

if the user wants to use the boxes in different locations this can also be easily implemented.

**Comment by luanluciano93** [comment]
But that way with **global Storage** is wrong, because this should not be taken into account in all crates. The only correct thing is time.

**Comment by EPuncker** [comment]
i'll test on real tibia right now

**Comment by EPuncker** [comment]
same server, two rusty legs, br wiki is wrong 😛

**Comment by EPuncker** [comment]
but yes, the interval should be one hour and not 20

**Comment by omarcopires** [comment]
> But this way with **Global Storage** is wrong, because it should not be taken into account in all crates. The only correct thing is time.

I'm trying to understand your logic, the original script already treated it as a single box, the only difference here is that the range will be applied to all players instead of one!

**Comment by luanluciano93** [comment]
The only change will be in the time that the player can perform the action again.

**Comment by DSpeichert** [comment]
@EPuncker Can you comment on whether any part of this PR is correct?

**Comment by EPuncker** [comment]
> @EPuncker Can you comment on whether any part of this PR is correct?

the only correct part is the use delay from 20 hours to 1 hour 😄

**Pull request merged**
