### PR TITLE
Remove monster immune effect

### PR DESCRIPTION
**Pull request by OPfeajoief13**
Monsters shouldn't receive magic effects if they're immune to the condition.

### CODE REVIEW

**Comment by wgrriffel** [comment]
why?

**Comment by OPfeajoief13** [comment]
Dragon Lords for example shouldn't receive blockhit effect if they walk on a magic field they're resistant to (fire).

**Comment by wgrriffel** [comment]
when i used to play monsters actually did make a block effect from elements that they are immune, did this changed?

**Comment by OPfeajoief13** [comment]
To be honest I'm not 100% sure, what I do know is that if a Dragon Lord with race fire walks in a firefield (type fire) it does not show any effect whatsoever.

Maybe it should be like:

if monster->getRace() == item->getMagicfield(){
No effect
}

**Comment by OPfeajoief13** [comment]
I will test this soon, maybe someone can confirm this for me

**Comment by joseluis2g** [comment]
I tested with some mobs on tibia and if monster is immune to fire the spark still showing
https://www.youtube.com/watch?v=v1grapvsY90

**Comment by OPfeajoief13** [comment]
It's indeed false.

**Pull request closed without merging**
