### PR TITLE
Added ItemType:getRequiredLevel()

### PR DESCRIPTION
**Pull request by Codinablack**
This was missing, and it was simple enough to make, no drastic alterations needed, but it is very useful for the scripters, so I hope this gets approved :+1:

### CODE REVIEW

**Comment by Jo-Tran** [comment]
Oooo Sexy =)

**Comment by Codinablack** [comment]
Do I seriously have to go through all that bs again to make new commits and merge and make another pr?

**Comment by djarek** [comment]
Just push a new commit to your master branch. It will get added automatically to this PR.

**Comment by Codinablack** [comment]
Yeah, but too many commits then, then I have to merge them again... when I get the time I guess I will have to delete my whole fucking fork again and do this all over again...

**Comment by kornholi** [comment]
You can quickly merge commits using git rebase

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Codinablack** [comment]
Was having problems with git. I finally got it to work for me. 

https://github.com/otland/forgottenserver/pull/1218

**Pull request closed without merging**
