### PR TITLE
Improves weapons scripts -- updates getMaxWeaponDamage formula

### PR DESCRIPTION
**Pull request by raymondtfr**
I have improved weapons files (damages, effects, exhaust, etc), and updated name from explosion arrow to burst arrow. Updated damage formula with an more accurate one (based on Tibia-stats).

### CODE REVIEW

**Comment by ranisalt** [comment]
You forgot to remove the old files

**Comment by raymondtfr** [comment]
What you mean? are you talking about the files in "weapons" folder? (It was an old commit but and I had problems pushing them previously, so I included them now)

**Comment by ranisalt** [comment]
You copied `explosive_arrow.lua` to `burst arrow.lua` but did not removed the former.

**Comment by raymondtfr** [comment]
Oh my. Thanks for clearing that up for me. I did not notice.

**Comment by marksamman** [comment]
1) Use underscores instead of spaces in file names.
2) Squash your commits and remove any references to Tibia in your commit message, it is a trademarked word and the goal of this project is not to copy what they do (same thing applies to #1538).

**Comment by raymondtfr** [comment]
This might be a stupid question, but do I have to remove the reference to Tibia in web address "tibia-stats"? or it isn't the same thing? :dancers:

**Pull request closed without merging**
