### PR TITLE
Raise C++ standard to C++20

### PR DESCRIPTION
**Pull request by ranisalt**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Raise the required C++ standard from C++17 to C++20. It has the following benefits (not exhaustive):

- Potentially improved compile times using concepts instead of SFINAE for code where we use `std::enable_if` 
- More expressive code through the use of [ranges](https://en.cppreference.com/w/cpp/ranges) (not range-for), views and [spans](https://en.cppreference.com/w/cpp/container/span)
- Native `std::format` that can replace fmt
- `constexpr if` and `consteval` to perform more work during compile time
- Coroutines, which can help writing generator functions where we currently generate a whole container of items before processing it (e.g. recursively navigating a container)

See more [language features](https://en.cppreference.com/w/cpp/20) and [compiler support](https://en.cppreference.com/w/cpp/compiler_support/20).

Minimum compiler version with decent C++20 support is gcc 8 and clang 6, with gcc 9 and clang 8 being mostly feature-complete.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Erza** [comment]
> Native std::format that can replace fmt
I wish. Last time I checked a few months ago, GCC still didn't support std::format. I switched to C++20 on a project because I wanted to use it, and then found out that GCC *still* did not support the C++20 text formatting at the end of 2022....

GCC 13 finally supports it now, but it's not even released yet.

**Review by EPuncker — CHANGES_REQUESTED** [review]
missing vsproject changes

**Comment by ranisalt** [comment]
> GCC 13 finally supports it now, but it's not even released yet.

It's just wishful thinking. We will still use libfmt, since we use colors, but maybe one day `std::format` matures enough :P hopefully the rest of the reasons are appealing enough

**Comment by ArturKnopik** [comment]
a lot of problems with lambdas, maybe the introduction of the C++20 standard will fix memory leaks by the way (https://github.com/otland/forgottenserver/issues/4288)

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
