### PR TITLE
Map - Fixing borders, randomizing ground palettes, other misc changes/updates to houses

### PR DESCRIPTION
**Pull request by BahamutxD**
The aim for this PR is to give the map a face lift using 10.98 features. Mostly by fixing/updating the map without making any changes to playability (pathing) whenever possible.

A list of changes

_· Fixed borders being on top of other sprites when they shouldn't_  **DONE**

_· Cleaned some unreachable tiles. Either removing out of sight or duplicated tiles underground to save file size._ **DONE**

_· Changed thick mountain ground borders and walls for the newer and thinner version for visual quality_ **DONE**

_· Randomized grounds (ie grass, rock, earth, sea) to use more variants of the same sprite present in newer .spr_ **DONE**

_· Other small issues such as underground floors not being covered by the floor above_ **DONE**

_· Fixes to dirt floor underground being broken._ https://imgur.com/dSMHpfo **DONE** 

_· Fixes to underground dirt brown walls using legacy 7.x sprite. Old walls had floor built in the sprite not allowing custom floors_ **DONE**

_· Added North and West walls to houses so they can own hangables on those walls_ **DONE**

_· Fixed several house errors (wrong tiles, block rooftops, entry points, open windows/lights...)_ **DONE**

Example of randomization made.

Old: https://i.imgur.com/MGBuIww.png

New: https://i.imgur.com/XOH186l.png

Example of underground wall fixes.

Old: https://i.imgur.com/WWZNwfO.png

New: https://i.imgur.com/Z5EdT1Z.png

Mountain ground borders

New: https://imgur.com/dZIv3wl

Old: https://imgur.com/luiD3qB

Mountain walls

Old: https://imgur.com/28rr3WG

New: https://imgur.com/Goz7MRu

Example of new North/West walls being included in the house

Old: https://imgur.com/9FdnLCN

Old: https://imgur.com/undefined

New: https://imgur.com/pEPuOcT

New: https://imgur.com/dQVUeHo

Roof blocked

Old: https://imgur.com/Etuh7SE

New: https://imgur.com/YLb3B1Y

Varak house roofs

Old: https://imgur.com/LYSC9z4

New: https://imgur.com/AvFEE40

### CODE REVIEW

**Comment by EPuncker** [comment]
feel free to keep working on it and tell us when you done then we merge 🥰

**Comment by BahamutxD** [comment]
· Randomized (mostly?) all grounds now (should be done)

· Fixed brown dirt walls underground using legacy 7.x sprite instead of the newer one allowing for custom ground (should be done)

· Some more border fixes (ongoing)

**Comment by BahamutxD** [comment]
Ready to merge

**Comment by BahamutxD** [comment]
Ready to merge

**Review by EPuncker — APPROVED** [review]

**Comment by EPuncker** [comment]
> Ready to merge

thank you

**Comment by Belden1** [comment]
https://imgur.com/pEPuOcT

In the house mentioned above, you can't hang items on unreachable walls, so not worth adding the extra cost for the player? Might not be a big deal for TFS world but just an thought for other maps or versions...

**Pull request merged**
