### PR TITLE
Fix the client crash when you open the missions window

### PR DESCRIPTION
**Pull request by MillhioreBT**
### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
The client 12.81 now needs the index of the mission that is sent to him, I do not know if it is the best way or if we need to identify the missions in another way that is not the index of the list

**Issues addressed:** Nothing!

### CODE REVIEW

**Comment by Zbizu** [comment]
You may track quests progress now. This is why it got an extra value. Overall quest log should have been rewritten, but I remember that the maintainers desire to keep compatibility blocked the pr in the past.

**Comment by omarcopires** [comment]
Maybe it's better to look this way rather than a partial solution, of course it's just a suggestion, but it would be interesting if you bring us your version of the code.

If possible take a look at this:
https://github.com/igorzerafusion/optimized_forgottenserver/commit/7b23b3503b123dc41ca86b3d48ae6557851ba988
https://github.com/igorzerafusion/optimized_forgottenserver/commit/63503e15a5513e9f83adf9477a343e86649b396f
https://github.com/igorzerafusion/optimized_forgottenserver/commit/c8f4d429abec31a23c45f3a3c31b49379ac6c900

**Review by EPuncker — APPROVED** [review]
Indeed there is a client crash (you can test it by having a non empty quest log), and this code does fix it.

**Comment by ranisalt** [comment]
And this has broken the other way around to OTClient :laughing:

**Pull request merged**
