### PR TITLE
Fixes #2665 Lua item:decay(decayId)

### LINKED ISSUE #2665: item:decay(decayId) - LUA modifies all items on server
I'm not sure, if this code is working as it should:
```
int LuaScriptInterface::luaItemDecay(lua_State* L)
{
	// item:decay(decayId)
	Item* item = getUserdata<Item>(L, 1);
	if (item) {
		if (isNumber(L, 2)) {
			ItemType& it = Item::items.getItemType(item->getID());
			it.decayTo = getNumber<int32_t>(L, 2);
		}

		g_game.startDecay(item);
		pushBoolean(L, true);
	} else {
		lua_pushnil(L);
	}
	return 1;
}
```
You call this function on some ITEM object and it modifies 'decayTo' for ALL ITEMS WITH SAME ID (for ItemType, not for 1 item).

It's only used in one place in `data` ( data/actions/scripts/other/music.lua ):
```
	if instrument.transformId then
		player:say(instrument.text, TALKTYPE_MONSTER_SAY, false, nil, item:getPosition())
		item:transform(instrument.transformId)
		item:decay(instrument.decayId)
	end
```

### PR DESCRIPTION
**Pull request by gesior**
Changed `ItemType` attribute `decayTo` to `ItemAttribute`. This attribute is savable to database.
Now it can be customized for every `Item`.

Previous version of Lua function `item:decay(decayId)` did modify `decayTo` of `ItemType`. Which did result in modyfing all items on server, not just `item` on which it was called.

### CODE REVIEW

**Comment by DSpeichert** [comment]
Please fix the commit message.

**Comment by gesior** [comment]
> Please fix the commit message.

To what message? Shorter?
```
refs #2665 fix LUA item:decay(decayId)
```
Is ok?

**Comment by DSpeichert** [comment]
1. Lua is spelled wrong
2. `refs` is not a keyword recognized by GitHub, you should use `Fixes #2665`
3. First line of commit message should not be longer than 50 characters
4. More details should come in  the following lines, separated by empty line, and can be 72 characters in length typically
5. `As title says.` looks bad

**Comment by gesior** [comment]
@DSpeichert 
Changed name, description and commit message.

**Comment by DSpeichert** [comment]
Great, thank you @gesior !

**Pull request merged**
