### PR TITLE
Update spellbook.lua add para to spell words

### PR DESCRIPTION
**Pull request by emil92b**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 
exiva - Find Person : 20
exiva **para** - Find Person : 20

https://github.com/otland/forgottenserver/pull/3648 -  required

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by emil92b** [comment]
theres 2 things left todo on spellbook:

**utevo res para - Summon Creature : var**
"**var**" should be displayed instead of mana, if the manacost is 0
` if spell.mana == 0 then
			spell.mana = "var"
		end` - something like this mby
		
**aleta sio - Invite Guests : -**
"**-**" should be displayed instead of mana, if its a house spell

**Review by EPuncker — APPROVED** [review]

**Review by Zbizu — APPROVED** [review]
Looks good to me. Remember to merge the other commit first.

**Comment by emil92b** [comment]
> Looks good to me. Remember to merge the other commit first.

not sure why, but `if spell.params then` is printing on all spells, while `> 0` did not

**Comment by Zbizu** [comment]
probably because `setField` with `false` set that field to `0` and `0` is seen as true when placed in Lua `if` statement

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
