### PR TITLE
Restart item decay in Lua after taking it out of depot

### LINKED ISSUE #1753: Decay Bug when put decaying item inside Depot Chest and logout.
Hi,

1 - First Decay Bug:
Edit an item with duration less than 5 minutes, decayto attribute and try to reproduce:
Put this item inside the house, then !leavehouse.

Duration will stop when the item reach the inbox, and never count again, and item become infinite.

2 - Second Decay Bug:

Edit an item with duration less than 5 minutes, decayto attribute and try to reproduce:
Put this item inside depot chest, then logout your character.
Login in again, and look at the item, stop the duration forever and become infinite.

Why need to fix this? For the item "claw of the nexus spawn" when lose item power, transform to new claw of the nexus spawn that have 86400 seconds duration and decay attribute, and is not the same thing like rings or anything that count the time only when equipped, always this item stop decaying forever when the player put in depot chest and leave the game, same with houses.

### PR DESCRIPTION
**Pull request by gugahoa**
Fixes #1753 
The item that stopped decaying on logout (bug), will return to decay after being taken out of depot or inbox

### CODE REVIEW

**Comment by gugahoa** [comment]
There shouldn't be anything blocking this from fixing #1753 
@marksamman @ranisalt

**Comment by ranisalt** [comment]
I'd rather fix in the sources as I don't like the idea of a script to fix a bug, it's too fragile for a clumsy scripter to unhide a bug inadvertently.

**Comment by wgrriffel** [comment]
@ranisalt i agree, either i think #1591 should be reopen to the track

**Comment by DSpeichert** [comment]
@ranisalt I don't see how #1591 relates to this issue. Are you sure you meant to reopen that?

**Comment by ranisalt** [comment]
I don't remember, probably a mistake.

**Comment by wgrriffel** [comment]
@DSpeichert @ranisalt it does not relate directly with #1591, the problem is that it was fixed through a lua script, which is not proper to this kind of issue, the same with this one

**Pull request closed without merging**
