### PR TITLE
remove unnecessary code

### PR DESCRIPTION
**Pull request by raymondtfr**

### CODE REVIEW

**Comment by marksamman** [comment]
Why is it unnecessary?

**Comment by ranisalt** [comment]
I don't think it is unnecessary. It's fallback for when the spell isn't properly configured and you can actually omit the spell group if it is attack or healing spell.

**Comment by marksamman** [comment]
Yeah, I think this is a sane default if a group hasn't been specified. We could avoid doing this if "none" has explicitly been specified as the group though (if that makes sense and that's why @raymondtfr opened this PR).

**Comment by raymondtfr** [comment]
I think it is unnecessary because it will force the spell to always have a default cooldown group (icon) assigned. But what if we want to have no effect displayed for a determined cooldown icon (this can be reverted in spells.xml)?

**Comment by raymondtfr** [comment]
Closing this as this may seem *unnecessary*.

**Pull request closed without merging**
