### PR TITLE
Update game protocol to 10990

### PR DESCRIPTION
**Pull request by jo3bingham**
Adds basic compatibility with upcoming update

### CODE REVIEW

**Comment by marksamman** [comment]
Thanks. It would be nice if we could get these changes into OTClient first, it seems like TFS currently isn't compatible with OTClient and we don't want to drift further away from OTClient.

**Comment by jo3bingham** [comment]
@marksamman Done. https://github.com/edubart/otclient/pull/770

**Comment by marksamman** [comment]
Thanks! I'll leave this open until the same protocol changes make it into OTClient then.

**Comment by brunominervino** [comment]
@jo3bingham great!!
You can make this change too:
https://github.com/otland/forgottenserver/blob/master/src/definitions.h#L28-L29

Before @marksamman merge this commit.

Just a suggestion 👍

**Comment by jo3bingham** [comment]
@brunominervino These are changes in the test server client for the upcoming winter update. CipSoft is using 10990 as the protocol version, but this could change when it's officially released. When the update is released, and I'm sure of the protocol version, I will change the definition. However, there were no changes from 10.98 to the current client version of 10.99.

**Comment by brunominervino** [comment]
@jo3bingham Excuse me, since I'm away from Tibia, I didn't know about this information.

**Comment by comedinha** [comment]
https://github.com/comedinha/Flash-News/commit/0ff896fa8a8947533fb5a5307b853185a972f24c
10.99 launch option to show focus on flash...

**Comment by comedinha** [comment]
Have update to 11.01?

**Comment by Olimpotibia** [comment]
the bytes for sendmarketdetails dont work if you try to pen market and check item details wirh client 10.00

anyone have solution for this?


thnx anywayD:

**Comment by Riverlance** [comment]
@marksamman I use your TFS as 10.99 with the OTClient. And there is no problem with. The OTClient supports the protocol 10.99 yet. :)

**Comment by jo3bingham** [comment]
> Have update to 11.01?
@comedinha https://otland.net/threads/protocol-version-1101.247854/

> the bytes for sendmarketdetails dont work if you try to pen market and check item details wirh client 10.00
@Olimpotibia No other changes were made to the MarketDetail packet apart from what I committed. Not sure what the problem could be.

**Comment by comedinha** [comment]
@jo3bingham When there are many players this fix does not work.

**Comment by Marahin** [comment]
So, any update on this @comedinha @jo3bingham? Is there a way to run Tibia 11(.01) with Forgotten Server right now?

**Comment by jo3bingham** [comment]
@Marahin there's been further changes to the protocol since then that I've addressed on OTLand forums. In fact, this PR should be closed in favor of a new one.

**Comment by Marahin** [comment]
@jo3bingham thank you for caring to answer :-). For now, until Forgotten Server supports it, I'll stick with some unofficial changes I've found. Thanks!

**Pull request closed without merging**
