### PR TITLE
Use STL algorithms instead of loop in vocations.cpp

### PR DESCRIPTION
**Pull request by ranisalt**
With C++14, we will replace these `decltype(vocationsMap)::value_type` with `auto`

### CODE REVIEW

**Review by DSpeichert — APPROVED** [review]

**Review by MillhioreBT — APPROVED** [review]
Tested and work!
LGTM

**Comment by Czopeq** [comment]
*cough* from O(n) to O(n+1) *cough cough* nice.

**Review by EPuncker — APPROVED** [review]

**Comment by ranisalt** [comment]
> _cough_ from O(n) to O(n+1) _cough cough_ nice.

image

**Review by nekiro — APPROVED** [review]

**Comment by ranisalt** [comment]
Thanks!

**Pull request merged**
