### PR TITLE
Login protection

### PR DESCRIPTION
**Pull request by PrinterLUA**
Now players will not be able to get attacked or damaged when they login after certain seconds.

### CODE REVIEW

**Comment by WibbenZ** [comment]
What was the reason for closing this? Seems like a cool thing to have if the player(s) is/are kicked from the server.

**Comment by dalkon** [comment]
Probably because nothing has happened since December 9th.

**Comment by WibbenZ** [comment]
Yes, but nothing else has been pointed out as wrong or bugged :p

**Comment by Codinablack** [comment]
@WibbenZ maybe you didn't see it pointed out on here, but it was pointed out elsewhere that multiple commits like that must be squashed, and he told printer specifically that some of his needed to be squashed before he would add them...

**Pull request closed without merging**
