### PR TITLE
New function [leaveChannel]

### PR DESCRIPTION
**Pull request by moviebr**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This function allows the player to close an open chat.

### CODE REVIEW

**Review by EPuncker — APPROVED** [review]

**Comment by ranisalt** [comment]
What's the use case?

**Review by ranisalt — APPROVED** [review]

**Comment by ranisalt** [comment]
> Honestly, I thought of using it in a system that I developed using AntiBot, in which it opens its own chat to verify this. Without this new function, the chat could remain open there forever.

Ah, super cool!

**Comment by MillhioreBT** [comment]
The name of the method is quite weird for what it actually does.
I don't know, but it bothers me that the method is called "close", and in reality all it does is trigger the "onLeave" event of the chat, but the channel remains open.

This method was created for the client to call it when the chat is really closed physically from the client side.

to make a player unable to write in the chat, u can be controlled through a Lua variable.
Apparently, Cip's client does not need to close channels from the server side. Or does it? How?

**Comment by EPuncker** [comment]
> The name of the method is quite weird for what it actually does. I don't know, but it bothers me that the method is called "close", and in reality all it does is trigger the "onLeave" event of the chat, but the channel remains open.
> 
> This method was created for the client to call it when the chat is really closed physically from the client side.
> 
> to make a player unable to write in the chat, u can be controlled through a Lua variable. Apparently, Cip's client does not need to close channels from the server side. Or does it? How?
> 
> maybe call it `player:leaveChannel()`?

indeed we need a better and more descriptive name

**Review by EPuncker — APPROVED** [review]

**Review by ramon-bernardo — APPROVED** [review]

**Review by ramon-bernardo — APPROVED** [review]

**Review by EPuncker — APPROVED** [review]

**Pull request merged**
