### PR TITLE
Added new groups

### LINKED ISSUE #2248: [Question] New groups
We should set more groups to _groups.xml_ to make more easier to the AAC creators, as admin as well. 

Currently in our datapack we only have player, gamemaster and god.

**We should a few groups for example:**
- Tutor
- Senior Tutor
- Community Manager

Also in the _groups.xml_, we should provide a comment that have a flag calculator to if someone wants modify the flags.

What you guys think?

Regards,
vankk.

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
added tutor, senior tutor and community manager to groups.xml

**Issues addressed:** 
fixes #2248

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by Zbizu** [comment]
imo unnecessary. Anyone who needs tutors will code it himself.

**Review by DSpeichert — APPROVED** [review]

**Review by DSpeichert — APPROVED** [review]

**Comment by Alkenix** [comment]
Any idea how to get /reload commands working again after updating to this?
I've already changed the group on my acc and god-char.
Teleport etc. works but /reload commands don't.

**Comment by Zbizu** [comment]
@Alkenix group 5 access 5 required

**Comment by Alkenix** [comment]
> @Alkenix group 6 account type 6 required

Yep I know. Still not working.

**Pull request merged**
