### PR TITLE
Many words in talkactions

### PR DESCRIPTION
**Pull request by rookgaard**
Hello.

I would like to introduce another thing that is missing compared to 0.X and it was very useful in my opinion - many words in one talkaction entry (that's why it's called `words` not `word`). The simpliest example - you can have 2 entries in talkactions.xml to display players online - by typing `!online` and `/online`, but with this code you can combine them into one entry - `!online;/online`.

@DSpeichert  I hope this PR won't receive comment `This is not a feature that provides anything you can't already do.` - because if something can be done easier, why not have it?

Duplicate of #3132

### CODE REVIEW

**Comment by joseluis2g** [comment]
I never tried this but wasnt this already possible? if not im sorry and great job

**Comment by korejwo** [comment]
@joseluis2g No, because engine register it as string https://github.com/otland/forgottenserver/blob/master/src/talkaction.cpp#L71  without exploding by delimiter https://github.com/otland/forgottenserver/blob/master/src/talkaction.cpp#L137.

**Comment by rookgaard** [comment]
@joseluis2g No, because engine register it as string https://github.com/otland/forgottenserver/blob/master/src/talkaction.cpp#L71  without exploding by delimiter https://github.com/otland/forgottenserver/blob/master/src/talkaction.cpp#L137.

**Comment by kygov** [comment]
Why not just use `playerSaySpell` and iterate through words map? In this way its creating new Talkaction object for every words, or I'm wrong?

**Comment by rookgaard** [comment]
@kygov Talkaction object is created once (https://github.com/otland/forgottenserver/blob/master/src/talkaction.cpp#L77, https://github.com/rookgaard/forgottenserver/blob/feature/talkactions-words/src/talkaction.cpp#L82) and then just it's address is copied for every word. It's made the same way as actions where object is created once (https://github.com/otland/forgottenserver/blob/master/src/actions.cpp#L197) and then addres copied for every ID (https://github.com/otland/forgottenserver/blob/master/src/actions.cpp#L201).

**Comment by gpedro** [comment]
what's the difference between #3132 and yours?

**Comment by EPuncker** [comment]
> what's the difference between #3132 and yours?

one for xml and other for revscript

**Comment by MillhioreBT** [comment]
> > what's the difference between #3132 and yours?
> 
> one for xml and other for revscript

My RP now supports XML too, if you want to give it a try and give me recommendations, here I am ;)

**Comment by rookgaard** [comment]
My one also support revscripts too from now and requires less code changes :)

@DSpeichert what means `decisions` label? It means PR waits for review?

**Comment by MillhioreBT** [comment]
> My one also support revscripts too from now and requires less code changes :)
> 
> @DSpeichert what means `decisions` label? It means PR waits for review?

Hello Goodnight!
I will not say which modification is better or more efficient, the decision will be made by all together!
What I did not like was that you put that my PR was duplicate, when in reality the duplicate is yours, just look at the date and the PR number

```lua
print(3132 < 3137)
-- true
```

regards!!

**Review by Znote — APPROVED** [review]
Tested, both XML and Revscriptsys works great. :) 

image

**Pull request merged**
