### PR TITLE
Renamed a few files to keep a default naming style

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Renamed a few files to keep a default naming style

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by ranisalt** [comment]
Ok let's just review all of them to avoid having several PRs renaming a couple of files. I can see `advertisement-rook.lua` right there that should also be changed.

**Comment by EPuncker** [comment]
> Ok let's just review all of them to avoid having several PRs renaming a couple of files. I can see `advertisement-rook.lua` right there that should also be changed.

the only stuff left are: npc lib files (I don't know if it was a good idea to rename them), and source files

**Review by ramon-bernardo — DISMISSED** [review]

**Review by ranisalt — APPROVED** [review]

**Comment by DSpeichert** [comment]
@EPuncker conflcits.

**Comment by EPuncker** [comment]
> @EPuncker conflicts.

resolved

**Review by DSpeichert — APPROVED** [review]

**Pull request merged**
