### PR TITLE
Added A LOT of missing items up to version 10.98

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

- Added lots of missing items up to version 10.98 based on client files
- Fixed all articles
- Fixed most of the names

we can say we have like 99% of the items right now

all of that possible thanks to @MillhioreBT and @jo3bingham and @giuinktse7

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by ranisalt — DISMISSED** [review]

**Comment by Zbizu** [comment]
Items load properly so syntax is alright.
Loading monsters spat out several warnings:
```
[Warning - Monsters::loadMonster] Non-unique loot item "power bolt".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/dragon_l
ord.xml
[Warning - Monsters::loadMonster] Non-unique loot item "dragon lord trophy".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/dragon_l
ord.xml
[Warning - Monsters::loadMonster] Non-unique loot item "burst arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/dragon.x
ml
[Warning - Monsters::loadMonster] Non-unique loot item "arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/elf_scou
t.xml
[Warning - Monsters::loadMonster] Non-unique loot item "arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/elf_arca
nist.xml
[Warning - Monsters::loadMonster] Non-unique loot item "grave flower".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/elf_arca
nist.xml
[Warning - Monsters::loadMonster] Non-unique loot item "halberd".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/black_kn
ight.xml
[Warning - Monsters::loadMonster] Non-unique loot item "arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/elf.xml
[Warning - Monsters::loadMonster] Non-unique loot item "halberd".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/cyclops.
xml
[Warning - Monsters::loadMonster] Non-unique loot item "arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/hunter.x
ml
[Warning - Monsters::loadMonster] Non-unique loot item "burst arrow".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/hunter.x
ml
[Warning - Monsters::loadMonster] Non-unique loot item "halberd".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/orc_bers
erker.xml
[Warning - Monsters::loadMonster] Non-unique loot item "cherry".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/bug.xml
[Warning - Monsters::loadMonster] Non-unique loot item "grave flower".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/monsters/vampire.
xml
```

Regarding changes in items.xml itself, the names themselves look alright, but I do recommend re-checking item attributes @EPuncker, see: https://github.com/otland/forgottenserver/pull/3508/files#diff-91ad02cf0392428a8eee4cac4012de4c8f3b42319fd87ee93bf2873b19461875R13166 for example

**Review by Zbizu — DISMISSED** [review]

**Comment by DSpeichert** [comment]
Probably worth fixing non-unique loot item names?

**Review by ranisalt — APPROVED** [review]

**Comment by BahamutxD** [comment]
I've been reviewing items.xml for some time now and haven't been able to find a single issue.

My idea was to eventually do the whole thing but seeing how I am unable to find any issue after 15-20% of the file reviewed + a fast look over the whole thing - I find it safe to assume it's for the most part good to go.

**Comment by Alkenix** [comment]
image
Downloaded the latest branch monster folder (last edit by EPuncker) and fixed all of them in it.
But I dunno how to get them into the latest branch.. Sorry. 
So here are the changed luas:
[changes.zip](https://github.com/otland/forgottenserver/files/6967907/changes.zip)

**Comment by ranisalt** [comment]
@Alkenix check #3540 #3538

**Comment by Alkenix** [comment]
@ranisalt Yep. Still had the errors. :)

**Pull request merged**
