### PR TITLE
throwing items and distance attacks rework

### LINKED ISSUE #2891: Directional spells vs. walls behaviour
### Notes
Original thread:
https://otland.net/threads/spells-versus-walls.268213/

His issue was caused by using OTX repo:
https://github.com/mattyx14/otxserver/commit/42c9cda0558aa994613d548338a463603fbddd69

But he brings up the point that rl tibia has different behaviour.
https://otland.net/threads/spells-versus-walls.268213/page-3#post-2592654

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login to game.
2. Face wall.
3. Use a directional wave or strike spell.

### Expected behaviour
The spell goes off and cost mana regardless;
But the spell only hit actually hits a SQM if `isSightClear() == true` and `CONST_PROP_BLOCKSOLID == false`.

### Actual behaviour
You get `RETURNVALUE_NOTENOUGHROOM` instead.

Here:
https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L229

### PR DESCRIPTION
**Pull request by Zbizu**
fixes the behaviour of isSightClear (#2727)

things to test:
- throwing items
- throwing items between floors
- throwing distance attacks

the github comparing broke for some reason

edit: potentially closes #2891

### CODE REVIEW

**Comment by EPuncker** [comment]
okay I finally got my server on to test this, and everything seems fine:

the report situation:
depois

item throwing and item throwing between floors seems to be fine as well

**Comment by Zbizu** [comment]
1d7f7bfe0cd2a213382661f0fbe2189c

I've got a report that it was possible to throw an item to the place where platinum coin is (possible rounding error/different compiler(?)). However, the problem doesn't occur when I compile tfs locally. Any advice how to fix it so it's the same for every platform?

**Comment by gigastar** [comment]
https://pastebin.com/9PC33p1X

**Comment by Zbizu** [comment]
@gigastar any context for this paste?

**Comment by gigastar** [comment]
Sorry, I just modified the code to match the rest of TFS files. For instance, abs() to std::abs()

**Comment by DSpeichert** [comment]
> Sorry, I just modified the code to match the rest of TFS files. For instance, abs() to std::abs()

You should submit a review using GH interface, you can include code suggestions even. A paste is... not useful.

**Comment by Zbizu** [comment]
I won't be working on it anytime soon. If someone is interested in finishing it, feel free to create a separate pull request using edited version of these changes. I'm leaving it open until it gets solved.

**Comment by gigastar** [comment]
I don't know how to create a pull request so... I fixed a few problems that I found in this code. (You couldn't throw items correctly the the left or to the top right of the screen. This fixes that problem and may fix the "rounding problem" mentioned. 

`//get a line between two points
//based on Xiaolin Wu algorithm
std::vector< std::pair<int, int> > get2DLine(int x0, int y0, int x1, int y1)
{
	std::vector< std::pair<int, int> > line;
	if (x0 == x1 && y0 == y1) {
		return line;
	}

	bool isSteep = std::abs(y1 - y0) > std::abs(x1 - x0);
	if (isSteep) {
		std::swap(x0, y0);
		std::swap(x1, y1);
	}

	if (x0 > x1) {
		std::swap(x0, x1);
		if (y0 < y1) {
			std::swap(y0, y1);
		}
	}

	float dx = x1 - x0;
	float dy = y1 - y0;
	double grad = 1.0;

	if (dx != 0) {
		grad = dy * 1.0 / dx;
	}

	if (grad < 0) {
		grad = grad * -1;
	}

	double interY = y0 + grad; //first y - intersection for the main loop

	if (isSteep) {
		for (int y = x0 + 1; y < x1; y++) {
			if (interY < 0) {
				interY = interY * -1;
			}
			int newX = std::floor(interY);
			int newY = y;
			line.push_back({ newX, newY });
			interY += grad;
		}
	}
	else {
		for (int x = x0 + 1; x < x1; x++) {
			if (interY < 0) {
				interY = interY * -1;
			}
			int newX = x;
			int newY = std::floor(interY);
			line.push_back({ newX, newY });
			interY += grad;
		}
	}

	// now we need to perform a jump between floors to see if everything is clear (literally)
	return line;
}`

**Comment by EPuncker** [comment]
closing this as https://github.com/otland/forgottenserver/pull/3265 is pretty much done, thank you @Zbizu

**Pull request closed without merging**
