### PR TITLE
Added The Mutated Pumpkin

### PR DESCRIPTION
**Pull request by EPuncker**
Along with its corpse skinning rewards each 4 hours

- added missing slain mutated pumpkin corpse (the skinnable one)

https://tibia.fandom.com/wiki/The_Mutated_Pumpkin

### CODE REVIEW

**Comment by EPuncker** [comment]
tested and working, but further tests are always more than welcome

**Comment by BahamutxD** [comment]
Is the itemid 26383 correct? It doesn't seem to work/exist in 10.98

id 13583 is a dead pumpkin while 8960/8961/8962/8963 are the corpse + decays.

image

**Comment by EPuncker** [comment]
@BahamutxD 
try now please

**Comment by BahamutxD** [comment]
@EPuncker Things look good now good work!

Just a couple of small things. 

· The corpse id 13583 is a container- not sure if it should be like that.
· Chocolate bars are not stackable (they are supposed to be according to tibiawiki) This is an issue here specially when you get the x50 bars reward.

**Comment by EPuncker** [comment]
> @EPuncker Things look good now good work!
> 
> Just a couple of small things.
> 
> · The corpse id 13583 is a container- not sure if it should be like that.
> · Chocolate bars are not stackable (they are supposed to be according to tibiawiki) This is an issue here specially when you get the x50 bars reward.

seems like our non updated items.otb will bring some issues now 😄 what should we do @DSpeichert

**Comment by DSpeichert** [comment]
@EPuncker Conflicts

**Comment by EPuncker** [comment]
> @EPuncker Conflicts

fixed

**Pull request merged**
