### PR TITLE
Fix Player.onMoveItem not being called when switching items in inventory

### LINKED ISSUE #1804: onMoveItem Event bug
### Expected behaviour

Should not be moved from the slotPosition, either by just draging the item or switching the item with another item.
### Actual behaviour

I've made an item, in the event onMoveItem not being moveable, but still it's possible if you switch the item with another item e.g if the item is in the feet slot and you move another pair of boots to that slot. The "unmoveable" boots gets switched. But trying moving them out, would not work, you have to switch.
### Environment

Latest tfs.

### PR DESCRIPTION
**Pull request by marmichalski**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Check if swapped item can be moved 🤷 

**Issues addressed:** Closes #1804.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by MillhioreBT — COMMENTED** [review]
I have not tried it, but at first glance I like this!

**Comment by nekiro** [comment]
What exactly this fixes? I'm concerned that linked bug issue does not happen with current code.

**Comment by marmichalski** [comment]
> What exactly this fixes? I'm concerned that linked bug issue does not happen with current code.

It fixes exactly what's described in the issue.

**Review by MillhioreBT — APPROVED** [review]
LGTM

**Review by EPuncker — APPROVED** [review]

**Review by nekiro — APPROVED** [review]

**Pull request merged**
