### PR TITLE
Reverting PR

### PR DESCRIPTION
**Pull request by tornadia**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Fixes https://github.com/otland/forgottenserver/issues/4263
Reverts https://github.com/otland/forgottenserver/pull/3495/files

**Issues addressed:** [4263](https://github.com/otland/forgottenserver/issues/4263)

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by EPuncker** [comment]
@danyelvarejao can you check this please

**Comment by danyelvarejao** [comment]
I think it should be like @ranisalt said.
```c
if (forceLoad || (reloading && monsters.find(it.first) != monsters.end())) {
```

**Comment by tornadia** [comment]
> I think it should be like @ranisalt said.
> 
> ```c
> if (forceLoad || (reloading && monsters.find(it.first) != monsters.end())) {
> ```

It literally makes no difference to wrap that statement around parentheses as that is what the order of operators is already doing, i.e. BEDMAS/PEDMAS in math, AND (&&) operators have precedence over OR (||)

**Comment by ranisalt** [comment]
For reference: https://en.cppreference.com/w/cpp/language/operator_precedence

It would be good to wrap for clarity, it's not _that_ obvious

**Review by ranisalt — APPROVED** [review]
To whoever merges this, please add a proper commit message

**Review by EPuncker — APPROVED** [review]

**Comment by EPuncker** [comment]
> To whoever merges this, please add a proper commit message

I love chatGTP

**Pull request merged**
